import type {CurriculumExercise} from './types';

export interface ExamPart {prompt:string;points:number;}
export interface ExamQuestion {stem:string;points:number;parts?:ExamPart[];selfCheck:boolean;}
type Addition={topicId:string;item:CurriculumExercise;question:ExamQuestion;difficulty:'Medium'|'Hard'|'Exam-level'};
const tex=String.raw;
function written(id:number,topic:number,skill:'A'|'B',source:string,title:string,stem:string,parts:ExamPart[],explanation:string,rubric:string[],difficulty:Addition['difficulty']='Exam-level'):Addition{
 const code=String(topic).padStart(2,'0');
 return {topicId:`CALC_T${code}`,difficulty,item:{id:`CALC_E${id}`,title,prompt:[stem,...parts.map((part,index)=>`${String.fromCharCode(97+index)}) ${part.prompt}`)].join('\n'),skillId:`CALC_S${code}${skill}`,sourceIds:[source],kind:'open',explanation,rubric},question:{stem,parts,points:parts.reduce((sum,part)=>sum+part.points,0),selfCheck:true}};
}
function exact(id:number,topic:number,skill:'A'|'B',source:string,title:string,prompt:string,answer:string,explanation:string,difficulty:Addition['difficulty']='Medium'):Addition{
 const code=String(topic).padStart(2,'0');
 return {topicId:`CALC_T${code}`,difficulty,item:{id:`CALC_E${id}`,title,prompt,skillId:`CALC_S${code}${skill}`,sourceIds:[source],kind:'integer',answer,explanation},question:{stem:prompt,points:1,selfCheck:false}};
}

export const calculusAdditions:Addition[]=[
 written(101,1,'B','CALC_SRC_FOUNDATIONS','Joining oscillatory and polynomial branches',tex`Let $f(x)=\sin(3x)/x$ for $x<0$, $f(0)=a$, and $f(x)=3+bx+x^2$ for $x>0$.`,[
  {prompt:tex`Find both one-sided limits at $0$.`,points:2},{prompt:tex`Choose $a$ for continuity.`,points:1},{prompt:tex`Find $b$ for differentiability at $0$ and justify the left derivative using a limit or Taylor expansion.`,points:3}],
  tex`Both limits equal $3$, so $a=3$. Since $\sin(3x)/x=3-\frac92x^2+O(x^4)$, the left difference quotient tends to $0$. The right derivative is $b$, hence $b=0$.`,
  ['2 points: establish the two limits separately.','1 point: match the value at zero to the common limit.','3 points: calculate both difference quotients and conclude b=0.']),
 exact(102,1,'A','CALC_SRC_FOUNDATIONS','Count admissible integer inputs',tex`How many integers belong to the real domain of $h(x)=\frac{\ln(9-x^2)}{x-1}$? Enter the count.`, '4',tex`The logarithm requires $-3<x<3$, and $x=1$ is excluded by the denominator. The allowed integers are $-2,-1,0,2$: four inputs.`),
 written(103,2,'A','CALC_SRC_DERIVATIVES','A rational curve beyond its first derivative',tex`Consider $f(x)=\frac{x^2}{1+x^2}$ on the real line.`,[
  {prompt:tex`Find and simplify $f'(x)$.`,points:2},{prompt:tex`Find $f''(x)$.`,points:2},{prompt:'Find all inflection points and justify the changes in concavity.',points:2}],
  tex`The derivatives are $f'(x)=\frac{2x}{(1+x^2)^2}$ and $f''(x)=\frac{2(1-3x^2)}{(1+x^2)^3}$. The denominator is positive. Concavity changes at $x=\pm1/\sqrt3$, where $f=1/4$. The inflection points are $(\pm1/\sqrt3,1/4)$.`,
  ['2 points: quotient rule and simplification.','2 points: product/chain rule for the second derivative.','2 points: both coordinates and a sign-change argument.']),
 exact(104,2,'A','CALC_SRC_DERIVATIVES','Implicit differentiation with an exponential',tex`The curve $ye^x+xy^2=2$ passes through $(0,2)$. Find $y'(0)$ for its local differentiable branch.`, '-6',tex`Differentiating gives $e^xy'+ye^x+y^2+2xyy'=0$. At $(0,2)$ this is $y'+2+4=0$, so $y'=-6$. The coefficient of $y'$ is $1$, so the local derivative is defined.`),
 written(105,3,'A','CALC_SRC_INTEGRALS','Substitution followed by integration by parts',tex`Let $I=\int_0^1 x\ln(1+x^2)\,dx$.`,[
  {prompt:'Transform the definite integral using a substitution, including the new bounds.',points:2},{prompt:'Evaluate the transformed integral by parts.',points:2},{prompt:tex`Prove $0<I<\frac12\ln 2$ without decimal approximations.`,points:2}],
  tex`Set $u=1+x^2$, so $I=\frac12\int_1^2\ln u\,du=\frac12[u\ln u-u]_1^2=\ln2-\frac12$. For $0<x<1$, $0<x\ln(1+x^2)<x\ln2$. Integrating gives the strict bounds.`,
  ['2 points: substitution, factor 1/2 and bounds 1 to 2.','2 points: integration by parts and exact value.','2 points: compare the integrands on an interval of positive length.']),
 exact(106,3,'A','CALC_SRC_INTEGRALS','Recognize a derivative under an integral',tex`Evaluate $\int_{-1}^{1}\frac{3x^2+x^4}{(1+x^2)^2}\,dx$. Hint: differentiate $x^3/(1+x^2)$.`, '1',tex`The quotient rule gives $\frac{d}{dx}\frac{x^3}{1+x^2}=\frac{3x^2+x^4}{(1+x^2)^2}$. The fundamental theorem gives $1/2-(-1/2)=1$.`),
 written(107,4,'A','CALC_SRC_LIMIT_PROCESSES','A parameter-dependent improper integral',tex`For real $p$, consider $J(p)=\int_1^\infty\frac{\ln x}{x^p}\,dx$.`,[
  {prompt:tex`Use $x=e^t$ to transform the integral.`,points:2},{prompt:'Determine exactly which values of p give convergence.',points:2},{prompt:'Evaluate J(p) throughout its convergence range.',points:2}],
  tex`The transformed integral is $\int_0^\infty t e^{-(p-1)t}\,dt$. For $p>1$, integration by parts gives $J(p)=1/(p-1)^2$; the boundary term tends to zero. At $p=1$ the integrand is $t$, and for $p<1$ it grows exponentially, so both cases diverge.`,
  ['2 points: transform both the differential and the bounds.','2 points: establish convergence for p>1 and divergence for p<=1.','2 points: integrate by parts, including the limiting boundary term.']),
 exact(108,4,'B','CALC_SRC_LIMIT_PROCESSES','A cancellation-sensitive sequence',tex`Find $\lim_{n\to\infty}2n\left(\sqrt{1+3/n}-1\right)$.`, '3',tex`Rationalization gives $6/(\sqrt{1+3/n}+1)$, which tends to $3$. The vanishing bracket cannot be replaced by zero before multiplication by n.`),
 written(109,5,'B','CALC_SRC_SERIES','Alternation, absolute convergence and error',tex`Consider $\sum_{n=1}^{\infty}(-1)^{n-1}\frac{n}{n^2+1}$.`,[
  {prompt:'Decide whether the series converges and verify the relevant hypotheses.',points:2},{prompt:'Decide whether convergence is absolute or conditional.',points:2},{prompt:tex`Find the smallest number of terms $N\ge1$ for which the alternating-series bound guarantees error at most $1/100$.`,points:2}],
  tex`The positive magnitudes tend to zero and decrease for $n\ge1$, since the derivative of $x/(x^2+1)$ is $(1-x^2)/(x^2+1)^2$. The absolute series diverges by limit comparison with $1/n$, with ratio tending to 1. Convergence is conditional. The error bound is $(N+1)/((N+1)^2+1)$. At N=98 it exceeds 1/100, and at N=99 it is $100/10001<1/100$; monotonicity proves minimality.`,
  ['2 points: decreasing magnitudes and zero limit.','2 points: harmonic limit comparison and conditional classification.','2 points: next-term bound, N=99 and failure at N=98.']),
 exact(110,5,'A','CALC_SRC_TAYLOR','A weighted geometric series',tex`Evaluate $12\sum_{n=1}^{\infty}\frac{n}{3^n}$.`, '9',tex`For $|r|<1$, differentiating the geometric series gives $\sum_{n=1}^{\infty}nr^n=r/(1-r)^2$. At $r=1/3$ this is $3/4$, and multiplication by 12 gives 9.`, 'Hard'),
 written(111,6,'B','CALC_SRC_TAYLOR','Taylor cancellations in a product',tex`Let $g(x)=e^x\cos x$.`,[
  {prompt:'Find the Maclaurin polynomial through degree four.',points:3},{prompt:tex`Evaluate $\lim_{x\to0}\frac{g(x)-1-x}{x^3}$.`,points:2},{prompt:tex`Find $g^{(4)}(0)$.`,points:1}],
  tex`Multiplying the exponential and cosine series gives $g(x)=1+x-\frac13x^3-\frac16x^4+O(x^5)$. The quadratic term cancels. The limit is $-1/3$, and $g^{(4)}(0)=4!(-1/6)=-4$.`,
  ['3 points: correct product through degree four, including the zero quadratic term.','2 points: use the first nonzero remaining term.','1 point: multiply the coefficient by 4 factorial.']),
 exact(112,6,'B','CALC_SRC_TAYLOR','Recover a high derivative from a series',tex`For $f(x)=\ln(1+x^2)$, find $f^{(6)}(0)$.`, '240',tex`The expansion is $x^2-x^4/2+x^6/3+O(x^8)$. Thus $f^{(6)}(0)=6!/3=240$.`, 'Hard'),
 written(113,7,'A','CALC_SRC_PARTIALS','Partial derivatives without continuity',tex`Define $f(x,y)=\frac{xy^2}{x^2+y^4}$ away from $(0,0)$ and set $f(0,0)=0$.`,[
  {prompt:'Find both first partial derivatives at the origin from their definitions.',points:2},{prompt:tex`Compare approaches along $x=0$ and $x=y^2$.`,points:2},{prompt:'Decide continuity and differentiability at the origin, with justification.',points:2}],
  tex`Both coordinate-axis restrictions are identically zero, so $f_x(0,0)=f_y(0,0)=0$. Along $x=0$ the limit is zero, whereas along $x=y^2$ with $y\ne0$ the value is $1/2$. There is no two-variable limit. The function is not continuous and therefore not differentiable at the origin.`,
  ['2 points: use coordinate difference quotients, not a formula undefined at the origin.','2 points: valid paths with limits 0 and 1/2.','2 points: distinguish existence of partials from continuity and differentiability.']),
 exact(114,7,'B','CALC_SRC_PARTIALS','Mixed partials with a coupled exponent',tex`For $f(x,y)=xe^{xy}$, compute $f_{xy}(1,0)$.`, '2',tex`First $f_x=e^{xy}(1+xy)$. Then $f_{xy}=xe^{xy}(2+xy)$, which is 2 at (1,0).`),
 written(115,8,'B','CALC_SRC_GRADIENT','Extrema on a triangular region',tex`Find the absolute extrema of $f(x,y)=x^2+xy+y^2$ on $x\ge0$, $y\ge0$, $x+y\le2$.`,[
  {prompt:'Solve the stationary equations and identify whether the candidate is interior.',points:2},{prompt:'Examine all three edges, including their endpoints.',points:3},{prompt:'State the absolute minimum and maximum with every location.',points:1}],
  tex`The stationary equations give only (0,0), which lies on the boundary. On the axes, f is a square between 0 and 4. On $x+y=2$, $f=(x-1)^2+3$ for $0\le x\le2$, with values from 3 to 4. The minimum is 0 only at (0,0); the maximum is 4 at (2,0) and (0,2).`,
  ['2 points: solve both equations and notice the boundary location.','3 points: analyze each edge, including the critical point on the sloping edge.','1 point: compare all candidates and list all extremizers.']),
 exact(116,8,'A','CALC_SRC_GRADIENT','Second change along a curved path',tex`Let $F(x,y)=xy^2+\ln x$, $x(t)=e^t$ and $y(t)=\sin t$. Find $\frac{d^2}{dt^2}F(x(t),y(t))$ at $t=0$.`, '2',tex`Substitution gives $e^t\sin^2t+t=t+t^2+O(t^3)$. The second derivative at zero is therefore 2. Direct differentiation twice gives the same value.`, 'Hard'),
 written(117,9,'B','CALC_SRC_COMPLEX','Roots, products and a real polynomial',tex`Consider the equation $z^3=-8i$.`,[
  {prompt:'Find all three roots in Cartesian form.',points:3},{prompt:'Verify their sum and product.',points:1},{prompt:'Find a monic real polynomial of least degree containing these roots and all their conjugates.',points:2}],
  tex`The roots are $\sqrt3-i$, $2i$, and $-\sqrt3-i$, obtained with modulus 2 and angles $-\pi/6+2k\pi/3$. Their sum is 0 and product is $-8i$. Their conjugates solve $z^3=8i$; the two root sets are disjoint. The required degree-six polynomial is $(z^3+8i)(z^3-8i)=z^6+64$.`,
  ['3 points: three distinct roots with correct modulus and angles.','1 point: sum zero and product -8i.','2 points: include conjugates, prove disjointness, and multiply the factors.']),
 exact(118,9,'B','CALC_SRC_COMPLEX','Common roots of unity',tex`How many distinct complex numbers satisfy both $z^6=1$ and $z^4=1$?`, '2',tex`Every solution is nonzero, so division gives $z^2=1$. Both 1 and -1 satisfy the original equations, giving exactly two common roots.`),
 written(119,10,'B','CALC_SRC_DOUBLE','Reverse bounds and find an average',tex`Let $D=\{(x,y):0\le x\le1,\ x\le y\le\sqrt{x}\}$.`,[
  {prompt:'Describe D with y as the outer variable.',points:2},{prompt:tex`Evaluate $\iint_D y\,dA$.`,points:2},{prompt:'Find the area of D and the average value of y on D.',points:2}],
  tex`The reversed description is $0\le y\le1$, $y^2\le x\le y$. Thus $\iint_D y\,dA=\int_0^1(y^2-y^3)\,dy=1/12$. The area is $\int_0^1(y-y^2)\,dy=1/6$, so the average is $(1/12)/(1/6)=1/2$.`,
  ['2 points: both bounds and the outer interval.','2 points: integrate over the correctly described region.','2 points: area 1/6 and division by area to obtain 1/2.']),
 exact(120,10,'B','CALC_SRC_DOUBLE','Mass under a sloping density',tex`A lamina occupies $x\ge0$, $y\ge0$, $x+y\le2$ and has density $\rho(x,y)=12-3x-3y$. Find its total mass.`, '16',tex`Integrate $\int_0^2\int_0^{2-x}(12-3x-3y)\,dy\,dx$. The constant contributes 24, and $3\iint_D(x+y)\,dA=8$. The mass is 16; density is positive throughout D.`, 'Hard'),

 // Eight distinct additions per topic complete the twenty-question topic banks.
 written(121,1,'A','CALC_SRC_FOUNDATIONS','Invert a fractional map',tex`Let $f(x)=(x+1)/(x-1)$ on $\mathbb R\setminus\{1\}$.`,[
  {prompt:'Determine the range and inverse, including its domain.',points:2},{prompt:'Show that applying f twice returns the original input and check all exclusions.',points:2}],
  tex`Solving $y(x-1)=x+1$ gives $x=(y+1)/(y-1)$, with $y\ne1$. The equation $f(x)=1$ is impossible. Thus the range and inverse domain both exclude 1, and $f^{-1}=f$. Substitution gives $f(f(x))=x$ for every $x\ne1$.`,['Solve for x and exclude y=1.','Verify composition and that the intermediate value never equals 1.'],'Medium'),
 exact(122,1,'A','CALC_SRC_FOUNDATIONS','Composition can lose inputs',tex`Let $f(u)=\sqrt u$ and $g(x)=x^2-4$. How many integer inputs in $[-3,3]$ are in the domain of $f\circ g$ but not $g\circ f$?`,'2',tex`The first composition needs $|x|\ge2$, giving $-3,-2,2,3$. The second needs $x\ge0$. Only $-3,-2$ belong to the first domain but not the second.`),
 written(123,1,'B','CALC_SRC_FOUNDATIONS','A hole is not a vertical asymptote',tex`Consider $r(x)=(x^2-x-2)/(x^2-4)$.`,[
  {prompt:'Locate and classify every discontinuity, giving a continuous extension where possible.',points:3},{prompt:'Find its horizontal asymptote and the one-sided limits at its pole.',points:2}],
  tex`For $x\ne\pm2$, $r(x)=(x+1)/(x+2)$. At 2 there is a hole with limiting value $3/4$. At -2 the numerator tends to -1: the left limit is $+\infty$ and the right limit is $-\infty$. The horizontal asymptote is $y=1$.`,['Keep both original exclusions; fill only the hole at 2.','Check signs near -2 and the limit at infinity.'],'Medium'),
 exact(124,1,'B','CALC_SRC_FOUNDATIONS','Oscillation with controlled magnitude',tex`Find $\lim_{x\to0}(\cos x+x^2\cos(1/x^2))$.`,'1',tex`The oscillatory summand has absolute value at most $x^2$, so it tends to zero. Continuity gives $\cos x\to1$. No limit for the inner cosine is required.`),
 written(125,1,'B','CALC_SRC_FOUNDATIONS','Quantify a nonlinear limit',tex`Prove $\lim_{x\to2}x^2=4$ directly from the epsilon-delta definition.`,[
  {prompt:'First impose a fixed bound on the distance from x to 2 and bound the other factor.',points:2},{prompt:'Give a positive delta for every epsilon and complete the implication.',points:2}],
  tex`Require $|x-2|<1$, giving $1<x<3$ and $|x+2|<5$. For $\varepsilon>0$, choose $\delta=\min(1,\varepsilon/5)$. Then $0<|x-2|<\delta$ implies $|x^2-4|=|x-2||x+2|<5\delta\le\varepsilon$.`,['Bound x+2 using a preliminary neighborhood.','Choose the minimum and prove the strict epsilon inequality.'],'Hard'),
 exact(126,1,'A','CALC_SRC_FOUNDATIONS','Principal inverse after a composition',tex`Evaluate $\cos(\arcsin(3/5))+\sin(\arccos(3/5))$. Enter the result multiplied by 5.`,'8',tex`Both principal angles have nonnegative complementary trigonometric values, each $\sqrt{1-9/25}=4/5$. Their sum is $8/5$, so the requested scaled result is 8.`),
 written(127,1,'B','CALC_SRC_FOUNDATIONS','Continuity does not remove a corner',tex`Let $f(x)=|x-2|$.`,[
  {prompt:'Use one-sided formulas to prove continuity at 2.',points:2},{prompt:'Compute both one-sided difference quotients and decide differentiability.',points:2}],
  tex`On the left $f(x)=2-x$ and on the right $f(x)=x-2$; both approach $f(2)=0$. The quotient $|h|/h$ is -1 for negative h and 1 for positive h, so no derivative exists at 2.`,['Both limits must match the defined value.','Distinguish the function limit from the derivative limit.'],'Medium'),
 exact(128,1,'B','CALC_SRC_FOUNDATIONS','The sign hidden in a square root',tex`Find $\lim_{x\to-\infty}(\sqrt{x^2-6x}+x)$.`,'3',tex`Rationalization gives $-6x/(\sqrt{x^2-6x}-x)$. Since $x<0$, division by $-x$ gives $6/(\sqrt{1-6/x}+1)\to3$.`,'Hard'),

 written(129,2,'A','CALC_SRC_DERIVATIVES','Differentiate a variable base and exponent',tex`Let $f(x)=x^{\sin x}$ for $x>0$.`,[
  {prompt:'Use logarithmic differentiation to derive the derivative.',points:2},{prompt:tex`Find the tangent line at $x=\pi/2$.`,points:2}],
  tex`From $\ln f=\sin x\ln x$, $f'=x^{\sin x}(\cos x\ln x+\sin x/x)$. At $\pi/2$, the value is $\pi/2$ and the slope is 1, so the tangent is $y=x$.`,['Differentiate both the exponent and logarithm.','Use both the point and slope.'],'Medium'),
 exact(130,2,'B','CALC_SRC_DERIVATIVES','An endpoint and a cusp compete',tex`For $f(x)=|x-1|-x/2$ on $[0,4]$, find the value of x where the absolute minimum occurs.`,'1',tex`On $[0,1]$ the slope is $-3/2$; on $[1,4]$ it is $1/2$. Thus the function decreases to the cusp and increases after it. The minimum occurs at 1 even though the derivative does not exist there.`),
 written(131,2,'B','CALC_SRC_DERIVATIVES','Use the mean value theorem as a bound',tex`Let $a>0$ and $h>0$.`,[
  {prompt:tex`Apply the mean value theorem to $\ln x$ on $[a,a+h]$.`,points:2},{prompt:tex`Prove $h/(a+h)<\ln(a+h)-\ln a<h/a$.`,points:2}],
  tex`The logarithm is continuous on the closed interval and differentiable inside it, so the difference is $h/c$ for some $a<c<a+h$. The reciprocal is strictly decreasing on positive numbers, giving $1/(a+h)<1/c<1/a$. Multiply by h.`,['State the hypotheses and intermediate point.','Use positivity to preserve strict inequalities.'],'Hard'),
 exact(132,2,'B','CALC_SRC_DERIVATIVES','A Newton cycle instead of a root',tex`Apply Newton's method to $f(x)=x^3-2x+2$ starting at $x_0=0$. What is $x_2$?`,'0',tex`Since $f(0)=2$ and $f'(0)=-2$, $x_1=1$. Since $f(1)=1$ and $f'(1)=1$, $x_2=0$. Both steps are defined, but iteration cycles instead of converging.`),
 written(133,2,'B','CALC_SRC_DERIVATIVES','A rectangle beneath a parabola',tex`A rectangle above the x-axis has upper corners on $y=12-x^2$ and is symmetric about the y-axis.`,[
  {prompt:'Express its area in terms of its positive half-width and give the feasible interval.',points:2},{prompt:'Find the dimensions giving largest area, checking endpoints.',points:3}],
  tex`For half-width $0\le x\le\sqrt{12}$, $A(x)=2x(12-x^2)$. Its derivative is $24-6x^2$, so the interior candidate is x=2. Endpoints have area zero; x=2 gives width 4, height 8 and maximum area 32.`,['Width is twice x and height must be nonnegative.','Solve the derivative equation and compare all candidates.']),
 exact(134,2,'A','CALC_SRC_DERIVATIVES','Read the slope of an inverse',tex`A differentiable one-to-one function satisfies $f(2)=5$ and $f'(2)=1/3$. Its inverse is differentiable at 5. Find $(f^{-1})'(5)$.`,'3',tex`Differentiating $f(f^{-1}(y))=y$ gives $f'(f^{-1}(y))(f^{-1})'(y)=1$. At y=5 the derivative is the reciprocal of $f'(2)$, namely 3.`),
 written(135,2,'A','CALC_SRC_DERIVATIVES','A linear estimate with a certified error',tex`Approximate $\sqrt{4.1}$ using the tangent at x=4.`,[
  {prompt:'Find the approximation and decide the direction of the error.',points:2},{prompt:tex`Use $|f''(x)|\le1/32$ on $[4,4.1]$ to bound the absolute error.`,points:2}],
  tex`The approximation is $2+(0.1)/4=2.025$. Since $f''(x)=-1/(4x^{3/2})<0$, it overestimates. Taylor's first-order remainder is bounded by $(1/32)(0.1)^2/2=1/6400$.`,['Compute the tangent and use concavity.','Include the factor 1/2 in the remainder.'],'Hard'),
 exact(136,2,'B','CALC_SRC_DERIVATIVES','Resolve two orders of cancellation',tex`Find $\lim_{x\to0}(e^{2x}-1-2x)/x^2$.`,'2',tex`Both numerator and denominator tend to zero. Applying l'Hospital twice gives the limit of $4e^{2x}/2$, equal to 2; the intermediate denominator derivative is nonzero away from zero.`,'Hard'),

 written(137,3,'A','CALC_SRC_INTEGRALS','Change of variable with two branches',tex`Consider $I=\int_{-1}^{1}x^2\,dx$. A student substitutes $u=x^2$ and concludes I=0 because both endpoint values of u are 1.`,[
  {prompt:'Explain why that transformed integral is not valid.',points:2},{prompt:'Split at zero, perform valid substitutions, and evaluate I.',points:2}],
  tex`The substitution is not one-to-one across zero and $x=\pm\sqrt u$ uses different branches. On [-1,0], $x^2dx=-\sqrt u\,du/2$ with bounds 1 to 0. On [0,1] it is $\sqrt u\,du/2$ with bounds 0 to 1. Each contribution is 1/3, so I=2/3.`,['Identify the branch/sign issue, not a failure of integration itself.','Keep orientation and both branch contributions.'],'Hard'),
 exact(138,3,'A','CALC_SRC_INTEGRALS','Differentiate an accumulation twice',tex`Let $F(x)=\int_0^{x^2}\sin t\,dt$. Find $F''(0)$.`,'0',tex`The fundamental theorem and chain rule give $F'=2x\sin(x^2)$ and $F''=2\sin(x^2)+4x^2\cos(x^2)$. Both terms vanish at zero.`),
 written(139,3,'B','CALC_SRC_INTEGRALS','Parts returns the original integral',tex`Find an antiderivative of $e^x\cos x$.`,[
  {prompt:'Integrate by parts twice and write the resulting equation for the original integral.',points:3},{prompt:'Solve that equation and verify by differentiating.',points:2}],
  tex`Writing $I=\int e^x\cos x\,dx$ and $J=\int e^x\sin x\,dx$ gives $I=e^x\cos x+J$ and $J=e^x\sin x-I$, up to constants. Thus $I=e^x(\sin x+\cos x)/2+C$. Its derivative is $e^x\cos x$.`,['Track the signs across both integrations by parts.','Collect two copies of I and differentiate the result.']),
 exact(140,3,'A','CALC_SRC_INTEGRALS','Recover an integral after translation',tex`A continuous function f satisfies $\int_0^2 f(u)\,du=7$. Evaluate $\int_1^2 2f(2x-2)\,dx$.`,'7',tex`Set u=2x-2 and du=2dx. The endpoints become 0 and 2, so the transformed integral is exactly the given integral.`),
 written(141,3,'A','CALC_SRC_INTEGRALS','Signed displacement and total travel',tex`A particle has velocity $v(t)=t^2-4t+3$ for $0\le t\le4$.`,[
  {prompt:'Find its displacement over the whole interval.',points:2},{prompt:'Find the total distance travelled, explaining the split points.',points:3}],
  tex`An antiderivative is $V(t)=t^3/3-2t^2+3t$. Values at 0,1,3,4 are 0,4/3,0,4/3. Velocity is positive on (0,1) and (3,4), negative on (1,3). Displacement is 4/3, but distance is $4/3+4/3+4/3=4$.`,['Integrate velocity for displacement.','Split at both sign changes and sum absolute contributions.']),
 exact(142,3,'B','CALC_SRC_INTEGRALS','Boundary data in integration by parts',tex`A continuously differentiable function f has $f(2)=5$ and $\int_0^2 f(x)\,dx=3$. Evaluate $\int_0^2 x f'(x)\,dx$.`,'7',tex`Parts gives $[xf(x)]_0^2-\int_0^2 f(x)\,dx=10-3=7$. The boundary at zero vanishes without knowing f(0).`),
 written(143,3,'A','CALC_SRC_INTEGRALS','A symmetry that is not oddness',tex`Evaluate $I=\int_0^\pi \frac{x\sin x}{1+\cos^2x}\,dx$.`,[
  {prompt:'Use the substitution u=pi-x to obtain a second expression for I, then add them.',points:3},{prompt:'Evaluate the remaining integral exactly.',points:2}],
  tex`Reflection leaves $\sin x/(1+\cos^2x)$ unchanged and replaces x by $\pi-x$. Thus $2I=\pi\int_0^\pi\sin x/(1+\cos^2x)\,dx$. Substitution u=cos x yields $\int_{-1}^1du/(1+u^2)=\pi/2$. Hence $I=\pi^2/4$.`,['Reflect the full integrand and retain the bounds.','Use the arctangent integral and divide by two.']),
 exact(144,3,'A','CALC_SRC_INTEGRALS','Read the width in a Riemann sum',tex`Evaluate $\lim_{n\to\infty}\frac2n\sum_{k=1}^n(1+2k/n)$.`,'4',tex`This is the right-endpoint sum for $\int_1^3 x\,dx=4$. The width is 2/n and the sampled coordinate is 1+2k/n; using [0,1] without transforming would lose the scale.`),

 written(145,4,'A','CALC_SRC_LIMIT_PROCESSES','Two different improper endpoints',tex`For real p, consider $\int_0^\infty x^{-p}/(1+x)\,dx$.`,[
  {prompt:'Determine convergence near zero by limit comparison.',points:2},{prompt:'Determine convergence at infinity and combine the conditions.',points:2}],
  tex`Near zero the ratio to $x^{-p}$ tends to 1, giving p<1. At infinity the ratio to $x^{-p-1}$ tends to 1, giving p>0. Both independent pieces converge exactly when $0<p<1$; each endpoint p=0 or p=1 has a logarithmic divergence.`,['Compare with the correct local power at zero.','Use the different tail power and exclude both endpoints.']),
 exact(146,4,'A','CALC_SRC_LIMIT_PROCESSES','An integrable logarithmic singularity',tex`Evaluate $\int_0^1-\ln x\,dx$.`,'1',tex`From epsilon to 1 the integral is $1+\varepsilon\ln\varepsilon-\varepsilon$. Since $\varepsilon\ln\varepsilon\to0$, the improper limit is 1. The unbounded integrand still has finite integral.`),
 written(147,4,'A','CALC_SRC_LIMIT_PROCESSES','Symmetric truncation is not convergence',tex`Consider $\int_{-1}^1 x^{-3}\,dx$.`,[
  {prompt:'Compute its symmetric truncated integral with a gap of radius epsilon.',points:2},{prompt:'Test the two halves separately and explain the distinction.',points:2}],
  tex`Odd symmetry makes every symmetric truncation zero. But $\int_\varepsilon^1x^{-3}dx=1/(2\varepsilon^2)-1/2\to+\infty$, and the left half tends to $-\infty$. The ordinary improper integral diverges; only its Cauchy principal value is zero.`,['Evaluate or justify cancellation for matching cutoffs.','Do not add opposing infinities; require both halves finite.'],'Medium'),
 exact(148,4,'B','CALC_SRC_LIMIT_PROCESSES','A sequence hides a derivative',tex`Find $\lim_{n\to\infty}n\ln(1+2/n)$.`,'2',tex`Set h=1/n. The expression is $\ln(1+2h)/h$, tending to the derivative at zero of $\ln(1+2h)$, namely 2.`),
 written(149,4,'B','CALC_SRC_LIMIT_PROCESSES','An alternating error that shrinks',tex`Let $a_0=0$ and $a_{n+1}=3-a_n/2$.`,[
  {prompt:'Find the fixed point and an explicit expression for the error.',points:2},{prompt:'Prove convergence and explain why monotonicity is unnecessary here.',points:2}],
  tex`The fixed point is 2. Subtracting it gives $a_{n+1}-2=-(a_n-2)/2$, hence $a_n-2=-2(-1/2)^n$. Its absolute value is $2^{1-n}\to0$. The sequence alternates about 2, so it is not monotone, yet the explicit error proves convergence.`,['Derive the error recurrence and initial coefficient.','Use absolute error tending to zero rather than the fixed point alone.'],'Hard'),
 exact(150,4,'A','CALC_SRC_LIMIT_PROCESSES','Choose an improper tail cutoff',tex`Find the smallest positive integer R for which $\int_R^\infty 6/x^3\,dx\le1/12$.`,'6',tex`The tail equals $3/R^2$. The inequality is $R^2\ge36$, so the smallest positive integer is 6; equality is allowed.`),
 written(151,4,'B','CALC_SRC_LIMIT_PROCESSES','A nonlinear recurrence with a useful reciprocal',tex`Let $a_0=1$ and $a_{n+1}=a_n/(1+a_n)$.`,[
  {prompt:'Prove positivity and derive a recurrence for the reciprocals.',points:2},{prompt:'Obtain a closed form and use it to prove convergence.',points:2}],
  tex`Positivity follows by induction. Taking reciprocals gives $1/a_{n+1}=1/a_n+1$, so $1/a_n=n+1$ and $a_n=1/(n+1)\to0$. This also shows strict decrease without assuming convergence first.`,['Justify taking reciprocals using positivity.','Solve the transformed recurrence with its initial condition.'],'Hard'),
 exact(152,4,'B','CALC_SRC_LIMIT_PROCESSES','Vanishing oscillations need not be monotone',tex`Find $\lim_{n\to\infty}(3+(-1)^n/\sqrt n)$ for $n\ge1$.`,'3',tex`The distance from 3 is exactly $1/\sqrt n$, which tends to zero. Even and odd subsequences approach the same limit from opposite sides.`),

 written(153,5,'B','CALC_SRC_SERIES','Exponential growth competes with a factorial',tex`Classify $\sum_{n=1}^\infty n!/n^n$.`,[
  {prompt:'Simplify the ratio of consecutive positive terms.',points:2},{prompt:'Find its limit and state the resulting convergence conclusion.',points:2}],
  tex`The ratio is $(n/(n+1))^n=(1+1/n)^{-n}\to e^{-1}<1$. The ratio test therefore proves convergence. A factorial in the numerator alone does not imply divergence.`,['Cancel the factorial and powers accurately.','Recognize the exponential limit and apply the ratio test.'],'Hard'),
 exact(154,5,'A','CALC_SRC_SERIES','A telescope with a gap of two',tex`Evaluate $\sum_{n=1}^\infty 4/(n(n+2))$.`,'3',tex`The term is $2(1/n-1/(n+2))$. The partial sum is $3-2/(N+1)-2/(N+2)$, which tends to 3. Two initial and two terminal terms survive.`),
 written(155,5,'B','CALC_SRC_SERIES','Compare both convergence and error',tex`Let $S=\sum_{n=1}^\infty1/n^3$ and let $S_N$ be its first N terms.`,[
  {prompt:'Prove convergence and bound the remainder above and below using integrals.',points:3},{prompt:'Find a sufficient integer N for error at most 1/200.',points:1}],
  tex`The function $x^{-3}$ is positive, continuous and decreasing. Integral comparison gives $1/(2(N+1)^2)\le S-S_N\le1/(2N^2)$. Thus N=10 is sufficient for error at most 1/200; this bound does not assert that ten is the true smallest possible N.`,['Use integrals from N+1 and N in the correct order.','Distinguish sufficient certification from the exact smallest truncation.'],'Hard'),
 exact(156,5,'A','CALC_SRC_SERIES','Separate two geometric tails',tex`Evaluate $\sum_{n=0}^\infty(2/3^n-1/2^n)$.`,'1',tex`Both series converge absolutely. Their sums are $2/(1-1/3)=3$ and $1/(1-1/2)=2$, so the difference is 1.`),
 written(157,5,'B','CALC_SRC_SERIES','Alternating signs cannot fix nonzero terms',tex`A student claims $\sum_{n=1}^\infty(-1)^n n/(n+1)$ converges by the alternating-series test.`,[
  {prompt:'Identify the failed hypothesis and determine convergence.',points:2},{prompt:'Explain why small changes between successive magnitudes are irrelevant to that hypothesis.',points:2}],
  tex`The magnitudes $n/(n+1)$ tend to 1, not zero; the signed terms oscillate near -1 and 1. The necessary term test fails, so the series diverges. Differences of magnitudes tend to zero, but that does not imply that the magnitudes themselves tend to zero.`,['Apply the term test to the actual terms.','Distinguish successive differences from the required zero limit.'],'Medium'),
 exact(158,5,'B','CALC_SRC_SERIES','Certify an alternating geometric tail',tex`For $\sum_{n=0}^\infty(-1)^n/3^n$, retain the first N terms (indices 0 through N-1). What smallest N does the alternating-series bound certify for error at most 1/1000?`,'7',tex`The first omitted magnitude is $3^{-N}$. Since $3^6=729<1000$ and $3^7=2187>1000$, N=7 is the first certified value. The question asks about this bound, not the sharper exact geometric error.`),
 written(159,5,'B','CALC_SRC_SERIES','Logarithms change the harmonic boundary',tex`For real p, classify $\sum_{n=2}^\infty1/(n(\ln n)^p)$.`,[
  {prompt:'Verify the integral test applies eventually, even when p is negative.',points:2},{prompt:'Use a substitution to find the full convergence range.',points:2}],
  tex`The terms are positive. The derivative of $1/(x(\ln x)^p)$ is $-(\ln x+p)/(x^2(\ln x)^{p+1})$, negative for sufficiently large x. Substitution u=ln x transforms the tail integral into $\int u^{-p}\,du$, which converges at infinity exactly for p>1. Finite initial segments do not change convergence.`,['Establish eventual rather than necessarily immediate decrease.','Apply the p-integral criterion to the logarithmic variable.']),
 exact(160,5,'A','CALC_SRC_SERIES','Recover a sum from its partial sums',tex`A series beginning at n=1 has partial sums $S_N=4-3/(N+1)$ for all $N\ge1$. What is its infinite sum?`,'4',tex`Convergence is defined by the limit of partial sums. Here $S_N\to4$. The formula determines $a_1=S_1=5/2$; it must not be extended to a fictitious nonzero S_0 when recovering individual terms.`),

 written(161,6,'A','CALC_SRC_TAYLOR','Differentiation changes endpoint behavior',tex`Consider $F(x)=\sum_{n=1}^\infty x^n/n^2$.`,[
  {prompt:'Find the full convergence interval of F.',points:2},{prompt:'Find the full convergence interval of its termwise derivative series.',points:3}],
  tex`Both series have radius 1. F converges absolutely at both endpoints by the p-series with p=2, so its interval is [-1,1]. The derivative is $\sum x^{n-1}/n$: at 1 it is harmonic and divergent, while at -1 it is alternating harmonic and convergent. Its interval is [-1,1). Termwise differentiation is justified inside the radius.`,['Test both original endpoints separately.','Test the differentiated endpoints without assuming preservation.']),
 exact(162,6,'B','CALC_SRC_TAYLOR','A removable quotient records a derivative',tex`Define $g(x)=\sin x/x$ for nonzero x and $g(0)=1$. Find $5g^{(4)}(0)$.`,'1',tex`The series is $1-x^2/6+x^4/120-\cdots$, so $g^{(4)}(0)=4!/120=1/5$. Multiplying by 5 gives 1.`),
 written(163,6,'B','CALC_SRC_TAYLOR','Taylor approximation away from zero',tex`Approximate $1/x$ near x=2.`,[
  {prompt:'Find its degree-three Taylor polynomial centered at 2.',points:2},{prompt:'Prove the approximation error is at most 1/32 whenever the distance to 2 is at most 1/2.',points:3}],
  tex`Writing h=x-2 gives $P=1/2-h/4+h^2/8-h^3/16$. The finite geometric identity gives the exact error $h^4/(16(2+h))$. If $|h|\le1/2$, its magnitude is at most $(1/16)/(16\cdot3/2)=1/384<1/32$. This sharper bound proves the requested one.`,['Use powers of x-2 with the correct signs.','Keep a positive lower bound on the denominator in the exact remainder.'],'Hard'),
 exact(164,6,'B','CALC_SRC_TAYLOR','An odd coefficient vanishes structurally',tex`For $f(x)=e^{x^2}\cos x$, find $f^{(7)}(0)$.`,'0',tex`Both factors are even analytic functions, so their product has only even powers in its Maclaurin series. Every odd derivative at zero, including the seventh, is zero.`),
 written(165,6,'A','CALC_SRC_TAYLOR','Integrate a rational series with missing powers',tex`Let $F(x)=\int_0^x1/(1+t^3)\,dt$.`,[
  {prompt:'Derive its power series for the absolute value of x less than 1.',points:2},{prompt:'Test convergence of the series at each endpoint. Also decide whether the defining integral is finite there; no endpoint sum evaluation is required.',points:3}],
  tex`Geometric expansion and integration give $F(x)=\sum_{n=0}^\infty(-1)^n x^{3n+1}/(3n+1)$ for $|x|<1$. At 1 the series converges by alternation and the integral is finite because the integrand is continuous on [0,1]. At -1 every series term is $-1/(3n+1)$, so it diverges to negative infinity. The integral also diverges there: $1+t^3=(t+1)(t^2-t+1)$ has a simple zero at -1, and integration from 0 toward -1 reverses orientation.`,['Integrate powers and retain the lower-bound constant.','Test the series and integral endpoints separately, keeping the negative orientation.']),
 exact(166,6,'B','CALC_SRC_TAYLOR','Scale a cancellation limit to an integer',tex`Evaluate $24\lim_{x\to0}(\cos x-1+x^2/2)/x^4$.`,'1',tex`The cosine expansion leaves $x^4/24+O(x^6)$ in the numerator. Division and multiplication by 24 give 1.`),
 written(167,6,'B','CALC_SRC_TAYLOR','A Taylor polynomial is not automatically a lower bound',tex`Use $P_2(x)=1+x+x^2/2$ to approximate $e^x$ on $[-1/2,1/2]$.`,[
  {prompt:'Determine on which side of zero P2 underestimates and on which it overestimates.',points:2},{prompt:'Give a single absolute-error bound valid throughout the interval.',points:2}],
  tex`Taylor's theorem gives $e^x-P_2(x)=e^\xi x^3/6$, with xi between 0 and x. This is positive for x>0 and negative for x<0, and zero at 0. Since $e^\xi\le e^{1/2}$, the absolute error is at most $e^{1/2}/48$.`,['Use the sign of the remainder, not only positivity of the exponential.','Bound both the derivative factor and the cubic distance.'],'Hard'),
 exact(168,6,'A','CALC_SRC_TAYLOR','Find a radius with sparse powers',tex`Find the radius of convergence about zero of $\sum_{n=1}^\infty x^{2n}/(n4^n)$.`,'2',tex`The ratio of successive magnitudes tends to $|x|^2/4$. Absolute convergence requires $|x|<2$, so the radius is 2, not 4. At either endpoint the series becomes harmonic and diverges.`),

 written(169,7,'A','CALC_SRC_PARTIALS','Intersect a surface domain with a deleted curve',tex`Let $f(x,y)=\sqrt{y-x^2}/\ln(x+y)$.`,[
  {prompt:'Describe the real domain using simultaneous inequalities and exclusions.',points:3},{prompt:'Decide whether (0,0), (0,1) and (0,2) belong.',points:1}],
  tex`The domain requires $y\ge x^2$, $x+y>0$, and $x+y\ne1$. The square-root boundary may be included when the logarithmic restrictions hold. (0,0) fails positivity; (0,1) makes the denominator zero; (0,2) is allowed.`,['Include the logarithm domain and its nonzero requirement separately.','Check all conditions at each supplied point.'],'Medium'),
 exact(170,7,'B','CALC_SRC_PARTIALS','A tangent plane predicts a distant input',tex`For $f(x,y)=e^{x-y}$, let L be its linearization at (0,0). Find $L(2,1)$, as a plane value rather than a claim of accurate approximation.`,'2',tex`At the origin f=1, $f_x=1$ and $f_y=-1$. Thus $L=1+x-y$ and $L(2,1)=2$. The actual value is e; linearization is not an exact substitution into f.`),
 written(171,7,'A','CALC_SRC_PARTIALS','All straight paths can miss a bad curve',tex`Define $f(x,y)=x^2y/(x^4+y^2)$ away from the origin and f(0,0)=0.`,[
  {prompt:'Show that the limit along every straight line through the origin is zero.',points:3},{prompt:'Find a curved path proving that the full limit does not exist.',points:2}],
  tex`For y=mx with m nonzero, the expression is $mx/(x^2+m^2)\to0$. On y=0 and on the vertical line x=0 it is identically zero. Along $y=x^2$ it is 1/2 away from zero. All straight-line limits therefore agree, yet no full limit exists.`,['Treat zero slope and the vertical line as well as nonzero slopes.','Use the parabolic path and compare with an axis.']),
 exact(172,7,'A','CALC_SRC_PARTIALS','A perpendicularity parameter',tex`Find the real value k making vectors $(1,k,2)$ and $(k,3,-2)$ perpendicular.`,'1',tex`Their dot product is $k+3k-4=4k-4$. It vanishes exactly when k=1. Both vectors are nonzero, so the dot-product criterion applies.`),
 written(173,7,'B','CALC_SRC_PARTIALS','Separate exact change from linear change',tex`Let $f(x,y)=x^2y$, based at (1,2), with increments h and k.`,[
  {prompt:'Expand the exact change and identify its linear part.',points:2},{prompt:'Prove that the remaining terms divided by the increment length tend to zero.',points:3}],
  tex`The exact change is $4h+k+2h^2+2hk+h^2k$. The linear part is $4h+k$. With $r=\sqrt{h^2+k^2}$, the remainder magnitude is at most $4r^2+r^3$, whose quotient by r tends to zero. Thus the plane is a differentiable approximation, not an exact formula.`,['Retain all quadratic and cubic terms in the expansion.','Use a bound uniform over all directions.'],'Hard'),
 exact(174,7,'B','CALC_SRC_PARTIALS','A second partial with a logarithmic coupling',tex`For $f(x,y)=\ln(1+xy)$, find $f_{xx}(1,1)$. Enter four times this value.`,'-1',tex`The first partial is $y/(1+xy)$, and the second is $-y^2/(1+xy)^2$. At (1,1) it equals -1/4, so four times the value is -1.`),
 written(175,7,'A','CALC_SRC_PARTIALS','An isolated level and nearby ellipses',tex`Consider $f(x,y)=(x-1)^2+4(y+2)^2$.`,[
  {prompt:'Describe the level sets for c negative, zero and positive.',points:3},{prompt:'Find the center and semiaxis lengths when c=4.',points:1}],
  tex`No points have negative values. The zero level consists only of (1,-2). Positive levels are ellipses centered there, with semiaxes $\sqrt c$ horizontally and $\sqrt c/2$ vertically. At c=4 these lengths are 2 and 1.`,['Distinguish an empty set, a point and a curve.','Use semiaxes rather than full axis lengths.'],'Medium'),
 exact(176,7,'B','CALC_SRC_PARTIALS','Hold the independent coordinate fixed',tex`Let $f(x,y)=x\sin y+y\cos x$. Find $f_y(0,0)$.`,'1',tex`Holding x fixed gives $f_y=x\cos y+\cos x$, which is 1 at the origin. No derivative of x with respect to y belongs in this partial.`),

 written(177,8,'A','CALC_SRC_GRADIENT','Velocity and unit direction give different rates',tex`At a point, $\nabla f=(3,4)$. A path passes through that point with velocity (6,8).`,[
  {prompt:'Find the rate of change along the path and the directional derivative in its direction.',points:2},{prompt:'Explain the factor between these two rates.',points:2}],
  tex`The path rate is $(3,4)\cdot(6,8)=50$. The speed is 10 and the unit direction is (3/5,4/5), giving directional derivative 5. The path rate is speed times change per unit distance.`,['Normalize only for the unit directional derivative.','Identify the speed as the scale factor.'],'Medium'),
 exact(178,8,'B','CALC_SRC_GRADIENT','Count all stationary points',tex`How many stationary points does $f(x,y)=x^3-3x+y^2$ have on the plane?`,'2',tex`The gradient equations are $3x^2-3=0$ and 2y=0, giving (1,0) and (-1,0). There are exactly two. The first is a minimum and the second a saddle.`),
 written(179,8,'B','CALC_SRC_GRADIENT','A parameter changes the type of a critical point',tex`Let $f_a(x,y)=x^2+2axy+y^2$ for real a.`,[
  {prompt:'Classify the origin when the absolute value of a is less than 1 or greater than 1.',points:2},{prompt:'Resolve the two boundary cases where the Hessian test is inconclusive.',points:3}],
  tex`The Hessian determinant is $4(1-a^2)$. For $|a|<1$ the origin is a strict global minimum; for $|a|>1$ it is a saddle. At a=1, $f=(x+y)^2$, and at a=-1, $f=(x-y)^2$. Each has a non-strict global minimum along an entire line, including the origin.`,['Apply the determinant and positive xx partial correctly.','Factor in the degenerate cases and distinguish strict from non-strict.']),
 exact(180,8,'A','CALC_SRC_GRADIENT','Follow a level curve',tex`A differentiable path stays on $x^2+2y^2=9$. At a time when (x,y)=(1,2) and $x'=4$, find $y'$.`,'-1',tex`Differentiating the constant level gives $2xx'+4yy'=0$. At the point this is $8+8y'=0$, so y'=-1.`),
 written(181,8,'B','CALC_SRC_GRADIENT','Global extrema without an interior critical point',tex`Find absolute extrema of $f(x,y)=xy$ on $1\le x\le3$, $1\le y\le2$.`,[
  {prompt:'Explain why the interior stationary equations provide no candidate.',points:1},{prompt:'Inspect the boundary and give every extremizing point and value.',points:3}],
  tex`The gradient is (y,x), which cannot vanish in the rectangle. Both partials are positive throughout, so on each horizontal or vertical edge the function increases in the varying coordinate. Comparing corners gives unique minimum 1 at (1,1) and unique maximum 6 at (3,2).`,['Check the domain when solving for a zero gradient.','Use boundary monotonicity and identify values and locations.'],'Medium'),
 exact(182,8,'A','CALC_SRC_GRADIENT','Second-order change at a stationary point',tex`Let $f(x,y)=x^2+3y^2$ and a differentiable path be $x=t$, $y=t^2$. Find the second derivative of the composed function at t=0.`,'2',tex`Along the path the function is $t^2+3t^4$, with second derivative $2+36t^2$. It equals 2 at zero even though the first derivative vanishes there.`),
 written(183,8,'B','CALC_SRC_GRADIENT','A curved boundary with non-corner extrema',tex`Find the absolute extrema of $f(x,y)=xy$ on $x^2+y^2\le2$.`,[
  {prompt:'Find interior stationary candidates.',points:1},{prompt:'Use a boundary parameterization or square inequalities to find all extrema.',points:3}],
  tex`The sole interior stationary point is (0,0), with value 0. Since $2|xy|\le x^2+y^2\le2$, values lie in [-1,1]. Equality requires $|x|=|y|=1$. Maximum 1 occurs at (1,1),(-1,-1); minimum -1 occurs at (1,-1),(-1,1).`,['Solve both gradient equations.','Prove the bounds and check every equality case.']),
 exact(184,8,'A','CALC_SRC_GRADIENT','Determine a gradient from two directions',tex`At a point, the unit-direction derivatives in directions $(1,0)$ and $(0,1)$ are -5 and 12. What is the largest unit-direction derivative there? Assume f is differentiable.`,'13',tex`The gradient is (-5,12). Its norm is $\sqrt{25+144}=13$, the maximum dot product with a unit vector.`),

 written(185,9,'A','CALC_SRC_COMPLEX','Conjugation in a linear equation',tex`Solve $z+2\overline z=3-4i$.`,[
  {prompt:'Write real equations using z=x+iy and solve them.',points:2},{prompt:'Verify the solution and explain why this is not the same as 3z=3-4i.',points:2}],
  tex`The left side is $3x-iy$, so x=1 and y=4. Thus z=1+4i and its conjugate is 1-4i; their indicated combination is 3-4i. Conjugation reverses the imaginary part, so it cannot be replaced by z.`,['Separate real and imaginary coefficients.','Substitute the complex value and its conjugate.'],'Medium'),
 exact(186,9,'A','CALC_SRC_COMPLEX','Modulus of a quotient without full expansion',tex`For $z=(3+4i)/(1-2i)$, find $|z|^2$.`,'5',tex`The squared modulus is $|3+4i|^2/|1-2i|^2=25/5=5$. The denominator is nonzero.`),
 written(187,9,'B','CALC_SRC_COMPLEX','A translated root polygon',tex`Solve $(z-1)^3=8$.`,[
  {prompt:'Find all solutions in Cartesian form.',points:3},{prompt:'Describe their circle and verify their sum.',points:2}],
  tex`The cube roots of 8 are $2,-1+i\sqrt3,-1-i\sqrt3$. Adding 1 gives $3,i\sqrt3,-i\sqrt3$. They lie on the circle centered at 1 with radius 2. Their sum is 3, consistent with the coefficient of $z^2$ in $(z-1)^3-8$.`,['Apply the translation after finding every root.','Use distances from 1, not from the origin.']),
 exact(188,9,'B','CALC_SRC_COMPLEX','Multiplicity does not change the set of roots',tex`How many distinct roots does $(z^2+1)^3(z-1)^2$ have over the complex numbers?`,'3',tex`The roots are i,-i,1, with multiplicities 3,3,2. Thus there are three distinct roots although the degree and total multiplicity are eight.`),
 written(189,9,'A','CALC_SRC_COMPLEX','A purely imaginary quotient on the unit circle',tex`Let $|z|=1$ with $z\ne1$.`,[
  {prompt:tex`Use $\overline z=1/z$ to prove $(1+z)/(1-z)$ is purely imaginary.`,points:3},{prompt:'Evaluate it at z=i as a check.',points:1}],
  tex`For $w=(1+z)/(1-z)$, conjugation gives $\overline w=(1+1/z)/(1-1/z)=(z+1)/(z-1)=-w$. Thus its real part is zero. At z=i it equals i after multiplying numerator and denominator by 1+i.`,['Use z nonzero and preserve the sign in the denominator.','Explain why conjugate w=-w means real part zero.'],'Hard'),
 exact(190,9,'B','CALC_SRC_COMPLEX','Count roots on a specified half-plane',tex`How many roots of $z^8=1$ have strictly positive imaginary part?`,'3',tex`Arguments are $k\pi/4$ for k=0,...,7. Strictly positive imaginary part selects k=1,2,3. The real roots for k=0 and k=4 are excluded.`),
 written(191,9,'B','CALC_SRC_COMPLEX','Recover a real polynomial from one complex root',tex`A monic cubic with real coefficients has roots $2+i$ and $-1$.`,[
  {prompt:'Determine the third root and the complete polynomial.',points:3},{prompt:'Verify the constant term from the root product.',points:1}],
  tex`The conjugate root 2-i is required. Multiplying gives $[(z-2)^2+1](z+1)=(z^2-4z+5)(z+1)=z^3-3z^2+z+5$. The root product is $5(-1)=-5$, so the constant term of the monic cubic is 5.`,['Use conjugate pairing and expand without dropping cross terms.','Apply the odd-degree sign to the root product.'],'Medium'),
 exact(192,9,'A','CALC_SRC_COMPLEX','Extract a coordinate from a rotated number',tex`Find the imaginary part of $e^{i\pi/2}(2-3i)$.`,'2',tex`The exponential is i, so multiplication gives $2i-3i^2=3+2i$. The imaginary part is the real coefficient 2, not 2i.`),

 written(193,10,'B','CALC_SRC_DOUBLE','Reverse a region that needs three slices',tex`Let $D=\{(x,y):0\le x\le2,\ x\le y\le x+1\}$.`,[
  {prompt:'Express a double integral over D with y outermost, splitting where necessary.',points:3},{prompt:'Use the reversed bounds to verify its area.',points:2}],
  tex`The y range is [0,3]. For $0\le y\le1$, $0\le x\le y$; for $1\le y\le2$, $y-1\le x\le y$; for $2\le y\le3$, $y-1\le x\le2$. Width integrals give $1/2+1+1/2=2$.`,['Find both changes of slice and give three integrals.','Integrate the slice widths to recover area 2.']),
 exact(194,10,'A','CALC_SRC_DOUBLE','Separate an odd part from a surviving part',tex`Evaluate $\iint_{[-1,1]\times[0,2]}(x^3y+3y^2)\,dA$.`,'16',tex`The x-odd term integrates to zero for every y. The remaining term gives $2\int_0^2 3y^2dy=16$. Symmetry removes only the odd part, not the entire integrand.`),
 written(195,10,'B','CALC_SRC_DOUBLE','A product integrand on a non-product region',tex`Evaluate $\iint_D xy\,dA$ for $D=\{0\le y\le x\le1\}$.`,[
  {prompt:'Explain why multiplying the two integrals from zero to one is invalid.',points:1},{prompt:'Evaluate using each integration order and compare.',points:3}],
  tex`The triangular region is not a Cartesian product. Integrating y first gives $\int_0^1 x(x^2/2)dx=1/8$. Reversing gives $\int_0^1 y(1-y^2)/2\,dy=1/8$. The product of separate integrals would be 1/4, covering the whole square instead.`,['Identify the geometric failure of separability.','Use correct variable bounds in both orders.'],'Medium'),
 exact(196,10,'A','CALC_SRC_DOUBLE','Normalize a nonuniform density',tex`A nonnegative density $\rho(x,y)=c(x+y)$ on the unit square must have total mass 1. Find c.`,'1',tex`The integral of x+y over the unit square is $1/2+1/2=1$. Hence the total mass is c, and c=1 meets both normalization and nonnegativity.`),
 written(197,10,'B','CALC_SRC_DOUBLE','An average on a triangular domain',tex`Let $D=\{x\ge0,y\ge0,x+y\le1\}$ and $f(x,y)=x^2$.`,[
  {prompt:'Compute the integral of f and the area of D.',points:2},{prompt:'Find the average value and explain why the value at the centroid need not equal it.',points:2}],
  tex`The integral is $\int_0^1x^2(1-x)dx=1/12$ and the area is 1/2, so the average is 1/6. The centroid has x=1/3 and f=1/9, different because this function is quadratic rather than affine.`,['Use the shrinking slice width and divide by area.','Compare the two actual values without assuming midpoint exactness.'],'Hard'),
 exact(198,10,'B','CALC_SRC_DOUBLE','Area with crossing boundary curves',tex`Find six times the area enclosed by $y=x^2$ and $y=2x$.`,'8',tex`Intersections satisfy $x^2=2x$, giving x=0 and x=2. On that interval the upper curve is 2x, so area is $\int_0^2(2x-x^2)dx=4/3$. Six times the area is 8.`),
 written(199,10,'B','CALC_SRC_DOUBLE','Order reversal exposes a substitution',tex`Evaluate $I=\int_0^1\int_{\sqrt y}^1\cos(x^3)\,dx\,dy$.`,[
  {prompt:'Describe the region with x outermost.',points:2},{prompt:'Evaluate the resulting integral exactly.',points:2}],
  tex`The region is $0\le x\le1$, $0\le y\le x^2$. Reversing gives $I=\int_0^1x^2\cos(x^3)dx$. Set u=x^3, du=3x^2dx, obtaining $I=\sin(1)/3$.`,['Square the boundary inequality only on the nonnegative domain.','Retain the factor 1/3 from substitution.']),
 exact(200,10,'A','CALC_SRC_DOUBLE','Find a missing constant from an average',tex`On $[0,2]\times[0,3]$, the average of $f(x,y)=2x+y+c$ is $13/2$. Find c.`,'3',tex`The coordinate averages are 1 and 3/2, so the function average is $2+3/2+c=7/2+c$. Equating it to 13/2 yields c=3. Equivalently integrate and divide by the area 6.`),
];

export const calculusExamSets=[
 {id:'foundations',title:'Mini exam 1: limits and change',minutes:25,difficulty:'Standard',ids:['CALC_E101','CALC_E104','CALC_E105']},
 {id:'infinite-processes',title:'Mini exam 2: infinite processes and roots',minutes:35,difficulty:'Challenging',ids:['CALC_E107','CALC_E110','CALC_E111','CALC_E117']},
 {id:'several-variables',title:'Mini exam 3: several variables',minutes:25,difficulty:'Challenging',ids:['CALC_E113','CALC_E116','CALC_E119']},
 {id:'mixed-revision',title:'Mixed revision exam: the full syllabus',minutes:60,difficulty:'Mixed',ids:['CALC_E102','CALC_E103','CALC_E106','CALC_E108','CALC_E109','CALC_E112','CALC_E114','CALC_E115','CALC_E118','CALC_E120']},
];
export const calculusQuestion=(id:string)=>calculusAdditions.find(entry=>entry.item.id===id);
