import {IndexedStudentRepository} from '../../src/learning/repository';
import {emptyBackup,parseBackup,CONTENT,type LoadedState} from '../../src/learning/contracts';
import {startSession} from '../../src/exams/engine';
import co from '../../src/exams/banks/co.json';
import type {ExamBank} from '../../src/exams/types';
const bank=co as ExamBank,output=document.querySelector('#exam-results')!;
const assert=(value:unknown,message:string)=>{if(!value)throw Error(message);};
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const checks:{name:string;result:string}[]=[];
function open(name:string,version?:number){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(name,version);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('student'))r.result.createObjectStore('student');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function read(name:string){const db=await open(name),version=db.version;const values=await Promise.all(['active','recovery'].map(k=>new Promise<unknown>(resolve=>{const r=db.transaction('student').objectStore('student').get(k);r.onsuccess=()=>resolve(r.result);})));db.close();return {version,values};}
async function reject(work:()=>Promise<unknown>){let rejected=false;try{await work();}catch{rejected=true;}assert(rejected,'Operation unexpectedly succeeded');}
async function seed(name:string){const {exams:_e,examReviews:_r,...base}=emptyBackup(),backup={...base,schemaVersion:2,attempts:[{attemptId:'prior-submission',contentVersion:CONTENT.version,subjectId:'CSE1400_CO',topicId:'CO_T06_ASSEMBLY_X86_64',targetedSkillIds:[],status:'SUBMITTED',answer:{kind:'text',value:'Prior learner response'},hintsUsed:null,solutionViewed:null,createdAt:'2026-09-09T12:00:00.000Z',updatedAt:'2026-09-09T12:00:00.000Z',revision:3,submission:{operationId:'prior-operation',submittedAt:'2026-09-09T12:00:00.000Z'}}],reviews:[{attemptId:'prior-submission',reviewedAt:'2026-09-09T12:00:00.000Z',revision:2}]},active={...backup,generation:'old',revision:19};const db=await open(name,2);await new Promise<void>((resolve,reject)=>{const tx=db.transaction('student','readwrite');tx.objectStore('student').put(active,'active');tx.objectStore('student').put(backup,'recovery');tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);});db.close();return {active,backup};}
async function check(name:string,work:()=>Promise<void>){try{await work();checks.push({name,result:'PASS'});}catch(e){checks.push({name,result:'FAIL '+String(e)});}output.textContent=JSON.stringify({browser:navigator.userAgent,checks,failures:checks.filter(c=>c.result!=='PASS').length},null,2);}
async function run(){checks.length=0;const name='step10-native-'+crypto.randomUUID(),old=await seed(name),repo=new IndexedStudentRepository({name}),tab=new IndexedStudentRepository({name});let state:LoadedState;
 await check('native Schema 2→3 active/recovery migration and cooperative versionchange',async()=>{const held=await open(name,2);let changed=false;held.onversionchange=()=>{changed=true;held.close();};state=await repo.load();assert(changed&&state.data.schemaVersion===3&&state.data.revision===19&&state.data.generation!=='old','Migration metadata');assert((await read(name)).version===3,'DB version');assert(same(state.data.attempts,old.active.attempts)&&same(state.data.reviews,old.active.reviews),'Prior attempts/reviews');const recovery=await repo.exportRecovery();assert(recovery.schemaVersion===3&&same(recovery.attempts,old.backup.attempts)&&same(recovery.reviews,old.backup.reviews),'Recovery migration');});
 await check('native session save and stale second connection conflict',async()=>{state=await repo.startExam(bank,'ds.exam.co.quick','native','one',state.data);const stale=await tab.load(),s=state.data.exams[0];s.responses[0].answer={kind:'text',value:'00000'};state=await repo.saveExam('one',1,s.responses,[s.items[0].id],state.data);await reject(()=>tab.saveExam('one',1,stale.data.exams[0].responses,[],stale.data));assert((await tab.load()).data.exams[0].responses[0].answer.value==='00000','Newer response lost');});
 await check('native submission request-success then abort rolls back lock and evidence',async()=>{const before=await repo.exportBackup(),put=IDBObjectStore.prototype.put;let succeeded=false;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const r=put.call(this,value,key);if(this.transaction.db.name===name&&key==='active')r.addEventListener('success',()=>{succeeded=true;this.transaction.abort();});return r;};try{await reject(()=>repo.submitExam(state.data.exams[0],'op',bank,state.data));}finally{IDBObjectStore.prototype.put=put;}assert(succeeded&&same(await repo.exportBackup(),before),'Atomic submit rollback failed');});
 await check('native commit, immutable submission, stale post-submit write and idempotency',async()=>{const original=structuredClone(state.data.exams[0]);state=await repo.submitExam(original,'op',bank,state.data);assert(state.data.attempts.length===2&&state.data.exams[0].status==='SUBMITTED','Commit missing');await reject(()=>tab.saveExam('one',original.revision,original.responses,[],state.data));assert(same(await repo.submitExam(original,'op',bank,state.data),state),'Idempotency drift');});
 await check('native backup round trip, recovery replacement and generation invalidation',async()=>{const before=await repo.exportBackup();assert(same(parseBackup(JSON.stringify(before)),before),'Round trip');const stale=state;state=await repo.restore(before,state.data);assert(same(await repo.exportRecovery(),before),'Recovery mismatch');await reject(()=>tab.startExam(bank,'ds.exam.co.quick','x','stale',stale.data));});
 await check('native aborted restore preserves active and recovery',async()=>{const before=await read(name),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const r=put.call(this,value,key);if(this.transaction.db.name===name&&key==='active')r.addEventListener('success',()=>this.transaction.abort());return r;};try{await reject(()=>repo.restore(emptyBackup(),state.data));}finally{IDBObjectStore.prototype.put=put;}assert(same(await read(name),before),'Partial restore');});
 await check('native aborted version upgrade rolls back DB 2 and both records',async()=>{const n='step10-abort-'+crypto.randomUUID(),saved=await seed(n),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const r=put.call(this,value,key);if(this.transaction.db.name===n&&key==='recovery')r.addEventListener('success',()=>this.transaction.abort());return r;};const failing=new IndexedStudentRepository({name:n});try{await reject(()=>failing.load());}finally{IDBObjectStore.prototype.put=put;failing.close();}assert(same(await read(n),{version:2,values:[saved.active,saved.backup]}),'Upgrade rollback');});
 await check('native deadline boundary freezes saves and permits explicit confirmation',async()=>{let now=Date.now();const timed=new IndexedStudentRepository({name:'step10-timer-'+crypto.randomUUID(),now:()=>new Date(now).toISOString()});let s=await timed.load();s=await timed.startExam(bank,'ds.exam.co.quick','x','timer',s.data);const original=structuredClone(s.data.exams[0]);now=Date.parse(original.deadlineAt);await reject(()=>timed.saveExam('timer',1,original.responses,[],s.data));s=await timed.submitExam(original,'expired',bank,s.data);assert(s.data.exams[0].deadlineAt===original.deadlineAt&&s.data.exams[0].submission?.submittedAt===original.deadlineAt,'Deadline drift');timed.close();});
 await check('prepare reload of committed session',async()=>{sessionStorage.setItem('step10-reload',name);assert((await repo.load()).data.exams[0].status==='SUBMITTED','Not committed');});repo.close();tab.close();
}
document.querySelector('#run-exam')!.addEventListener('click',()=>void run());
document.querySelector('#reload-exam')!.addEventListener('click',()=>void check('actual page reload preserves immutable session versions, deadline and evidence',async()=>{const name=sessionStorage.getItem('step10-reload');assert(name?.startsWith('step10-native-'),'Run checks first');const repo=new IndexedStudentRepository({name:name!}),state=await repo.load(),s=state.data.exams[0];assert(s.status==='SUBMITTED'&&s.responses[0].answer.value==='00000'&&s.flagged.length===1&&state.data.attempts.length===2,'Committed record lost');assert(s.deadlineAt===startSession(bank.blueprints[0],bank,s.seed,s.sessionId,Date.parse(s.startedAt)).deadlineAt,'Deadline changed');repo.close();}));
