import {IndexedStudentRepository} from '../../src/learning/repository';
import {emptyBackup,parseBackup,type Dataset} from '../../src/learning/contracts';
import {record,text,CLOCK} from '../helpers/adaptive';
import {deriveEvidence} from '../../src/adaptive/evidence';
const output=document.querySelector('#step9-results')!;
const checks:{name:string;result:string}[]=[];
const assert=(ok:unknown,message:string)=>{if(!ok)throw new Error(message);};
const eq=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
async function rejects(work:()=>Promise<unknown>,code:string){try{await work();}catch(e){assert(typeof e==='object'&&e!==null&&'code' in e&&e.code===code,`Expected ${code}, got ${String(e)}`);return;}throw new Error('Unexpected success');}
function open(name:string,version?:number){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(name,version);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('student'))r.result.createObjectStore('student');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function seed(name:string){const {reviews:_reviews,...base}=emptyBackup();const backup={...base,schemaVersion:1,attempts:[record('legacy-wrong','enrich-carry-overflow',text('1,1'),2),record('legacy-success','enrich-carry-overflow',text('1,0'),1)]};const active={...backup,generation:'legacy-generation',revision:7};const db=await open(name,1);await new Promise<void>((resolve,reject)=>{const tx=db.transaction('student','readwrite');tx.objectStore('student').put(active,'active');tx.objectStore('student').put(backup,'recovery');tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);});db.close();return {active,backup};}
async function read(name:string){const db=await open(name);const values=await Promise.all(['active','recovery'].map(key=>new Promise<unknown>(resolve=>{const r=db.transaction('student').objectStore('student').get(key);r.onsuccess=()=>resolve(r.result);})));const version=db.version;db.close();return {version,values};}
async function check(name:string,work:()=>Promise<void>){try{await work();checks.push({name,result:'PASS'});}catch(e){checks.push({name,result:'FAIL: '+String(e)});}output.textContent=JSON.stringify({checks,failures:checks.filter(c=>c.result!=='PASS').length},null,2);}
async function run(){
 checks.length=0;const name='delftstudy-step9-native-'+crypto.randomUUID(),old=await seed(name),repo=new IndexedStudentRepository({name}),other=new IndexedStudentRepository({name});let state:Dataset;
 await check('real v1 connection versionchange and atomic Schema/DB 2 migration preserve submitted bytes',async()=>{const held=await open(name,1);let changed=false;held.onversionchange=()=>{changed=true;held.close();};state=(await repo.load()).data;assert(changed,'Old connection did not close');assert(eq(state.attempts,old.active.attempts),'Original submissions changed');assert(state.revision===7&&state.generation!=='legacy-generation','Revision/generation migration');assert((await read(name)).version===2,'Not version 2');assert(eq((await repo.exportRecovery()).attempts,old.backup.attempts),'Recovery attempts changed');});
 await check('legacy generation rejects writes inside the new transaction',async()=>{await rejects(()=>repo.setReviewed('legacy-wrong',0,true,{generation:'legacy-generation'}),'CONFLICT');});
 await check('historical interpretation retains original binding and later success without deleting mistake',async()=>{const evidence=deriveEvidence(state.attempts,[],CLOCK);assert(evidence.mistakes.length===1&&evidence.groups[0].laterSuccesses===1,'Wrong historical result');const changed=structuredClone(state.attempts[0]);changed.exercise!.version='unavailable-newer-version';assert(deriveEvidence([changed],[],CLOCK).limited.length===1,'Missing version was guessed');});
 await check('workflow commits, survives another connection and never modifies answer bytes',async()=>{state=(await repo.setReviewed('legacy-wrong',0,true,state)).data;const loaded=await other.load();assert(loaded.data.reviews.length===1,'Review missing');assert(eq(loaded.data.attempts,old.active.attempts),'Attempts rewritten');});
 await check('concurrent review revisions conflict safely',async()=>{await rejects(()=>other.setReviewed('legacy-wrong',0,false,state),'CONFLICT');});
 await check('request success then abort is not a saved workflow action',async()=>{const before=await repo.exportBackup(),put=IDBObjectStore.prototype.put;let succeeded=false;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const r=put.call(this,value,key);if(this.transaction.db.name===name)r.addEventListener('success',()=>{succeeded=true;this.transaction.abort();});return r;};try{await rejects(()=>repo.setReviewed('legacy-wrong',1,false,state),'STORAGE');}finally{IDBObjectStore.prototype.put=put;}assert(succeeded&&eq(await repo.exportBackup(),before),'Aborted write changed data');});
 await check('Schema 2 export/import round trip preserves workflow and exact attempt bindings',async()=>{const before=await repo.exportBackup();assert(eq(parseBackup(JSON.stringify(before)),before),'Round-trip drift');state=(await repo.restore(before,state)).data;assert(eq(await repo.exportRecovery(),before),'Recovery mismatch');});
 await check('Schema 1 import migrates and preserves pre-import review workflow',async()=>{const before=await repo.exportBackup();state=(await repo.restore(old.backup,state)).data;assert(state.reviews.length===0,'Legacy workflow invented');assert(eq(await repo.exportRecovery(),before),'Pre-restore snapshot missing');assert(eq(state.attempts,old.active.attempts),'Legacy import lost submissions');});
 await check('restore changes epoch and rejects a stale second connection',async()=>{const stale=state;state=(await repo.restore(await repo.exportBackup(),state)).data;await rejects(()=>other.setReviewed('legacy-wrong',0,true,stale),'CONFLICT');});
 await check('aborted restore retains both prior active and recovery exactly',async()=>{const before=await read(name),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const r=put.call(this,value,key);if(this.transaction.db.name===name&&key==='active')r.addEventListener('success',()=>this.transaction.abort());return r;};try{await rejects(()=>repo.restore(emptyBackup(),state),'STORAGE');}finally{IDBObjectStore.prototype.put=put;}assert(eq(await read(name),before),'Partial restore');});
 await check('malformed, future, duplicate and corrupted review backups fail before mutation',async()=>{const before=await repo.exportBackup();for(const bad of [{...before,schemaVersion:99},{...before,reviews:[{attemptId:'missing',reviewedAt:null,revision:1}]},{...before,attempts:[...before.attempts,before.attempts[0]]}]){try{await repo.restore(bad,state);throw new Error('Unexpected valid import');}catch(e){assert(e instanceof Error&&e.message!=='Unexpected valid import','Bad import accepted');}}assert(eq(await repo.exportBackup(),before),'Failed preflight changed data');});
 await check('aborted native version upgrade rolls back DB version, active and recovery',async()=>{const aborted='delftstudy-step9-native-abort-'+crypto.randomUUID();const saved=await seed(aborted),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:unknown,key?:IDBValidKey){const r=put.call(this,value,key);if(this.transaction.db.name===aborted&&key==='recovery')r.addEventListener('success',()=>this.transaction.abort());return r;};const failing=new IndexedStudentRepository({name:aborted});try{await rejects(()=>failing.load(),'STORAGE');}finally{IDBObjectStore.prototype.put=put;failing.close();}assert(eq(await read(aborted),{version:1,values:[saved.active,saved.backup]}),'Upgrade failed without rollback');});
 await check('version 1 client cannot reopen upgraded database',async()=>{try{const db=await open(name,1);db.close();throw new Error('Old client opened');}catch(e){assert(e instanceof DOMException&&e.name==='VersionError','Missing VersionError');}});
 await check('prepare actual page reload with committed review marker',async()=>{state=(await repo.setReviewed('legacy-wrong',0,true,state)).data;sessionStorage.setItem('delftstudy-step9-reload',name);assert(state.reviews[0].reviewedAt!==null,'Not reviewed');});repo.close();other.close();
}
document.querySelector('#run-step9')!.addEventListener('click',()=>{void run();});
document.querySelector('#reload-step9')!.addEventListener('click',()=>{void check('actual page reload preserves Schema 2 attempts, binding and workflow',async()=>{const name=sessionStorage.getItem('delftstudy-step9-reload');assert(name?.startsWith('delftstudy-step9-native-'),'Run native checks first');const repo=new IndexedStudentRepository({name:name!});const state=await repo.load();assert(state.data.attempts.length===2&&state.data.reviews[0].reviewedAt!==null,'Committed records lost');assert(deriveEvidence(state.data.attempts,state.data.reviews,CLOCK).mistakes.length===1,'Original binding lost');repo.close();});});
