import {academicIndex} from '../academic/navigation';
import type {Evidence} from './evidence';
import type {ActionKind,Recommendation} from './engine';
import {buildStudySession} from './session';
export type StudyMethodId='flexible'|'pomodoro'|'52-17'|'time-blocking'|'active-recall'|'interleaving';
export type StudyBlockKind='focus'|'break'|'learn'|'practice'|'recall'|'review'|'interleave';
export type TimeBlockingProfile='new'|'active'|'mistakes';
export type StudyMethodUnavailableReason='course'|'duration'|'whole-course'|'topics'|null;
export interface StudyTimeBlock{id:string;kind:StudyBlockKind;minutes:number}
export interface StructuredStudyBlock extends StudyTimeBlock{topicId?:string;activities:Recommendation[]}
export interface StructuredStudySession{method:Exclude<StudyMethodId,'flexible'>;totalMinutes:number;focusMinutes:number;breakMinutes:number;profile?:TimeBlockingProfile;blocks:StructuredStudyBlock[]}
export const STUDY_METHODS=[
{id:'flexible',nameKey:'studyMethod.flexible.name',descriptionKey:'studyMethod.flexible.description',structureKey:'studyMethod.flexible.structure',minimumMinutes:1},
{id:'pomodoro',nameKey:'studyMethod.pomodoro.name',descriptionKey:'studyMethod.pomodoro.description',structureKey:'studyMethod.pomodoro.structure',minimumMinutes:30},
{id:'52-17',nameKey:'studyMethod.52-17.name',descriptionKey:'studyMethod.52-17.description',structureKey:'studyMethod.52-17.structure',minimumMinutes:69},
{id:'time-blocking',nameKey:'studyMethod.timeBlocking.name',descriptionKey:'studyMethod.timeBlocking.description',structureKey:'studyMethod.timeBlocking.structure',minimumMinutes:30},
{id:'active-recall',nameKey:'studyMethod.activeRecall.name',descriptionKey:'studyMethod.activeRecall.description',structureKey:'studyMethod.activeRecall.structure',minimumMinutes:15},
{id:'interleaving',nameKey:'studyMethod.interleaving.name',descriptionKey:'studyMethod.interleaving.description',structureKey:'studyMethod.interleaving.structure',minimumMinutes:30},
] as const;
export function parseStudyMethod(value:string|null):StudyMethodId{return STUDY_METHODS.some(x=>x.id===value)?value as StudyMethodId:'flexible'}
export function studyMethodAvailability(method:StudyMethodId,o:{minutes:number;subjectId?:string;topicId?:string;eligibleTopicCount:number}):{available:boolean;reason:StudyMethodUnavailableReason}{const d=STUDY_METHODS.find(x=>x.id===method)!;if(method==='interleaving'&&!o.subjectId)return{available:false,reason:'course'};if(o.minutes<d.minimumMinutes)return{available:false,reason:'duration'};if(method==='interleaving'&&o.topicId)return{available:false,reason:'whole-course'};if(method==='interleaving'&&o.eligibleTopicCount<2)return{available:false,reason:'topics'};return{available:true,reason:null}}
function ratio(total:number,weights:readonly number[]){if(total<weights.length*5)throw new Error('Duration too short.');const out:number[]=[];let left=total;for(let i=0;i<weights.length-1;i++){const later=(weights.length-i-1)*5,n=Math.max(5,Math.min(left-later,Math.round(total*weights[i]/5)*5));out.push(n);left-=n}out.push(left);return out}
function alternating(total:number,focus:number,rest:number){const out:StudyTimeBlock[]=[];let left=total,i=1;while(left>=focus+rest){out.push({id:`focus-${i}`,kind:'focus',minutes:focus},{id:`break-${i}`,kind:'break',minutes:rest});left-=focus+rest;i++}if(left>=5)out.push({id:`focus-${i}`,kind:'focus',minutes:left});else if(left){const last=[...out].reverse().find(x=>x.kind==='focus');if(last)last.minutes+=left}return out}
export function buildTimeStructure(method:StudyMethodId,minutes:number,profile:TimeBlockingProfile='active',topicCount=3):StudyTimeBlock[]{if(!Number.isInteger(minutes)||minutes<=0)throw new Error('Duration must be a positive integer.');if(method==='flexible')return[{id:'flexible-1',kind:'focus',minutes}];if(method==='pomodoro')return alternating(minutes,25,5);if(method==='52-17')return alternating(minutes,52,17);if(method==='time-blocking'){const presets:Record<number,readonly number[]>={30:[10,15,5],45:[10,25,10],60:[15,30,15],90:[20,45,25],120:[30,60,30]},values=profile==='new'&&presets[minutes]?[...presets[minutes]]:ratio(minutes,profile==='mistakes'?[.25,.45,.3]:profile==='active'?[.2,.5,.3]:[.25,.5,.25]),kinds:StudyBlockKind[]=profile==='mistakes'?['review','practice','review']:['learn','practice','review'];return values.map((n,i)=>({id:`${kinds[i]}-${i+1}`,kind:kinds[i],minutes:n}))}if(method==='active-recall'){const table:Record<number,readonly number[]>={15:[5,10],30:[10,15,5],45:[10,25,10],60:[15,30,15],90:[20,50,20],120:[25,65,30]},values=table[minutes]?[...table[minutes]]:ratio(minutes,minutes<30?[.35,.65]:[.25,.5,.25]),kinds:StudyBlockKind[]=values.length===2?['recall','practice']:['recall','practice','review'];return values.map((n,i)=>({id:`${kinds[i]}-${i+1}`,kind:kinds[i],minutes:n}))}const count=Math.max(2,Math.min(topicCount,minutes<=30?2:minutes<=90?3:4));return ratio(minutes,Array.from({length:count},()=>1/count)).map((n,i)=>({id:`interleave-${i+1}`,kind:'interleave',minutes:n}))}
export function selectTimeBlockingProfile(evidence:Evidence,o:{subjectId:string;topicId?:string;hasActivity:boolean}):TimeBlockingProfile{const groups=evidence.groups.filter(g=>g.skill.subjectId===o.subjectId&&(!o.topicId||g.skill.topicId===o.topicId));if(groups.some(g=>g.recent.length&&!g.laterSuccesses))return'mistakes';return o.hasActivity?'active':'new'}
const pref:Record<StudyBlockKind,readonly ActionKind[]>={focus:['learn','guided','practice','review','flashcards','retry','workspace','coding'],break:[],learn:['learn','guided','review','flashcards','practice','retry','workspace','coding'],practice:['practice','guided','coding','workspace','retry','flashcards','learn','review'],recall:['flashcards','retry','practice','guided','learn','review','workspace','coding'],review:['review','learn','flashcards','retry','practice','guided','workspace','coding'],interleave:['practice','guided','flashcards','learn','review','retry','workspace','coding']};
function allocate(pool:Recommendation[],minutes:number,kind:StudyBlockKind,used:Set<string>){const rank=new Map(pref[kind].map((x,i)=>[x,i])),available=pool.filter(x=>!used.has(x.to)).sort((a,b)=>(rank.get(a.kind)??99)-(rank.get(b.kind)??99)||b.priority-a.priority||a.id.localeCompare(b.id));if(!available.length)return[];const chosen=available.slice(0,Math.min(minutes<10?1:minutes<25?2:3,available.length,Math.max(1,Math.floor(minutes/5)))),parts:number[]=chosen.map(()=>minutes<5?0:5);let left=minutes-parts.reduce((s,n)=>s+n,0);for(let i=0;left>=5;i=(i+1)%chosen.length){parts[i]+=5;left-=5}parts[0]+=left;chosen.forEach(x=>used.add(x.to));return chosen.map((x,i)=>({...x,id:`${x.id}:${kind}`,minutes:parts[i]}))}
const pool=(e:Evidence,subjectId:string,topicId?:string)=>buildStudySession(e,{minutes:120,subjectId,topicId});
export function buildStructuredStudySession(evidence:Evidence,o:{method:Exclude<StudyMethodId,'flexible'>;minutes:number;subjectId:string;topicId?:string;hasActivity:boolean}):StructuredStudySession{const topics=academicIndex.topics.filter(x=>x.subject_id===o.subjectId).sort((a,b)=>a.order-b.order),available=studyMethodAvailability(o.method,{...o,eligibleTopicCount:topics.length});if(!available.available)throw new Error(`Unavailable: ${available.reason}`);const profile=o.method==='time-blocking'?selectTimeBlockingProfile(evidence,o):undefined,ordered=[...new Set([...evidence.groups.filter(g=>g.skill.subjectId===o.subjectId).map(g=>g.skill.topicId),...topics.map(x=>x.topic_id)])],structure=buildTimeStructure(o.method,o.minutes,profile,ordered.length),used=new Set<string>(),shared=o.method==='interleaving'?null:pool(evidence,o.subjectId,o.topicId);let cursor=0;const blocks=structure.map(b=>{if(b.kind==='break')return{...b,activities:[]};const topicId=o.method==='interleaving'?ordered[cursor++%ordered.length]:o.topicId;return{...b,topicId,activities:allocate(shared??pool(evidence,o.subjectId,topicId),b.minutes,b.kind,used)}});return{method:o.method,totalMinutes:o.minutes,focusMinutes:blocks.filter(b=>b.kind!=='break').reduce((s,b)=>s+b.minutes,0),breakMinutes:blocks.filter(b=>b.kind==='break').reduce((s,b)=>s+b.minutes,0),profile,blocks}}
