import {useEffect,useMemo,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router';
import {PageHeading,EmptyState} from '../shell/PageParts';
import {courses,academicIndex} from '../academic/navigation';
import {useEvidence} from './useEvidence';
import {buildStudySession,STUDY_TIME_PRESETS,type StudyTimePreset} from './session';
import type {Recommendation} from './engine';
import {buildStructuredStudySession,parseStudyMethod,STUDY_METHODS,studyMethodAvailability,type StructuredStudySession,type StudyBlockKind,type StudyMethodUnavailableReason} from './study-methods';
import {claimRecommendationImpression,recommendationImpressionKey,recommendStudyMethod,studyMethodSelectionSource,type StudyMethodRecommendationReason} from './study-method-recommendation';
import './adaptive.css';
import {useI18n} from '../i18n/i18n';
import {actionKind,presentAction,studyTimeLabel} from './presentation';
import {track} from '../analytics/analytics';
import {durationBucket} from '../analytics/events';
type Result=Recommendation[]|StructuredStudySession;
const blockKey:Record<StudyBlockKind,any>={focus:'studyMethod.block.focus',break:'studyMethod.block.break',learn:'studyMethod.block.learn',practice:'studyMethod.block.practice',recall:'studyMethod.block.recall',review:'studyMethod.block.review',interleave:'studyMethod.block.interleave'};
const reasonKey:Record<StudyMethodRecommendationReason,any>={'new-learner':'studyMethod.reason.newLearner','practice-short':'studyMethod.reason.practiceShort','deep-focus':'studyMethod.reason.deepFocus','complex-work':'studyMethod.reason.complexWork','retrieval':'studyMethod.reason.retrieval','multi-topic':'studyMethod.reason.multiTopic','flexible-fallback':'studyMethod.reason.flexibleFallback'};
const icon:Record<string,string>={flexible:'↝',pomodoro:'◷','52-17':'◴','time-blocking':'▦','active-recall':'↺',interleaving:'⇄'};
export function StudyPathPage({build=buildStudySession}:{build?:typeof buildStudySession}){
 const {t,lt}=useI18n(),{learning,evidence,refresh}=useEvidence(),[params,setParams]=useSearchParams();
 const minutesParam=params.get('minutes'),input=Number(minutesParam??30),validMinutes=STUDY_TIME_PRESETS.some(n=>n===input),minutes=(validMinutes?input:30) as StudyTimePreset,subjectId=params.get('course')??'',topicId=params.get('topic')??'',methodParam=params.get('method'),parsedMethod=parseStudyMethod(methodParam),explicitMethod=methodParam!==null&&STUDY_METHODS.some(item=>item.id===methodParam);
 const [path,setPath]=useState<Result|null>(null),[error,setError]=useState(''),eligibleTopics=academicIndex.topics.filter(x=>x.subject_id===subjectId),eligibleTopicCount=eligibleTopics.length,attempts=learning?.snapshot?.data.attempts??[],hasActivity=Boolean(attempts.length);
 useEffect(()=>{if(minutesParam===null||validMinutes)return;const next=new URLSearchParams(params);next.set('minutes','30');setParams(next,{replace:true})},[minutesParam,params,setParams,validMinutes]);
 const recommendationInput=useMemo(()=>{let candidates:Recommendation[]=[];if(subjectId)try{candidates=buildStudySession(evidence,{minutes,subjectId,topicId:topicId||undefined})}catch{}const courseAttempts=attempts.filter(a=>a.subjectId===subjectId),contextAttempts=courseAttempts.filter(a=>!topicId||a.topicId===topicId);let usableTopicCount=0;for(const topic of eligibleTopics)try{if(buildStudySession(evidence,{minutes:15,subjectId,topicId:topic.topic_id}).length)usableTopicCount++}catch{}return {minutes,subjectId,topicId:topicId||undefined,eligibleTopicCount,usableTopicCount,hasCourseActivity:courseAttempts.length>0,hasContextActivity:contextAttempts.length>0,hasRecentMistakes:evidence.groups.some(g=>g.skill.subjectId===subjectId&&(!topicId||g.skill.topicId===topicId)&&g.recent.length>0),candidates}},[attempts,evidence,eligibleTopicCount,minutes,subjectId,topicId]);
 const recommendation=useMemo(()=>recommendStudyMethod(recommendationInput),[recommendationInput]),method=explicitMethod?parsedMethod:recommendation.methodId,status=studyMethodAvailability(method,{minutes,subjectId,topicId,eligibleTopicCount}),seen=useRef(new Set<string>());
 useEffect(()=>{if(!subjectId)return;const key=recommendationImpressionKey(recommendationInput,recommendation);if(!claimRecommendationImpression(seen.current,key))return;track('study_method_recommended',{method_id:recommendation.methodId,reason_code:recommendation.reasonCode,duration_bucket:durationBucket(minutes),course_id:subjectId,source_surface:'study_path'})},[minutes,recommendation,recommendationInput,subjectId]);
 function change(key:string,value:string){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key==='course')next.delete('topic');setParams(next);setPath(null);setError('')}
 function unavailable(reason:StudyMethodUnavailableReason,min:number){return reason==='duration'?t('studyMethod.unavailableDuration',{count:min}):reason==='course'?t('studyMethod.unavailableCourse'):reason==='whole-course'?t('studyMethod.unavailableWholeCourse'):reason==='topics'?t('studyMethod.unavailableTopics'):''}
 function generate(){try{const result=method==='flexible'?build(evidence,{minutes,subjectId,topicId:topicId||undefined}):buildStructuredStudySession(evidence,{method,minutes,subjectId,topicId:topicId||undefined,hasActivity});setPath(result);track('study_path_generated',{course_id:subjectId,topic_id:topicId||undefined,activity_type:'study_path',duration_bucket:durationBucket(minutes),source_surface:'study_path',method_id:method});setError('')}catch{setPath(null);setError(t('studyPath.errorKeep'))}}
 function opened(a:Recommendation){track('study_path_activity_opened',{course_id:a.subjectId,topic_id:a.topicId,activity_type:'practice',source_surface:'study_path'})}
 function card(a:Recommendation){return <article className="ds-path-card"><div className="ds-evidence-meta"><span>{courses.find(c=>c.subject_id===a.subjectId)!.compactName} · {actionKind(a.kind,t)}</span><span>{t('duration.short',{count:a.minutes})} · {t('duration.estimate')}</span></div><h3>{presentAction(a,t,lt).title}</h3><p>{academicIndex.topics.find(x=>x.topic_id===a.topicId)?.name??a.topicId}</p><p className="ds-path-reason"><strong>{t('studyPath.why')}</strong><br/>{presentAction(a,t,lt).reason}</p><Link className="ds-button" to={a.to} onClick={()=>opened(a)}>{t('studyPath.openActivity')} →</Link></article>}
 if(!learning?.snapshot)return <><PageHeading title={t('studyPath.title')} eyebrow={t('studyPath.eyebrow').toUpperCase()}/><p role="status">{learning?.message??t('mistakes.storage')}</p></>;
 const flat=Array.isArray(path)?path:null,structured=path&&!Array.isArray(path)?path:null,first=flat?.[0]??structured?.blocks.flatMap(b=>b.activities)[0],selected=STUDY_METHODS.find(x=>x.id===method)!;
 return <div className="ds-adaptive"><PageHeading title={t('studyPath.title')} eyebrow={t('studyPath.eyebrow').toUpperCase()}><p>{t('studyPath.description')}</p></PageHeading>
 <section className="ds-study-primary" aria-label={t('studyPath.eyebrow')}><div className="ds-study-scope"><label>{t('progress.course')}<select value={subjectId} onChange={e=>change('course',e.target.value)}><option value="">{t('studyPath.chooseCourse')}</option>{courses.map(c=><option key={c.subject_id} value={c.subject_id}>{c.publicName}</option>)}</select></label><label className="ds-study-duration">{t('studyPath.time')}<select value={minutes} onChange={e=>change('minutes',e.target.value)}>{STUDY_TIME_PRESETS.map(n=><option key={n} value={n}>{studyTimeLabel(n,t)}</option>)}</select></label></div>
  <div className="ds-method-summary"><p><strong>{t('studyMethod.recommendedWithMethod',{method:t(STUDY_METHODS.find(x=>x.id===recommendation.methodId)!.nameKey)})}</strong> {t(reasonKey[recommendation.reasonCode])}</p>{explicitMethod&&method!==recommendation.methodId&&<p>{t('studyPath.selectedMethod',{method:t(selected.nameKey)})}</p>}</div>
  <p>{t('studyPath.estimates')}</p><div className="ds-storage-actions"><button className="ds-button" disabled={!subjectId||learning.phase==='busy'||!status.available} onClick={generate}>{t('studyPath.build')}</button><button className="ds-button ds-button-secondary" disabled={learning.phase==='busy'} onClick={async()=>{await refresh();setPath(null);setError('')}}>{t('studyPath.reload')}</button><Link className="ds-text-link" to="/mistakes">{t('dashboard.reviewMistakes')} →</Link></div>{error&&<p role="alert">{error}</p>}
 </section>
 <details className="ds-study-customize" open={topicId||explicitMethod?true:undefined}><summary>{t('studyPath.customize')}</summary><div className="ds-study-scope"><label>{t('progress.topic')}<select disabled={!subjectId} value={topicId} onChange={e=>change('topic',e.target.value)}><option value="">{t('studyPath.courseFocus')}</option>{eligibleTopics.map(x=><option key={x.topic_id} value={x.topic_id}>{x.name}</option>)}</select></label></div>
  <fieldset className="ds-method-fieldset" aria-describedby="study-method-guidance"><legend>{t('studyMethod.heading')}</legend><p className="ds-method-intro">{t('studyMethod.compactIntro')}</p><div className="ds-method-grid">{STUDY_METHODS.map(d=>{const s=studyMethodAvailability(d.id,{minutes,subjectId,topicId,eligibleTopicCount}),recommended=d.id===recommendation.methodId;return <label className={'ds-method-card'+(method===d.id?' is-selected':'')+(!s.available?' is-disabled':'')} key={d.id}><input type="radio" name="study-method" value={d.id} checked={method===d.id} disabled={!s.available} onChange={()=>{change('method',d.id);track('study_method_selected',{method_id:d.id,source_surface:'study_path',selection_source:studyMethodSelectionSource(d.id,recommendation.methodId),recommended_method_id:recommendation.methodId})}}/><span className="ds-method-icon" aria-hidden="true">{icon[d.id]}</span><span className="ds-method-name">{t(d.nameKey)}</span><small>{s.available?t(`studyMethod.hint.${d.id}` as any):unavailable(s.reason,d.minimumMinutes)}</small>{recommended&&<span className="ds-method-badge">{t('studyMethod.recommended')}</span>}{method===d.id&&<span className="ds-method-check" aria-hidden="true">✓</span>}</label>})}</div><div className="ds-method-guidance" id="study-method-guidance"><p><strong>{t(selected.nameKey)}.</strong> {t(selected.descriptionKey)}</p><p className="ds-method-reason"><strong>{t('studyMethod.recommendedWithMethod',{method:t(STUDY_METHODS.find(x=>x.id===recommendation.methodId)!.nameKey)})}</strong> {t(reasonKey[recommendation.reasonCode])}</p></div></fieldset>
 </details>
 {path===null?<EmptyState title={t(subjectId?'studyPath.ready':'studyPath.choose')}><p>{t(subjectId?'studyPath.buildHint':'studyPath.courseRequired')}</p></EmptyState>:flat?<><p role="status">{t('studyPath.sessionSummary',{duration:studyTimeLabel(minutes,t),count:flat.length,minutes:flat.reduce((s,a)=>s+a.minutes,0)})}</p><ol className="ds-study-queue">{flat.map(a=><li key={a.id}>{card(a)}</li>)}</ol></>:structured&&<><p role="status">{t('studyMethod.sessionSummary',{method:t(STUDY_METHODS.find(x=>x.id===structured.method)!.nameKey),total:structured.totalMinutes,focus:structured.focusMinutes,breaks:structured.breakMinutes})}</p><ol className="ds-structured-timeline">{structured.blocks.map((b,i)=><li key={b.id}><section className={'ds-study-block ds-study-block-'+b.kind}><div className="ds-study-block-heading"><span>{t('studyMethod.blockNumber',{count:i+1})}</span><h2>{t(blockKey[b.kind])}</h2><strong>{t('duration.short',{count:b.minutes})}</strong></div>{b.topicId&&<p>{academicIndex.topics.find(x=>x.topic_id===b.topicId)?.name??b.topicId}</p>}{b.kind==='break'?<p>{t('studyMethod.breakBody')}</p>:<div className="ds-study-block-activities">{b.activities.map(a=><div key={a.id}>{card(a)}</div>)}</div>}</section></li>)}</ol></>}
 {path&&first&&<div className="ds-study-next"><Link className="ds-button" to={first.to} onClick={()=>opened(first)}>{t('studyPath.start')} →</Link><button className="ds-button ds-button-secondary" onClick={generate}>{t('studyPath.rebuild')}</button></div>}<details><summary>{t('studyPath.how')}</summary><p>{t('studyPath.howEvidence')}</p><p>{t('studyPath.howLonger')}</p><details><summary>{t('studyPath.technical')}</summary><p>{t('studyPath.technicalBody')}</p></details></details></div>
}
