import {useState} from 'react';
import {Link,useSearchParams} from 'react-router';
import {PageHeading,EmptyState} from '../shell/PageParts';
import {courses,academicIndex} from '../academic/navigation';
import {useEvidence} from './useEvidence';
import {buildStudySession,STUDY_TIME_PRESETS,studyTimeLabel,type StudyTimePreset} from './session';
import type {Recommendation} from './engine';
import './adaptive.css';
export function StudyPathPage({build=buildStudySession}:{build?:typeof buildStudySession}){
 const {learning,evidence,refresh}=useEvidence();const [params,setParams]=useSearchParams();
 const input=Number(params.get('minutes')??30),minutes=(STUDY_TIME_PRESETS.some(n=>n===input)?input:30) as StudyTimePreset;
 const subjectId=params.get('course')??'',topicId=params.get('topic')??'';
 const [path,setPath]=useState<Recommendation[]|null>(null);const [error,setError]=useState('');
 function change(key:string,value:string){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);if(key==='course')next.delete('topic');setParams(next);setPath(null);setError('');}
 function generate(){try{setPath(build(evidence,{minutes,subjectId,topicId:topicId||undefined}));setError('');}catch(cause){setPath(null);setError(cause instanceof Error?cause.message:'The study session could not be built.');}}
 if(!learning?.snapshot)return <><PageHeading title="Study Path" eyebrow="CHOOSE YOUR NEXT STEP"/><p role="status">{learning?.message??'Student storage is not connected.'}</p></>;
 return <div className="ds-adaptive"><PageHeading title="Study Path" eyebrow="BUILD A STUDY SESSION"><p>Choose a course, optional topic and available time. Your session uses authored DelftStudy content and your saved practice evidence when available.</p></PageHeading>
  <div className="ds-mistake-filters"><label>Available study time<select value={minutes} onChange={e=>change('minutes',e.target.value)}>{STUDY_TIME_PRESETS.map(n=><option key={n} value={n}>{studyTimeLabel(n)}</option>)}</select></label><label>Course<select value={subjectId} onChange={e=>change('course',e.target.value)}><option value="">Choose a course</option>{courses.map(c=><option key={c.subject_id} value={c.subject_id}>{c.short}</option>)}</select></label><label>Topic<select disabled={!subjectId} value={topicId} onChange={e=>change('topic',e.target.value)}><option value="">Course-wide focus</option>{academicIndex.topics.filter(t=>t.subject_id===subjectId).map(t=><option key={t.topic_id} value={t.topic_id}>{t.name}</option>)}</select></label></div>
  <p>Times are planning estimates. The 2h+ option is a bounded 120-minute extended session. Selections stay in the URL; generated sessions are not stored.</p>
  <div className="ds-storage-actions"><button className="ds-button" disabled={!subjectId||learning.phase==='busy'} onClick={generate}>Build Study Session</button><button className="ds-button ds-button-secondary" disabled={learning.phase==='busy'} onClick={async()=>{await refresh();setPath(null);setError('');}}>Reload saved evidence</button><Link className="ds-text-link" to="/mistakes">Review Mistake Book →</Link></div>
  {error&&<p role="alert">{error} Your selections are still available; try again.</p>}
  {path===null?<EmptyState title={subjectId?'Ready to build':'Choose a course'}><p>{subjectId?'Build the session when your course, topic and time look right.':'A course is required so every activity stays relevant.'}</p></EmptyState>:<><p role="status">Your {studyTimeLabel(minutes)} session · {path.length} activities · about {path.reduce((n,a)=>n+a.minutes,0)} minutes.</p><ol className="ds-study-queue">{path.map(action=><li key={action.id}><article className="ds-path-card"><div className="ds-evidence-meta"><span>{courses.find(c=>c.subject_id===action.subjectId)!.short} · {action.kind}</span><span>{action.minutes} min · {action.durationSource}</span></div><h2>{action.title}</h2><p>{academicIndex.topics.find(t=>t.topic_id===action.topicId)?.name??action.topicId}</p><p className="ds-path-reason"><strong>Why this next step</strong><br/>{action.reason}</p><Link className="ds-button" to={action.to}>Open activity →</Link></article></li>)}</ol><div className="ds-study-next"><Link className="ds-button" to={path[0].to}>Start first activity →</Link><button className="ds-button ds-button-secondary" onClick={generate}>Rebuild session</button></div></>}
  <details><summary>How this path is chosen</summary><p>Recent and repeated mistakes raise priority. Later correct answers and reviewed items reduce urgency without erasing your history. Without practice evidence, the session starts from authored course and topic structure.</p><p>Longer sessions add complementary phases such as prerequisite review, concept work, recall, focused application and exam-style work. They do not repeat an activity to fill time. These suggestions are study guidance, not a grade.</p><details><summary>Technical details</summary><p>Stable internal identifiers resolve ties. The extended preset uses a deterministic 120-minute planning budget. Open coding, proof self-checks and workspaces remain unscored, and this path does not calculate mastery, readiness or a predicted exam grade.</p></details></details>
 </div>;
}
