// @vitest-environment jsdom
import {act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {BrowserRouter} from 'react-router';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {AppRoutes} from '../src/App';
import {LearningProvider} from '../src/learning/LearningProvider';
import {emptyBackup,type Attempt} from '../src/learning/contracts';
import {repository} from './helpers/learning';
import {CLOCK,record,text} from './helpers/adaptive';
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
let host:HTMLDivElement,root:Root;
beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host);vi.spyOn(window,'scrollTo').mockImplementation(()=>{});vi.spyOn(Date,'now').mockReturnValue(CLOCK);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();});
const records=()=>[record('co1','enrich-carry-overflow',text('1,1'),3),record('co2','enrich-carry-overflow',text('1,1'),2),record('rl1','enrich-implication-directions',text('1,1,1'),1)];
async function settle(){for(let i=0;i<150;i++){await act(async()=>{await new Promise(r=>setTimeout(r,10));});if(![...host.querySelectorAll('[role=status]')].some(n=>/^(Loading |Opening )/.test(n.textContent??'')))return;}throw new Error('UI did not settle');}
async function mount(path='/mistakes',attempts:Attempt[]=records()) {const repo=repository();const state=await repo.load();await repo.restore({...emptyBackup(),attempts},state.data);window.history.replaceState(null,'',path);await act(async()=>{await import('../src/adaptive/EvidenceSummary');});await act(async()=>root.render(<BrowserRouter><LearningProvider createRepository={()=>repo}><AppRoutes/></LearningProvider></BrowserRouter>));await settle();return repo;}
async function click(label:string,scope:ParentNode=host){const b=[...scope.querySelectorAll('button')].find(b=>b.textContent===label);expect(b,label).toBeDefined();await act(async()=>b!.click());await settle();}
async function select(label:string,value:string){const el=[...host.querySelectorAll('label')].find(l=>l.childNodes[0]?.textContent===label)?.querySelector('select');expect(el,label).toBeTruthy();await act(async()=>{el!.value=value;el!.dispatchEvent(new Event('change',{bubbles:true}));});await settle();}
it('empty Mistake Book and path contain no invented evidence',async()=>{await mount('/mistakes',[]);expect(host.textContent).toContain('No deterministic mistakes yet');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(0);});
it('displays actual answers, patterns, repeated evidence and immutable links',async()=>{await mount();expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(3);expect(host.textContent).toContain('2 incorrect submissions on this exact skill');expect(host.textContent).toContain('Matched answer pattern');expect(host.querySelectorAll('a[href*="/attempts/"]')).toHaveLength(3);expect(host.querySelectorAll('.ds-answer-pair')).toHaveLength(3);});
it('course, topic, skill, pattern, recency and review filters operate through deep links',async()=>{await mount();await select('Course','CSE1400_CO');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);expect(window.location.search).toContain('CSE1400_CO');await select('View','repeated');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);await select('View','corrected');expect(host.textContent).toContain('No mistakes match');await select('View','all');await select('When','7');await select('Topic','CO_T04_DATA_REP_RADIX_INTEGER');await select('Skill','CO_SK04_04_OVERFLOW');const patterns=host.querySelectorAll<HTMLSelectElement>('select')[3];await select('Answer pattern',[...patterns.options].find(o=>o.textContent==='Carry versus signed overflow')!.value);expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);});
it('mark reviewed and undo persist separately without changing attempt bytes',async()=>{const repo=await mount(),before=JSON.stringify((await repo.load()).data.attempts);await click('Mark reviewed',host.querySelector('.ds-mistake-card')!);let backup=await repo.exportBackup();expect(backup.reviews).toHaveLength(1);expect(JSON.stringify(backup.attempts)).toBe(before);expect(host.textContent).toContain('Reviewed does not mean learned');await select('View','reviewed');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(1);await click('Undo reviewed');expect((await repo.exportBackup()).reviews[0].reviewedAt).toBeNull();expect(JSON.stringify((await repo.load()).data.attempts)).toBe(before);});
it('Retry creates a new draft and preserves the original wrong answer',async()=>{const repo=await mount(),before=(await repo.load()).data.attempts;await click('Retry as new attempt',host.querySelector('.ds-mistake-card')!);const after=(await repo.load()).data.attempts;expect(after).toHaveLength(4);expect(after.slice(0,3)).toEqual(before);expect(after[3].status).toBe('DRAFT');expect(after[3].attemptId).not.toBe(before[2].attemptId);expect(window.location.pathname).toContain('/attempts/'+after[3].attemptId);});
it('a failed reviewed save is surfaced and is never shown as saved',async()=>{const repo=await mount();vi.spyOn(repo,'setReviewed').mockRejectedValue(new Error('storage unavailable'));await click('Mark reviewed');expect(host.querySelector('[role=alert]')).toBeTruthy();expect((await repo.exportBackup()).reviews).toEqual([]);expect(host.querySelector('.ds-mistake-card')?.textContent).not.toContain('Marked reviewed');});
it('limited historical binding preserves the answer without a wrong label or recommendation',async()=>{const a=records()[0];a.exercise!.version='missing-version';await mount('/mistakes',[a]);expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(0);expect(host.textContent).toContain('limited or unavailable historical evidence');expect(host.querySelector('.ds-historical pre')?.textContent).toBe('1,1');});
it('Study Path explains each action, has duration labels and working direct links',async()=>{await mount('/study-plan');expect(host.querySelector('h1')?.textContent).toBe('Study Path');const cards=host.querySelectorAll('.ds-path-card');expect(cards.length).toBeGreaterThan(0);for(const card of cards){expect(card.textContent).toContain('Why this next step');expect(card.textContent).toContain('DelftStudy estimate');expect(card.querySelector('a')?.getAttribute('href')).toMatch(/^\//);}expect(host.textContent).not.toMatch(/\d+%|predicted grade:|readiness:/);});
it('time and course selection change the queue and persist in Back/Forward URL navigation',async()=>{await mount('/study-plan');await select('Available study time','10');expect(window.location.search).toContain('minutes=10');expect(host.querySelectorAll('.ds-path-card').length).toBeLessThanOrEqual(2);await select('Course','CSE1300_RL');expect([...host.querySelectorAll('.ds-path-card')].every(c=>c.textContent?.includes('R&L'))).toBe(true);await act(async()=>{const done=new Promise(r=>window.addEventListener('popstate',r,{once:true}));window.history.back();await done;});await settle();expect(window.location.search).not.toContain('course');await act(async()=>{const done=new Promise(r=>window.addEventListener('popstate',r,{once:true}));window.history.forward();await done;});await settle();expect(window.location.search).toContain('course');});
it('topic Mistakes displays only that topic; Dashboard links actual recent evidence',async()=>{await mount('/co/CO_T04_DATA_REP_RADIX_INTEGER/mistakes');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);expect(host.querySelector('h1')?.textContent).toContain('integer');});
it('all filters and actions use native keyboard controls and visible labels',async()=>{await mount();for(const select of host.querySelectorAll('select'))expect(select.closest('label')?.textContent?.length).toBeGreaterThan(3);const first=host.querySelector('select')!;first.focus();expect(document.activeElement).toBe(first);const button=host.querySelector('.ds-mistake-card button') as HTMLButtonElement;button.focus();expect(document.activeElement).toBe(button);expect(host.querySelectorAll('a[href="#"]')).toHaveLength(0);});
it('a dashboard summary appears only for real recent wrong evidence',async()=>{await mount('/');expect(host.querySelector('[aria-label="Recent practice evidence"]')?.textContent).toContain('3 recent mistakes');expect(host.querySelector('[aria-label="Recent practice evidence"] a')?.getAttribute('href')).toBe('/mistakes');});
it('review: repeated-pattern summary respects the selected course',async()=>{await mount('/mistakes',[record('co','enrich-carry-overflow',text('1,1'),1),record('rl1','enrich-implication-directions',text('1,1,1'),2),record('rl2','enrich-implication-directions',text('1,1,1'),1)]);await select('Course','CSE1400_CO');expect(host.textContent).toContain('0 skills with repeated exact answer patterns');});
