// @vitest-environment jsdom
import {act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {BrowserRouter} from 'react-router';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {AppRoutes} from '../src/App';
import {StudyPathPage} from '../src/adaptive/StudyPathPage';
import {LearningProvider} from '../src/learning/LearningProvider';
import {emptyBackup,type Attempt} from '../src/learning/contracts';
import {repository} from './helpers/learning';
import {CLOCK,record,text} from './helpers/adaptive';
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
let host:HTMLDivElement,root:Root;
beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host);vi.spyOn(window,'scrollTo').mockImplementation(()=>{});vi.spyOn(Date,'now').mockReturnValue(CLOCK);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();});
const records=()=>[record('co1','enrich-carry-overflow',text('1,1'),3),record('co2','enrich-carry-overflow',text('1,1'),2),record('rl1','enrich-implication-directions',text('1,1,1'),1)];
async function settle(){for(let i=0;i<150;i++){await act(async()=>{await new Promise(r=>setTimeout(r,10));});if(![...host.querySelectorAll('[role=status]')].some(n=>/^(Loading |Opening )/.test(n.textContent??'')))return;}throw new Error('UI did not settle');}
async function mount(path='/mistakes',attempts:Attempt[]=records()) {const repo=repository();const state=await repo.load();await repo.restore({...emptyBackup(),attempts},state.data);window.history.replaceState(null,'',path);await act(async()=>{await import('../src/adaptive/EvidenceSummary');});await act(async()=>root.render(<BrowserRouter><LearningProvider createRepository={()=>repo}><AppRoutes/></LearningProvider></BrowserRouter>));await settle();return repo;}
async function click(label:string,scope:ParentNode=host){const b=[...scope.querySelectorAll('button')].find(b=>b.textContent===label);expect(b,label).toBeDefined();await act(async()=>b!.click());await settle();}
async function select(label:string,value:string){const el=[...host.querySelectorAll('label')].find(l=>l.childNodes[0]?.textContent===label)?.querySelector('select');expect(el,label).toBeTruthy();await act(async()=>{el!.value=value;el!.dispatchEvent(new Event('change',{bubbles:true}));});await settle();}
it('empty Mistake Book and path contain no invented evidence',async()=>{await mount('/mistakes',[]);expect(host.textContent).toContain('Nothing needs review right now');expect(host.textContent).toContain('No deterministic mistakes yet');expect(host.querySelectorAll('.ds-review-now-card,.ds-mistake-card')).toHaveLength(0);});
it('shows a compact actionable queue above the unchanged full history',async()=>{await mount();const queue=host.querySelectorAll('.ds-review-now-card');expect(queue).toHaveLength(2);expect(queue[0].textContent).toContain('This answer pattern appeared more than once recently.');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(3);expect(host.textContent?.indexOf('Review now')).toBeLessThan(host.textContent?.indexOf('All mistakes')??0);});
it('displays actual answers, patterns, repeated evidence and immutable links',async()=>{await mount();expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(3);expect(host.textContent).toContain('2 incorrect submissions on this exact skill');expect(host.textContent).toContain('Matched answer pattern');expect(host.querySelectorAll('.ds-mistake-card a[href*="/attempts/"]')).toHaveLength(3);expect(host.querySelectorAll('.ds-answer-pair')).toHaveLength(3);});
it('course, topic, skill, pattern, recency and review filters operate through deep links',async()=>{await mount();await select('Course','CSE1400_CO');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);expect(window.location.search).toContain('CSE1400_CO');await select('View','repeated');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);await select('View','corrected');expect(host.textContent).toContain('No mistakes match');await select('View','all');await select('When','7');await select('Topic','CO_T04_DATA_REP_RADIX_INTEGER');await select('Skill','CO_SK04_04_OVERFLOW');const patterns=host.querySelectorAll<HTMLSelectElement>('select')[3];await select('Answer pattern',[...patterns.options].find(o=>o.textContent==='Carry versus signed overflow')!.value);expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);});
it('mark reviewed and undo persist separately without changing attempt bytes',async()=>{const repo=await mount(),before=JSON.stringify((await repo.load()).data.attempts);await click('Mark reviewed',host.querySelector('.ds-mistake-card')!);let backup=await repo.exportBackup();expect(backup.reviews).toHaveLength(1);expect(JSON.stringify(backup.attempts)).toBe(before);expect(host.textContent).toContain('Reviewed does not mean learned');await select('View','reviewed');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(1);await click('Undo reviewed');expect((await repo.exportBackup()).reviews[0].reviewedAt).toBeNull();expect(JSON.stringify((await repo.load()).data.attempts)).toBe(before);});
it('Retry creates a new draft and preserves the original wrong answer',async()=>{const repo=await mount(),before=(await repo.load()).data.attempts;await click('Retry as new attempt',host.querySelector('.ds-mistake-card')!);const after=(await repo.load()).data.attempts;expect(after).toHaveLength(4);expect(after.slice(0,3)).toEqual(before);expect(after[3].status).toBe('DRAFT');expect(after[3].attemptId).not.toBe(before[2].attemptId);expect(window.location.pathname).toContain('/attempts/'+after[3].attemptId);});
it('Review now Retry uses the existing attempt path and preserves history',async()=>{const repo=await mount(),before=(await repo.load()).data.attempts;await click('Retry as new attempt',host.querySelector('.ds-review-now-card')!);const after=(await repo.load()).data.attempts;expect(after.slice(0,3)).toEqual(before);expect(after[3]).toMatchObject({status:'DRAFT'});expect(window.location.pathname).toContain('/attempts/'+after[3].attemptId);});
it('a failed reviewed save is surfaced and is never shown as saved',async()=>{const repo=await mount();vi.spyOn(repo,'setReviewed').mockRejectedValue(new Error('storage unavailable'));await click('Mark reviewed');expect(host.querySelector('[role=alert]')).toBeTruthy();expect((await repo.exportBackup()).reviews).toEqual([]);expect(host.querySelector('.ds-mistake-card')?.textContent).not.toContain('Marked reviewed');});
it('limited historical binding preserves the answer without a wrong label or recommendation',async()=>{const a=records()[0];a.exercise!.version='missing-version';await mount('/mistakes',[a]);expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(0);expect(host.textContent).toContain('older submissions cannot be checked');expect(host.querySelector('.ds-historical pre')?.textContent).toBe('1,1');});
it('Study Path starts with course, time, recommendation and Build while customization stays collapsed',async()=>{await mount('/study-plan');expect(host.querySelector('h1')?.textContent).toBe('Study Path');const customize=host.querySelector<HTMLDetailsElement>('.ds-study-customize')!;expect(customize.open).toBe(false);expect(customize.querySelectorAll('.ds-method-card')).toHaveLength(6);const build=[...host.querySelectorAll('button')].find(button=>button.textContent==='Build Study Session') as HTMLButtonElement;expect(build.disabled).toBe(true);const duration=[...host.querySelectorAll('label')].find(label=>label.childNodes[0]?.textContent==='Available study time')!.querySelector('select')!;expect([...duration.options].map(option=>option.textContent)).toEqual(['15 minutes','30 minutes','45 minutes','60 minutes','90 minutes','2h+']);await select('Course','CSE1400_CO');expect(host.querySelector('.ds-method-summary')?.textContent).toContain('Recommended: Interleaving');expect(build.disabled).toBe(false);await click('Build Study Session');expect(host.querySelectorAll('.ds-path-card').length).toBeGreaterThan(0);expect(host.textContent).toContain('Interleaving: 30 minutes total');for(const card of host.querySelectorAll('.ds-path-card')){expect(card.textContent).toContain('Why this next step');expect(card.querySelector('a')?.getAttribute('href')).toMatch(/^\//);}expect(host.textContent).not.toMatch(/\d+%|predicted grade:|readiness:/);});
it('Customize exposes topic and all methods and preserves a manual override',async()=>{await mount('/study-plan?course=CSE1400_CO');const customize=host.querySelector<HTMLDetailsElement>('.ds-study-customize')!;expect(customize.open).toBe(false);await act(async()=>customize.querySelector('summary')!.click());expect(customize.open).toBe(true);expect(customize.querySelectorAll('input[name="study-method"]')).toHaveLength(6);const active=customize.querySelector<HTMLInputElement>('input[value="active-recall"]')!;await act(async()=>active.click());await settle();expect(active.checked).toBe(true);expect(window.location.search).toContain('method=active-recall');await click('Build Study Session');expect(host.textContent).toContain('Active Recall: 30 minutes total');});
it('keeps an explicit URL method authoritative and resolves structured activity labels',async()=>{await mount('/study-plan?course=CSE1400_CO&minutes=60&method=time-blocking');const linked=host.querySelector<HTMLDetailsElement>('.ds-study-customize')!;expect(linked.open).toBe(true);expect(linked.querySelector<HTMLInputElement>('input[value="time-blocking"]')?.checked).toBe(true);await click('Build Study Session');expect(host.textContent).toContain('Time Blocking: 60 minutes total');expect(host.textContent).toContain('Study the core ideas in Radix and integer data representation');expect(host.textContent).toContain('Focus on Radix conversion and arithmetic');expect(host.textContent).not.toMatch(/topic:CO_T04|CO_ST04/);});
it('canonicalizes an invalid duration and preserves course, topic and explicit unavailable method',async()=>{await mount('/study-plan?course=CSE1400_CO&topic=CO_T11_CACHE&minutes=69&method=52-17');const query=new URLSearchParams(window.location.search);expect(query.get('course')).toBe('CSE1400_CO');expect(query.get('topic')).toBe('CO_T11_CACHE');expect(query.get('minutes')).toBe('30');expect(query.get('method')).toBe('52-17');const duration=[...host.querySelectorAll('label')].find(label=>label.childNodes[0]?.textContent==='Available study time')!.querySelector('select')!;expect(duration.value).toBe('30');const method=host.querySelector<HTMLInputElement>('input[value="52-17"]')!;expect(method.checked).toBe(true);expect(method.disabled).toBe(true);expect(([...host.querySelectorAll('button')].find(button=>button.textContent==='Build Study Session') as HTMLButtonElement).disabled).toBe(true);});
it('keeps a valid duration unchanged and generates with the same effective value',async()=>{const repo=repository(),state=await repo.load(),build=vi.fn(()=>[]);await repo.restore(emptyBackup(),state.data);window.history.replaceState(null,'','/study-plan?course=CSE1400_CO&minutes=90&method=flexible');await act(async()=>root.render(<BrowserRouter><LearningProvider createRepository={()=>repo}><StudyPathPage build={build}/></LearningProvider></BrowserRouter>));await settle();expect(new URLSearchParams(window.location.search).get('minutes')).toBe('90');expect([...host.querySelectorAll('label')].find(label=>label.childNodes[0]?.textContent==='Available study time')!.querySelector('select')!.value).toBe('90');await click('Build Study Session');expect(build).toHaveBeenCalledWith(expect.anything(),{minutes:90,subjectId:'CSE1400_CO',topicId:undefined});});
it('generates an invalid-duration deep link with the canonical effective duration',async()=>{const repo=repository(),state=await repo.load(),build=vi.fn(()=>[]);await repo.restore(emptyBackup(),state.data);window.history.replaceState(null,'','/study-plan?course=CSE1400_CO&minutes=69&method=flexible');await act(async()=>root.render(<BrowserRouter><LearningProvider createRepository={()=>repo}><StudyPathPage build={build}/></LearningProvider></BrowserRouter>));await settle();expect(window.location.search).toContain('minutes=30');await click('Build Study Session');expect(build).toHaveBeenCalledWith(expect.anything(),{minutes:30,subjectId:'CSE1400_CO',topicId:undefined});});
it('replaces invalid duration history without a redirect loop and remains canonical after remount',async()=>{const repo=repository(),state=await repo.load();await repo.restore(emptyBackup(),state.data);window.history.replaceState(null,'','/study-plan?minutes=15');window.history.pushState(null,'','/study-plan?minutes=69');const render=async()=>{await act(async()=>root.render(<BrowserRouter><LearningProvider createRepository={()=>repo}><StudyPathPage/></LearningProvider></BrowserRouter>));await settle();};await render();expect(window.location.search).toBe('?minutes=30');await act(async()=>{const done=new Promise(r=>window.addEventListener('popstate',r,{once:true}));window.history.back();await done;});await settle();expect(window.location.search).toBe('?minutes=15');await act(async()=>{const done=new Promise(r=>window.addEventListener('popstate',r,{once:true}));window.history.forward();await done;});await settle();expect(window.location.search).toBe('?minutes=30');await act(async()=>root.unmount());root=createRoot(host);await render();expect(window.location.search).toBe('?minutes=30');});
it('uses a safe topic label when structured subtopic metadata cannot be resolved',async()=>{const repo=repository();const state=await repo.load();await repo.restore(emptyBackup(),state.data);window.history.replaceState(null,'','/study-plan?course=CSE1400_CO&method=flexible');await act(async()=>root.render(<BrowserRouter><LearningProvider createRepository={()=>repo}><StudyPathPage build={()=>[{id:'session:subtopic:UNKNOWN_SUBTOPIC:review',title:'Focus on UNKNOWN_SUBTOPIC',topicId:'CO_T04_DATA_REP_RADIX_INTEGER',subjectId:'CSE1400_CO',skillIds:[],kind:'learn',minutes:30,durationSource:'Notedra estimate',to:'/co/CO_T04_DATA_REP_RADIX_INTEGER',reason:'UNKNOWN_SUBTOPIC',priority:0,basisSkillId:'topic:CO_T04_DATA_REP_RADIX_INTEGER'}]}/></LearningProvider></BrowserRouter>));await settle();await click('Build Study Session');expect(host.querySelector('.ds-path-card h3')?.textContent).toBe('Study the core ideas in Radix and integer data representation');expect(host.textContent).not.toContain('UNKNOWN_SUBTOPIC');});
it('time and course changes clear stale output and persist in Back/Forward URL navigation',async()=>{await mount('/study-plan');await select('Course','CSE1300_RL');await click('Build Study Session');expect(host.querySelectorAll('.ds-path-card').length).toBeGreaterThan(0);await select('Available study time','15');expect(window.location.search).toContain('minutes=15');expect(host.querySelectorAll('.ds-path-card')).toHaveLength(0);await click('Build Study Session');expect(host.querySelectorAll('.ds-path-card').length).toBeGreaterThan(0);expect([...host.querySelectorAll('.ds-path-card')].every(c=>c.textContent?.includes('Logic'))).toBe(true);await act(async()=>{const done=new Promise(r=>window.addEventListener('popstate',r,{once:true}));window.history.back();await done;});await settle();expect(window.location.search).not.toContain('minutes=15');await act(async()=>{const done=new Promise(r=>window.addEventListener('popstate',r,{once:true}));window.history.forward();await done;});await settle();expect(window.location.search).toContain('minutes=15');});
it('a generation failure stays localized and preserves the selected inputs for retry',async()=>{const repo=repository();const state=await repo.load();await repo.restore(emptyBackup(),state.data);window.history.replaceState(null,'','/study-plan?course=CSE1400_CO&topic=CO_T11_CACHE&minutes=90&method=flexible');await act(async()=>root.render(<BrowserRouter><LearningProvider createRepository={()=>repo}><StudyPathPage build={()=>{throw new Error('temporary planner failure');}}/></LearningProvider></BrowserRouter>));await settle();await click('Build Study Session');expect(host.querySelector('[role=alert]')?.textContent).toContain('Your selections are still available');expect((host.querySelector('option[value="90"]')!.parentElement as HTMLSelectElement).value).toBe('90');expect(window.location.search).toContain('topic=CO_T11_CACHE');expect(host.querySelectorAll('.ds-path-card')).toHaveLength(0);});
it('topic Mistakes displays only that topic; Dashboard links actual recent evidence',async()=>{await mount('/co/CO_T04_DATA_REP_RADIX_INTEGER/mistakes');expect(host.querySelectorAll('.ds-mistake-card')).toHaveLength(2);expect(host.querySelector('h1')?.textContent).toContain('integer');});
it('all filters and actions use native keyboard controls and visible labels',async()=>{await mount();for(const select of host.querySelectorAll('select'))expect(select.closest('label')?.textContent?.length).toBeGreaterThan(3);const first=host.querySelector('select')!;first.focus();expect(document.activeElement).toBe(first);const button=host.querySelector('.ds-mistake-card button') as HTMLButtonElement;button.focus();expect(document.activeElement).toBe(button);expect(host.querySelectorAll('a[href="#"]')).toHaveLength(0);});
it('a dashboard summary appears only for real recent wrong evidence',async()=>{await mount('/dashboard');expect(host.querySelector('[aria-label="Recent practice evidence"]')?.textContent).toContain('3 recent mistakes');expect(host.querySelector('[aria-label="Recent practice evidence"] a')?.getAttribute('href')).toBe('/mistakes');});
it('review: repeated-pattern summary respects the selected course',async()=>{await mount('/mistakes',[record('co','enrich-carry-overflow',text('1,1'),1),record('rl1','enrich-implication-directions',text('1,1,1'),2),record('rl2','enrich-implication-directions',text('1,1,1'),1)]);await select('Course','CSE1400_CO');expect(host.textContent).toContain('0 skills with repeated exact answer patterns');});
