import {describe,expect,it} from 'vitest';
import {allExercises} from '../src/practice/catalog';
import {deriveEvidence,skills} from '../src/adaptive/evidence';
import {priorityFor,recommend,TIME_BUDGETS} from '../src/adaptive/engine';
import {CLOCK,record,text,choice} from './helpers/adaptive';
const wrong=(id='a',age=1)=>record(id,'enrich-carry-overflow',text('1,1'),age);
const evidence=(records= [wrong()])=>deriveEvidence(records,[],CLOCK);
function wrongFor(skill:string,id:string,age=1){const e=allExercises.find(e=>e.skillId===skill);if(!e)throw new Error(skill);const answer=e.task.kind==='ip-fixed'?choice(e.task.options.find(o=>e.reference.kind==='choice'&&!e.reference.value.includes(o.id))!.id):text(e.task.kind==='enrichment-exact'?'99,99':e.task.kind==='truth'?'0,0,0,0':'0');return record(id,e.id,answer,age);}
describe('Deterministic adaptive study product heuristics',()=>{
 it('no evidence means no inferred adaptive queue',()=>expect(recommend(evidence([]),{minutes:20})).toEqual([]));
 it('same records and injected time give exact output independent of input order',()=>{const a=[wrong('z'),wrong('a'),record('rl','enrich-implication-directions',text('1,1,1'),2)];expect(recommend(evidence(a),{minutes:20})).toEqual(recommend(evidence(a.reverse()),{minutes:20}));});
 it.each([7,30,90])('recency has exact inclusive %i-day boundaries',days=>{const group=evidence([wrong('a',days)]).groups[0];expect(priorityFor(group,CLOCK)).toBeGreaterThan(priorityFor(group,CLOCK+1));});
 it('recent repeated wrongs outrank a single old mistake',()=>{const recent=evidence([wrong('a',2),wrong('b',1)]).groups[0],old=evidence([wrong('old',120)]).groups[0];expect(priorityFor(recent,CLOCK)).toBeGreaterThan(priorityFor(old,CLOCK));});
 it('later success reduces priority without erasing underlying mistakes',()=>{const before=evidence([wrong('a',2)]),after=evidence([wrong('a',2),record('ok','enrich-carry-overflow',text('1,0'),1)]);expect(priorityFor(after.groups[0],CLOCK)).toBeLessThan(priorityFor(before.groups[0],CLOCK));expect(after.mistakes).toHaveLength(1);expect(recommend(after,{minutes:20}).every(a=>a.kind!=='retry')).toBe(true);expect(recommend(after,{minutes:20})[0].reason).toContain('reduces');});
 it('repeated familiar retries shift to explanation instead of an indefinite retry loop',()=>{const path=recommend(evidence([wrong('a',3),wrong('b',2),wrong('c',1)]),{minutes:20});expect(path.some(a=>a.kind==='retry')).toBe(false);expect(path[0].kind).toBe('learn');});
 it('review only reduces workflow urgency, never counts as a correct result',()=>{const before=evidence(),reviewed=deriveEvidence([wrong()],[{attemptId:'a',reviewedAt:new Date(CLOCK).toISOString(),revision:1}],CLOCK);expect(priorityFor(before.groups[0],CLOCK)-priorityFor(reviewed.groups[0],CLOCK)).toBe(5);expect(reviewed.groups[0].laterSuccesses).toBe(0);});
 it('recommends an actual prerequisite first only if both skills have exact recent wrong evidence',()=>{const records=[wrongFor('CO_SK10_02_MEMORY_BITS','pre'),wrongFor('CO_SK11_01_CACHE_BITS','down1',2),wrongFor('CO_SK11_01_CACHE_BITS','down2',1)];const e=evidence(records);expect(e.groups).toHaveLength(2);const path=recommend(e,{minutes:20,topicId:'CO_T11_CACHE'});expect(path[0].basisSkillId).toBe('CO_SK10_02_MEMORY_BITS');expect(path[0].reason).toContain('canonical prerequisite');expect(skills.get('CO_SK11_01_CACHE_BITS')!.prerequisites).toContain(path[0].basisSkillId);});
 it('does not invent a prerequisite error without its own evidence',()=>{const path=recommend(evidence([wrongFor('CO_SK11_01_CACHE_BITS','d1',2),wrongFor('CO_SK11_01_CACHE_BITS','d2',1)]),{minutes:20});expect(path.every(a=>a.basisSkillId==='CO_SK11_01_CACHE_BITS')).toBe(true);expect(path.every(a=>!a.reason.includes('canonical prerequisite'))).toBe(true);});
 it('does not use parent-topic membership as a prerequisite edge',()=>{const path=recommend(evidence([wrong('a'),wrong('b'),wrongFor('CO_SK11_01_CACHE_BITS','cache')]),{minutes:20});expect(path.every(a=>!a.reason.includes('canonical prerequisite'))).toBe(true);});
 it.each(TIME_BUDGETS)('fits the %i-minute budget and emits only explained direct actions',minutes=>{const path=recommend(evidence([wrong('a'),record('ip','ip-pass-value',choice('changed-both'),1)]),{minutes});expect(path.reduce((n,a)=>n+a.minutes,0)).toBeLessThanOrEqual(minutes);for(const a of path){expect(a.reason.length).toBeGreaterThan(20);expect(a.to.startsWith('/')).toBe(true);expect(a.durationSource).toMatch(/estimate|Authored/);}});
 it('time budget changes available authored coding reinforcement without grading it',()=>{const e=allExercises.find(e=>e.id==='ds.practice.ip-equality')!;if(e.task.kind!=='ip-fixed')throw new Error();const wrongId=e.task.options.find(o=>o.id==='pattern')!.id;const data=evidence([record('ip',e.id,choice(wrongId),1)]);const short=recommend(data,{minutes:10}),long=recommend(data,{minutes:60});expect(short.some(a=>a.kind==='coding')).toBe(false);expect(long.some(a=>a.kind==='coding')).toBe(true);expect(long.find(a=>a.kind==='coding')!.reason).toContain('unscored');});
 it('uses distinct skill groups first and caps queue, activity duplication and near-identical actions',()=>{const records=[wrong('a'),record('rl','enrich-implication-directions',text('1,1,1'),1),wrongFor('CO_SK11_01_CACHE_BITS','cache')];const path=recommend(evidence(records),{minutes:45});expect(path.length).toBeLessThanOrEqual(4);expect(new Set(path.map(a=>a.to)).size).toBe(path.length);for(const skill of new Set(path.map(a=>a.basisSkillId)))expect(path.filter(a=>a.basisSkillId===skill).length).toBeLessThanOrEqual(2);for(const kind of new Set(path.map(a=>a.kind)))expect(path.filter(a=>a.kind===kind).length).toBeLessThanOrEqual(2);expect(new Set(path.map(a=>a.basisSkillId)).size).toBe(3);});
 it('course context does not leak another course into suggestions',()=>{const e=evidence([wrong(),record('rl','enrich-implication-directions',text('1,1,1'),1)]);expect(recommend(e,{minutes:20,subjectId:'CSE1300_RL'}).every(a=>a.subjectId==='CSE1300_RL')).toBe(true);});
 it('no mastery, readiness, grade predictions, mutable storage or scheduling fields',()=>{const path=recommend(evidence(),{minutes:20});expect(JSON.stringify(path)).not.toMatch(/"(?:mastery|readiness|predictedGrade|probability|correct|earned|percentage)"/);expect(()=>recommend(evidence(),{minutes:0})).toThrow('Unsupported');});
});
