import {describe,expect,it,vi} from 'vitest';
import {AccountSession,type AuthAdapter,type AccountUser} from '../src/cloud/auth';
import {cloudConfig} from '../src/cloud/config';
const A={id:'11111111-1111-4111-8111-111111111111',email:'a@example.invalid'},B={id:'22222222-2222-4222-8222-222222222222',email:'b@example.invalid'};
function setup(){let callback:(u:AccountUser|null)=>void=()=>{};const adapter:AuthAdapter={session:vi.fn(async()=>null),subscribe:vi.fn(fn=>{callback=fn;return vi.fn();}),signIn:vi.fn(async()=>{callback(A);}),signUp:vi.fn(async()=>({verificationRequired:true})),signOut:vi.fn(async()=>{callback(null);})};return {adapter,auth:new AccountSession(adapter),emit:(user:AccountUser|null)=>callback(user)};}
describe('auth lifecycle independent of Supabase',()=>{
  it('self-review: subscription initialization failure reports local fallback instead of rejecting unhandled',async()=>{const {auth,adapter}=setup();vi.mocked(adapter.subscribe).mockImplementation(()=>{throw Error('storage denied');});await expect(auth.start()).resolves.toBeUndefined();expect(auth.snapshot()).toMatchObject({phase:'error',user:null});auth.close();});
  it('starts loading with no visible identity and settles logged out',async()=>{const {auth}=setup();expect(auth.snapshot()).toMatchObject({phase:'loading',user:null});await auth.start();expect(auth.snapshot()).toMatchObject({phase:'anonymous',user:null});auth.close();});
  it('restores the known account only after session resolution',async()=>{const {auth,adapter}=setup();vi.mocked(adapter.session).mockResolvedValue(A);await auth.start();expect(auth.snapshot()).toMatchObject({phase:'signed-in',user:A});auth.close();});
  it('signs in through the provider and never persists passwords itself',async()=>{const {auth,adapter}=setup();await auth.start();await auth.signIn('a@example.invalid','transient');expect(adapter.signIn).toHaveBeenCalledWith('a@example.invalid','transient');expect(auth.snapshot().user).toEqual(A);expect(JSON.stringify(auth.snapshot())).not.toContain('transient');auth.close();});
  it('reports email verification without fabricating a session',async()=>{const {auth}=setup();await auth.start();expect(await auth.signUp('a@example.invalid','transient')).toEqual({verificationRequired:true});expect(auth.snapshot().user).toBeNull();auth.close();});
  it('signup may legitimately produce a provider session when auto-confirm is enabled',async()=>{const {auth,adapter,emit}=setup();await auth.start();vi.mocked(adapter.signUp).mockImplementation(async()=>{emit(A);return {verificationRequired:false};});expect((await auth.signUp('a','password')).verificationRequired).toBe(false);expect(auth.snapshot().user).toEqual(A);auth.close();});
  it('sign-out hides account state and cancels in-flight sync immediately',async()=>{const {auth}=setup();await auth.start();await auth.signIn('a','password');const old=auth.signal;await auth.signOut();expect(old.aborted).toBe(true);expect(auth.snapshot().user).toBeNull();expect(auth.snapshot().message).toContain('preserved');auth.close();});
  it('does not let an older session lookup override a newer sign-in',async()=>{const {auth,adapter,emit}=setup();let resolve!:(user:AccountUser|null)=>void;vi.mocked(adapter.session).mockImplementation(()=>new Promise(r=>{resolve=r;}));const start=auth.start();emit(B);resolve(A);await start;expect(auth.snapshot().user).toEqual(B);auth.close();});
  it('switches account with a new cancellation epoch and no A data in B state',async()=>{const {auth,emit}=setup();await auth.start();emit(A);const old=auth.signal,epoch=auth.snapshot().epoch;emit(B);expect(old.aborted).toBe(true);expect(auth.snapshot().epoch).toBeGreaterThan(epoch);expect(auth.snapshot().user).toEqual(B);auth.close();});
  it('token refresh invalidates old request epochs without changing account identity',async()=>{const {auth,emit}=setup();await auth.start();emit(A);const old=auth.signal;emit(A);expect(old.aborted).toBe(true);expect(auth.snapshot().user).toEqual(A);auth.close();});
  it('expired session transitions to anonymous and aborts authenticated sync',async()=>{const {auth,emit}=setup();await auth.start();emit(A);const old=auth.signal;emit(null);expect(old.aborted).toBe(true);expect(auth.snapshot().user).toBeNull();auth.close();});
  it('late auth events after sign-out do not resurrect hidden account data',async()=>{const {auth,emit}=setup();await auth.start();emit(A);await auth.signOut();emit(A);expect(auth.snapshot().user).toBeNull();auth.close();});
  it('failed sign-out is honest and keeps account data hidden',async()=>{const {auth,adapter,emit}=setup();await auth.start();emit(A);vi.mocked(adapter.signOut).mockRejectedValue(Error('private-provider-details'));await expect(auth.signOut()).rejects.toThrow('could not be confirmed');emit(A);expect(auth.snapshot()).toMatchObject({phase:'error',user:null});expect(auth.snapshot().message).not.toContain('private-provider');auth.close();});
  it('auth network errors do not leak provider internals',async()=>{const {auth,adapter}=setup();vi.mocked(adapter.session).mockRejectedValue(Error('raw detail'));await auth.start();expect(auth.snapshot()).toMatchObject({phase:'error',user:null});vi.mocked(adapter.signIn).mockRejectedValue(Error('raw detail'));await expect(auth.signIn('a','b')).rejects.toThrow('Sign-in failed');vi.mocked(adapter.signUp).mockRejectedValue(Error('raw detail'));await expect(auth.signUp('a','b')).rejects.toThrow('Account creation failed');auth.close();});
  it('close cancels and prevents stale initialization or subscription results',async()=>{const {auth,adapter,emit}=setup();let resolve!:(user:AccountUser|null)=>void;vi.mocked(adapter.session).mockImplementation(()=>new Promise(r=>{resolve=r;}));const start=auth.start();auth.close();resolve(A);emit(A);await start;expect(auth.snapshot().user).toBeNull();expect(auth.signal.aborted).toBe(true);});
});
describe('browser environment allowlist',()=>{
  const key='sb_publishable_'+'a'.repeat(32);
  it('missing environment gives fully local mode',()=>expect(cloudConfig(undefined,undefined).status).toBe('unavailable'));
  it('supports HTTPS project origins and publishable keys',()=>expect(cloudConfig('https://project.supabase.co',key).status).toBe('configured'));
  it('allows isolated local Supabase HTTP',()=>expect(cloudConfig('http://127.0.0.1:54321',key).status).toBe('configured'));
  it.each(['http://project.supabase.co','javascript:alert(1)','https://user:pass@project.supabase.co','https://project.supabase.co/path','https://project.supabase.co?key=x','https://project.supabase.co/#hash'])('rejects unsafe project URL %s',url=>expect(cloudConfig(url,key).status).toBe('invalid'));
  it.each([undefined,'','sb_'+'secret_'+'x'.repeat(32),'admin-key','eyJbad.bad.bad'])('rejects missing, privileged or malformed keys %#',value=>expect(cloudConfig('https://project.supabase.co',value).status).toBe('invalid'));
  it.each(['anon','service_role','authenticated'])('accepts only browser-safe legacy JWT role %s',role=>{const token=[btoa(JSON.stringify({alg:'HS256',typ:'JWT'})),btoa(JSON.stringify({role})),btoa('signature')].map(s=>s.replaceAll('=','')).join('.');expect(cloudConfig('https://project.supabase.co',token).status).toBe(role==='anon'?'configured':'invalid');});
});
