// @vitest-environment jsdom
import {act} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {BrowserRouter} from 'react-router';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {AccountPage} from '../src/accounts/AccountPage';
import {AccountContext,anonymousState,type AccountContextValue} from '../src/accounts/context';
import {AccountSession,type AuthAdapter} from '../src/cloud/auth';
import {AccountRoot} from '../src/accounts/AccountRoot';
import {AppRoutes} from '../src/App';
import {IDBFactory} from 'fake-indexeddb';
let host:HTMLDivElement,root:Root;
beforeEach(()=>{Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true,indexedDB:new IDBFactory()});vi.spyOn(window,'scrollTo').mockImplementation(()=>{});host=document.createElement('div');document.body.append(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();});
const defaultValue:AccountContextValue={config:{status:'unavailable',message:'Cloud sync is not configured.'},auth:null,state:anonymousState,syncStatus:'Local only',syncMessage:'',sync:null,adopt:null};
async function mount(value:Partial<AccountContextValue>={}){await act(async()=>root.render(<BrowserRouter><AccountContext.Provider value={{...defaultValue,...value}}><AccountPage/></AccountContext.Provider></BrowserRouter>));}
async function click(label:string){const b=[...host.querySelectorAll('button')].find(b=>b.textContent===label);expect(b).toBeDefined();await act(async()=>b!.click());}
it('explicit restore recovery action needs consent and never replaces the backup link',async()=>{
  const reconcile=vi.fn(async()=>{});await mount({config:{status:'configured',url:'https://project.supabase.co',key:'public'},state:{...anonymousState,phase:'signed-in',user:{id:'11111111-1111-4111-8111-111111111111',email:'a@example.invalid'}},syncStatus:'Conflict requires attention',reconcile});
  const b=[...host.querySelectorAll('button')].find(b=>b.textContent==='Compare restored history')!;expect(b.disabled).toBe(true);await act(async()=>host.querySelector<HTMLInputElement>('input[type=checkbox]')!.click());await click('Compare restored history');expect(reconcile).toHaveBeenCalledOnce();expect(host.textContent).toContain('Export student backup');
});
it('without configuration explains account access is unavailable, exposes backups and no broken sign-in controls',async()=>{await mount();expect(host.textContent).toContain('Cloud sync is not configured');expect(host.querySelector('form')).toBeNull();expect(host.textContent).toContain('Data & Privacy');expect(host.textContent).toContain('Export student backup');expect(host.textContent).toContain('Study app access requires account support');});
it('final-review: configuration guidance is not repeated beside the identical status',async()=>{await mount({syncMessage:'Cloud sync is not configured.'});expect(host.textContent!.split('Cloud sync is not configured.')).toHaveLength(2);});
it('renders pending, offline, sync error and conflict as readable text',async()=>{for(const status of ['Pending','Offline','Sync error','Conflict requires attention']){await mount({syncStatus:status,syncMessage:'Local data is safe.'});expect(host.querySelector('[role=status]')!.textContent).toContain(status);expect(host.textContent).toContain('Local data is safe');}});
it('signup/sign-in mode uses accessible labels and correct password autocomplete',async()=>{await mount({config:{status:'configured',url:'https://project.supabase.co',key:'public'}});expect(host.querySelector('input[type=email]')?.closest('label')?.textContent).toContain('Email');expect(host.querySelector('input[type=password]')?.getAttribute('autocomplete')).toBe('current-password');await click('Create an account instead');expect(host.querySelector('input[type=password]')?.getAttribute('autocomplete')).toBe('new-password');});
it('copying anonymous data requires an explicit account-specific choice',async()=>{const adopt=vi.fn(async()=>{}),sync=vi.fn(async()=>{});await mount({config:{status:'configured',url:'https://project.supabase.co',key:'public'},state:{...anonymousState,phase:'signed-in',user:{id:'11111111-1111-4111-8111-111111111111',email:'a@example.invalid'}},adopt,sync});const copy=[...host.querySelectorAll('button')].find(b=>b.textContent==='Copy anonymous history')!;expect(copy.disabled).toBe(true);await act(async()=>host.querySelector<HTMLInputElement>('input[type=checkbox]')!.click());expect(copy.disabled).toBe(false);await click('Copy anonymous history');expect(adopt).toHaveBeenCalledOnce();expect(host.querySelector<HTMLInputElement>('input[type=checkbox]')!.checked).toBe(false);});
it('sync failure gets focused accessible feedback and never a false success',async()=>{await mount({config:{status:'configured',url:'https://project.supabase.co',key:'public'},state:{...anonymousState,phase:'signed-in',user:{id:'11111111-1111-4111-8111-111111111111',email:'a@example.invalid'}},sync:async()=>{throw Error('Failed local commit');}});await click('Sync now');expect(host.querySelector('[role=alert]')?.textContent).toContain('Failed local commit');expect(document.activeElement).toBe(host.querySelector('[role=alert]'));expect(host.textContent).not.toContain('Synced');});
it('sign-out uses the actual auth controller and preserves the local-first explanation',async()=>{const adapter:AuthAdapter={session:async()=>null,subscribe:()=>()=>{},signIn:async()=>{},signUp:async()=>({verificationRequired:true}),signOut:vi.fn(async()=>{})};const auth=new AccountSession(adapter);await mount({config:{status:'configured',url:'https://project.supabase.co',key:'public'},auth,state:{...anonymousState,phase:'signed-in',user:{id:'11111111-1111-4111-8111-111111111111',email:'a@example.invalid'}}});await click('Sign out');expect(adapter.signOut).toHaveBeenCalledOnce();expect(auth.snapshot().user).toBeNull();auth.close();});
it.each(['/co','/rl','/ip'])('private app route %s redirects to the auth entry with missing environment',async path=>{window.history.replaceState(null,'',path);await act(async()=>root.render(<BrowserRouter><AccountRoot><AppRoutes/></AccountRoot></BrowserRouter>));for(let i=0;i<30&&window.location.pathname!=="/account";i++)await act(async()=>{await new Promise(r=>setTimeout(r,5));});expect(window.location.pathname).toBe('/account');expect(host.querySelector('h1')?.textContent).toBe('Account & Settings');expect(host.textContent).not.toContain('Page not found');});
it.each(['/','/account','/privacy','/terms'])('public route %s remains usable with missing environment',async path=>{window.history.replaceState(null,'',path);await act(async()=>root.render(<BrowserRouter><AccountRoot><AppRoutes/></AccountRoot></BrowserRouter>));for(let i=0;i<30&&!host.querySelector('h1');i++)await act(async()=>{await new Promise(r=>setTimeout(r,5));});expect(host.querySelector('h1')).not.toBeNull();expect(host.textContent).not.toContain('Page not found');});
