import {describe,it,expect} from 'vitest';
import {loadCO,validateCO,validateCOFiles,checkCOLocks,readCO,coCapabilities,coBuildGuard} from '../scripts/co-content';
import {topicStudy} from '../src/topic-study/content';
import {gradeCOResponse,validateCOResponse} from '../src/co/grading';
import type {COExercise} from '../src/co/types';
import {canonical} from '../scripts/practice-catalog';
const data=loadCO();
describe('complete CO authored content',()=>{
 it('14 lessons, 32 subtopics, 46 deliberate skill scopes, 79 cards, all fingerprints and source precision pass',()=>{expect(()=>validateCOFiles()).not.toThrow();const capabilities=coCapabilities(data,topicStudy);expect(capabilities).toHaveLength(14);expect(capabilities.every(c=>c.lessonId&&c.cardCount)).toBe(true);expect(capabilities.reduce((n,c)=>n+c.cardCount,0)).toBe(79);expect(data.coverage).toHaveLength(46);expect(data.exercises).toHaveLength(28);expect(data.topics.flatMap(t=>t.guided)).toHaveLength(17);});
 it.each(['missing-topic','foreign-skill','fake-subtopic','unknown-source','precision','duplicate-card','empty-skill','extra-score','open-score','assessment-source','broad-source','wrong-reference','missing-class','unlinked-class','wrong-tool'] as const)('rejects %s',kind=>{
  const d=structuredClone(data),p=structuredClone(topicStudy),b=d.topics[0].lesson.blocks[1];
  if(kind==='missing-topic')d.topics.pop();if(kind==='foreign-skill')b.skillIds=['RL_SK01_01_EVAL'];if(kind==='fake-subtopic')b.subtopicIds=['CO_ST404'];if(kind==='unknown-source')b.sourceIds=['missing'];if(kind==='precision')p.sources.find(s=>s.id===b.sourceIds[0])!.precision='EXACT_PAGE';if(kind==='duplicate-card')d.topics[0].cards[1].id=d.topics[0].cards[0].id;if(kind==='empty-skill')d.topics[0].cards.forEach(c=>c.skillIds=[]);if(kind==='extra-score')Object.assign(d.topics[0].cards[0],{mastery:1});if(kind==='open-score')Object.assign(d.topics[0].guided[0],{earned:1});if(kind==='assessment-source')Object.assign(d.exercises[0].source,{kind:'ASSESSMENT',can_generate_variants:true});if(kind==='broad-source')Object.assign(d.exercises[0],{assessmentMapping:'TOPIC_LEVEL_BROAD'});if(kind==='wrong-reference')d.exercises[0].reference={kind:'text',value:'invalid'};if(kind==='missing-class')d.coverage.pop();if(kind==='unlinked-class')d.coverage.find(c=>c.category==='A')!.exerciseIds=[];if(kind==='wrong-tool')d.tools[0].skillIds=['CO_SK14_01_VM_TRANSLATE'];
  expect(()=>validateCO(d,p)).toThrow('CO content:');
 });
 it.each(['lesson','block','card','guided','exercise','tool','classification'] as const)('published %s cannot change silently',kind=>{const d=structuredClone(data);if(kind==='lesson')d.topics[0].lesson.version='2';if(kind==='block')d.topics[0].lesson.blocks[0].paragraphs[0]+=' alteration';if(kind==='card')d.topics[0].cards[0].answer+=' alteration';if(kind==='guided')d.topics[0].guided[0].rubric[0]+=' alteration';if(kind==='exercise')d.exercises[0].prompt+=' alteration';if(kind==='tool')d.tools[0].assumptions+=' alteration';if(kind==='classification')d.coverage[0].reason+=' alteration';expect(()=>checkCOLocks(d,readCO('content-lock.json'))).toThrow('published version changed');});
 it('capabilities preserve canonical order and use factual counts only',()=>{const c=coCapabilities(data,topicStudy);expect(c.map(t=>t.topicId)).toEqual(topicStudy.topics.filter(t=>t.subjectId==='CSE1400_CO').map(t=>t.id));expect(canonical(c)).not.toMatch(/mastery|percentage|readiness|completed/);});
 it('open rubrics are not exercise definitions and get no numeric score',()=>{for(const g of data.topics.flatMap(t=>t.guided)){expect(data.exercises.some(e=>e.id===g.id)).toBe(false);expect(g).not.toHaveProperty('grader');}const open={...data.exercises[0],task:{kind:'open'},grader:{id:'open',version:'1'}} as unknown as COExercise;expect(gradeCOResponse(open,{kind:'text',value:'anything'})).toMatchObject({status:'NOT_AUTOGRADABLE'});expect(gradeCOResponse(open,{kind:'text',value:'anything'})).not.toHaveProperty('earned');});
 it('direct Vite guard calls the same mandatory validator',()=>{const guard=coBuildGuard(()=>{throw new Error('untrusted course');});const hook=guard.buildStart as ()=>void;expect(hook).toThrow('untrusted course');});
});
describe('fixed CO grading contracts',()=>{
 it.each(['','   ','1 0','0x01','+1','1e2','NaN','1'.repeat(65)])('rejects incomplete or malformed binary %s',value=>{expect(validateCOResponse(data.exercises[0].task,{kind:'text',value}).status).not.toBe('VALID');});
 it('normalizes exact decimals and case without relaxing width or changing references',()=>{const e=data.exercises.find(e=>e.id.endsWith('fixed-signed'))!;expect(gradeCOResponse(e,{kind:'text',value:' -001.5000 '})).toMatchObject({correct:true});const h=data.exercises.find(e=>e.id.endsWith('eax-read'))!;expect(gradeCOResponse(h,{kind:'text',value:'000000000000ab12'})).toMatchObject({correct:true});expect(gradeCOResponse(h,{kind:'text',value:'AB12'})).toMatchObject({status:'INVALID'});expect(h.reference.value).toBe('000000000000AB12');});
 it('well-formed wrong answers are incorrect, invalid references are technical errors',()=>{expect(gradeCOResponse(data.exercises[0],{kind:'text',value:'0000'})).toMatchObject({status:'GRADED',correct:false,earned:0});expect(gradeCOResponse({...data.exercises[0],reference:{kind:'text',value:'x'}},{kind:'text',value:'0011'})).toMatchObject({status:'ERROR'});});
});
