import {describe,it,expect} from 'vitest';
import {IDBFactory} from 'fake-indexeddb';
import {catalog,allExercises,versionBinding} from '../src/practice/catalog';
import {PracticeService,feedbackFor,resolveAttempt} from '../src/practice/service';
import {repository} from './helpers/learning';
import {evidencePolicy} from '../src/learning/contracts';
import locks from '../src/practice/catalog-lock.json';
import grader from '../src/practice/grader-lock.json';
describe('CO reuses immutable shared Practice',()=>{
 it('keeps the original six bindings byte-for-byte and retains the historical CO additions plus eight Assembly traces',()=>{expect(catalog).toHaveLength(6);expect(allExercises.filter(e=>e.task.kind!=='curriculum'&&!e.id.startsWith('ds.practice.advanced-')&&!e.id.startsWith('ds.practice.p7-')&&!e.id.startsWith('ds.practice.interactive-')&&e.task.kind!=='rl-exact'&&e.task.kind!=='enrichment-exact'&&e.task.kind!=='ip-fixed')).toHaveLength(42);for(const e of catalog)expect(versionBinding(e)).toBe(`${e.version}:sha256:${(locks as Record<string,string>)[`${e.id}@${e.version}`]}:grader:${grader.sha256}`);});
 it.each(['boolean-rows','cache-lru-trace','pipeline-total','amdahl-speedup','vm-translate'])('%s start/save/reload/submit/idempotency/conflict/retry uses StudentRepository',async slug=>{const f=new IDBFactory(),repo=repository(f),s=new PracticeService(repo);const {data}=await repo.load();const e=allExercises.find(e=>e.id===`ds.practice.co-${slug}`)!;let state=await s.start(e.id,'co',data);state=await s.save(state.data.attempts[0],e.reference,data);const draft=(await repository(f).load()).data.attempts[0];state=await s.submit(draft,e.reference,'op',data);const submitted=state.data.attempts[0];expect(feedbackFor(submitted)).toMatchObject({status:'GRADED',correct:true});expect(await s.submit(draft,e.reference,'op',data)).toEqual(state);const conflict={kind:'text',value:slug==='boolean-rows'?'0000':slug==='cache-lru-trace'?'11111':slug==='vm-translate'?'0000':'0'} as const;await expect(s.submit(draft,conflict,'op',data)).rejects.toMatchObject({code:'CONFLICT'});expect(feedbackFor((await repository(f).load()).data.attempts[0])).toEqual(feedbackFor(submitted));expect(evidencePolicy(submitted).eligible).toBe(false);const retry=await s.retry(submitted,'co-retry',data);expect(retry.data.attempts[0]).toEqual(submitted);expect(retry.data.attempts[1].attemptId).toBe('co-retry');expect(resolveAttempt({...submitted,exercise:{...submitted.exercise!,version:'stale'}}).status).toBe('UNAVAILABLE');});
});
