import {describe,it,expect} from 'vitest';
import {loadCO} from '../scripts/co-content';
import {gradeCOResponse} from '../src/co/grading';
const data=loadCO();const blocks=data.topics.flatMap(t=>t.lesson.blocks);
const prose=(slug:string)=>{const b=blocks.find(b=>b.id==='ds.block.co.'+slug)!;expect(b).toBeDefined();return b.paragraphs.join('\n');};
// Reference values are hand-derived here, not generated by the calculators or the grader.
const references=[
 ['boolean-rows','0011','A(B+¬B)=A in rows 00,01,10,11'],
 ['gray-population','01100110','C across BC=00,01,11,10 is 0110 for each A'],
 ['cmos-nand','0','both series nMOS on, both parallel pMOS off'],
 ['full-adder','10','1+0+1=2; carry then sum'],
 ['hex-addition','44','43+25=68=4×16+4'],
 ['signed-five','11010','32−6=26=16+8+2'],
 ['overflow-four','1','6+3=9 exceeds signed maximum 7'],
 ['bcd-thirty-eight','00111000','decimal digits 3 and 8 encoded separately'],
 ['little-byte','B2','low byte at the lowest byte address'],
 ['fixed-signed','-1.5','(26−32)/4'],
 ['custom-float-encode','0101101','13=1.101×2³; E=3+2=5, F=5'],
 ['custom-float-maximum','60','(1+7/8)×2^(7−2)'],
 ['eax-read','000000000000AB12','32-bit destination clears the upper half'],
 ['isa-capacity','64','20−2×ceil(log2(10))−6=6; 2^6 codes'],
 ['micro-transfer','2','Y=7; Z=7−5=2; R1=Z'],
 ['control-width','8','ceil(log2(8))+ceil(log2(4))+ceil(log2(8))'],
 ['address-alias','53','0x42 OR bit0 OR bit4 = 0x53'],
 ['interrupt-completion','12','entry1+service4+entry1+service6'],
 ['memory-chips','8','(4096/1024)×(16/8)'],
 ['bank-index','3','27=3×8+3'],
 ['cache-tag-width','9','16−log2(16)−log2(8)'],
 ['cache-lru-trace','00100','empty → [0] → [0,1] → [1,0] → [0,2] → [2,1]'],
 ['pipeline-total','12','5+6−1+2'],
 ['pipeline-load-use','7','load M4 produces for consumer X5, then M6 W7'],
 ['amdahl-speedup','2.5','1/(.2+.8/4)'],
 ['amdahl-inverse','0.25','(1/2−1/3)/(1−1/3)'],
 ['vm-table-size','4096','2^20 / 1024 entries × 4 bytes'],
 ['vm-translate','15B3','frame0x15 × 256 + offset0xB3'],
] as const;
describe('independent authored CO reference checks',()=>{
 it.each(references)('%s reference %s — %s',(slug,expected)=>{const e=data.exercises.find(e=>e.id===`ds.practice.co-${slug}`)!;expect(e.reference).toEqual({kind:'text',value:expected});expect(gradeCOResponse(e,{kind:'text',value:expected})).toMatchObject({status:'GRADED',correct:true});});
 it('every exact exercise has an independent reference case',()=>{expect(references.map(r=>'ds.practice.co-'+r[0]).sort()).toEqual(data.exercises.map(e=>e.id).sort());});
 it('truth tables, Gray population, wrap and don’t-care alternatives preserve specified rows',()=>{
  expect(blocks.find(b=>b.id.endsWith('t02.evaluate'))!.table!.rows).toEqual([['0','0','0'],['0','1','0'],['1','0','1'],['1','1','1']]);
  const map=blocks.find(b=>b.id.endsWith('t02.populate'))!.table!;expect(map.headers).toEqual(['A \\ BC','00','01','11','10']);expect(map.rows).toEqual([['0','0','1','1','0'],['1','0','1','1','0']]);
  const gray=[0,1,3,2];for(let i=0;i<4;i++){const diff=gray[i]^gray[(i+1)%4];expect([1,2]).toContain(diff);}expect(gray[0]^gray[2]).toBe(3); // opposite columns differ in two bits
  // Opposite row AND next column changes two variables: a diagonal is never adjacent.
  expect((0^1)+(gray[0]^gray[1])).toBe(2);
  expect(prose('t02.groups')).toContain('Diagonal cells are not adjacent');expect(prose('t02.groups')).toContain('columns 00 and 10');
  for(const row of [0,1,2,3,4,6]){const c=row%2;const notAC=row<4?c:0;expect(c).toBe([1,3].includes(row)?1:0);expect(notAC).toBe(c);}expect(prose('t02.dont-care')).toContain('NOT A·C');expect(prose('t02.dont-care')).toContain('C has fewer literals');
 });
 it('ideal circuits, MUX and full-adder examples check all input assignments without invented geometry',()=>{
  for(const a of [0,1])for(const b of [0,1]){const low=a===1&&b===1,high=a===0||b===0;expect(low).not.toBe(high);for(const carryIn of [0,1]){const sum=a^b^carryIn;const carry=(a&b)|(a&carryIn)|(b&carryIn);expect(sum+2*carry).toBe(a+b+carryIn);}for(const select of [0,1])expect((1-select)*a+select*b).toBe(select===0?a:b);}
  expect(prose('t03.blocks')).toContain('sum=0 and carry=1');expect(prose('t03.design')).toContain('series nMOS');expect(prose('t03.cmos')).toContain('At A=0');
 });
 it('fixed and explicitly non-IEEE floating worked endpoints and precision are independently correct',()=>{
  expect((26-32)/4).toBe(-1.5);expect([-16/4,15/4]).toEqual([-4,3.75]);expect(prose('t05.fixed')).toContain('−1.5');expect(prose('t05.fixed')).toContain('3.75');expect((1+3/8)*4).toBe(5.5);expect(prose('t05.float-example')).toContain('0 100 011');expect((1+7/8)*32).toBe(60);expect(prose('t05.range')).toContain('0.25');expect(prose('t05.range')).toContain('0.5');
 });
 it('Assembly addressing, width masks and stack frame values match independent integer arithmetic',()=>{
  const original=0x1122334455667788n;expect(((original&~255n)|0xaan).toString(16)).toBe('11223344556677aa');expect(((original&~65535n)|0xbbbbn).toString(16)).toBe('112233445566bbbb');expect(0x12345678n&0xffffffffn).toBe(305419896n);expect(4096-8).toBe(4088);expect([4096-8,4096-16,4096-24].map(n=>n.toString(16))).toEqual(['ff8','ff0','fe8']);expect(prose('t06.widths')).toContain('0x0000000012345678');expect(prose('t06.frame')).toContain('0x0FE8');expect(prose('t06.operands')).toContain('4088');
 });
 it('ISA and control field examples count codes, including no-action, rather than maximum codes',()=>{
  expect(20-2*4-6).toBe(6);expect(2**6).toBe(64);expect(prose('t07.budget')).toContain('six are unused');expect(16-2*3).toBe(10);expect(prose('t07.design')).toContain('remaining ten bits');expect(3+2+2).toBe(7);expect(7+3+4).toBe(14);expect(prose('t08.encoding')).toContain('3+2+2 = 7');expect(prose('t08.trace')).toContain('Z=10');
 });
 it('aliases, non-preemptive intervals, chip dimensions and banks use the declared units',()=>{
  expect([0x24,0x25,0x2c,0x2d].map(n=>n&0xf6)).toEqual([0x24,0x24,0x24,0x24]);expect(prose('t09.decode')).toContain('0x2D');expect(3+5).toBe(8);expect(prose('t09.interrupt')).toContain('[3,8)');expect(2048*16).toBe(32768);expect(32768/8).toBe(4096);expect(2**9).toBe(512);expect(4*4).toBe(16);expect(prose('t10.chips')).toContain('eleven word-address bits');expect(13%4).toBe(1);expect(Math.floor(13/4)).toBe(3);expect(prose('t10.interleave')).toContain('bank 1, row 3');
 });
 it('cache decomposition reconstructs addresses and LRU hit refresh gives the stated trace',()=>{
  expect(((5*2)+1)*4+1).toBe(45);expect(8-2-1).toBe(5);expect(prose('t11.fields')).toContain('tag five bits');expect(prose('t11.trace')).toContain('[0], [0,1], [1,0], [0,2], [2,1]');expect(prose('t11.trace')).toContain('miss, miss, hit, miss, miss');expect([0,1,3].map(n=>Math.floor(n/4))).toEqual([0,0,0]);
 });
 it('pipeline cycle endpoints, timing and dependencies match independent schedule references',()=>{
  expect(5+4-1).toBe(8);expect(8+3).toBe(11);expect(5*2).toBe(10);expect(8*2).toBe(16);expect(prose('t12.cycles')).toContain('16 ns');expect(prose('t12.schedule')).toContain('1,2,3,5');expect(prose('t12.schedule')).toContain('1,4,5,8');expect(5+4).toBe(9);expect(8+4).toBe(12);expect(2*3).toBe(6);expect(prose('t12.optimize')).toContain('add six cycles');
 });
 it('Amdahl and VM calculations preserve original-time fractions and page offsets',()=>{
  expect(1/(.25+.75/3)).toBe(2);expect(1/.25).toBe(4);expect((.5-1/3)/(1-1/3)).toBeCloseTo(.25);expect(prose('t13.example')).toContain('upper bound is 4');expect(2**16/256*4).toBe(1024);expect(0x1234%256).toBe(52);expect(Math.floor(0x1234/256)).toBe(18);expect(7*256+52).toBe(1844);expect((3*256+52).toString(16)).toBe('334');expect(prose('t14.layout')).toContain('1024 bytes');expect(prose('t14.translation')).toContain('0x734 (1844)');
 });
});
