import {describe,it,expect} from 'vitest';
import co from '../src/exams/banks/co.json';
import rl from '../src/exams/banks/rl.json';
import ip from '../src/exams/banks/ip.json';
import {startSession,selectItems,resolveSession,timing,summary} from '../src/exams/engine';
import {evaluateSubmission,practiceFor} from '../src/exams/evaluation';
import {validateExamSession,answered} from '../src/exams/records';
import {deriveEvidence} from '../src/adaptive/evidence';
import type {ExamBank} from '../src/exams/types';
const banks=[co,rl,ip] as ExamBank[],now=Date.parse('2026-09-10T10:00:00.000Z');
export const examBanks=banks;
describe('shared exact exam engine',()=>{
 for(const bank of banks)for(const blueprint of bank.blueprints){
  const label=bank.course+'/'+blueprint.mode;
  it(label+' reconstructs fixed seed, exact versions and authored constraints',()=>{const a=startSession(blueprint,bank,'seed','session',now);expect(a).toEqual(startSession(blueprint,bank,'seed','session',now));expect(a.items).toHaveLength(blueprint.slots.length);expect(new Set(a.items.map(i=>i.id)).size).toBe(a.items.length);expect(resolveSession(a,bank).status).toBe('AVAILABLE');expect(summary(a).unanswered).toBe(a.items.length);expect(a.startedAt).toBe(new Date(now).toISOString());});
  it(label+' never resets a deadline on reload or background elapsed time',()=>{const a=startSession(blueprint,bank,'seed','session',now),b=JSON.parse(JSON.stringify(a));expect(timing(b,now+123456).remainingMs).toBe(blueprint.durationMinutes*60000-123456);expect(timing(b,Date.parse(a.deadlineAt)-1)).toEqual({expired:false,remainingMs:1});expect(timing(b,Date.parse(a.deadlineAt))).toEqual({expired:true,remainingMs:0});expect(timing(b,Date.parse(a.deadlineAt)+86400000)).toEqual({expired:true,remainingMs:0});expect(()=>timing(b,NaN)).toThrow();});
  it(label+' separates unanswered, rubric and exact components with correct total bounds',()=>{const s=startSession(blueprint,bank,'seed','session',now);const result=evaluateSubmission(s,bank,s.startedAt);expect(result.evaluations.every(e=>e.status==='UNANSWERED')).toBe(true);expect(result.attempts).toEqual([]);for(const r of s.responses){const i=bank.items.find(i=>i.id===r.itemId)!;r.answer=practiceFor(i)?.reference??{kind:i.responseType as 'text'|'code',value:'A proof with every keyword; System.exit(0); this is not correctness evidence.'};}const graded=evaluateSubmission(s,bank,s.startedAt);expect(graded.evaluations.filter(e=>e.status==='AUTO_SCORED').reduce((n,e)=>n+(e.status==='AUTO_SCORED'?e.earned:0),0)).toBe(summary(s).autoMax);expect(graded.evaluations.filter(e=>e.status==='RUBRIC_REVIEW_REQUIRED')).toHaveLength(summary(s).open);expect(graded.attempts).toHaveLength(s.items.length-summary(s).open);expect(deriveEvidence(graded.attempts,[],now).mistakes).toHaveLength(0);});
  it(label+' does not reinterpret missing item, blueprint or evaluator versions',()=>{const s=startSession(blueprint,bank,'seed','session',now);for(const change of [(b:ExamBank)=>{b.items[0].version='2';},(b:ExamBank)=>{b.blueprints.find(b=>b.id===blueprint.id)!.version='2';},(b:ExamBank)=>{b.items.find(i=>i.id===s.items[0].id)!.evaluator.version='future';}]){const b=structuredClone(bank);change(b);if(s.items.some(i=>i.id===bank.items[0].id)||b.blueprints.some(i=>i.version==='2'))expect(resolveSession(s,b).status).toBe('UNAVAILABLE');}expect(s.items[0].version).toBe('1');});
 }
 for(const bank of banks)for(const item of bank.items.filter(i=>i.evaluation==='DETERMINISTIC'))it(item.id+' reuses a verified exact binding and rejects malformed format without mistake inflation',()=>{expect(practiceFor(item)).not.toBeNull();const b=bank.blueprints.find(b=>b.mode==='full')!;const s=startSession(b,bank,'x','s',now),r=s.responses.find(r=>r.itemId===item.id)!;r.answer=r.answer.kind==='choice'?{kind:'choice',value:['unknown-option']}:{kind:'text',value:'not an accepted response'};const result=evaluateSubmission(s,bank,s.startedAt);expect(result.evaluations.find(e=>e.itemId===item.id)?.status).toBe('NOT_AUTOGRADABLE');expect(result.attempts).toEqual([]);});
 it('CO full covers thirteen technical clusters with one Assembly question',()=>{const full=selectItems(banks[0].blueprints[1],banks[0],'x');expect(full).toHaveLength(22);expect(new Set(full.map(i=>i.topicId)).size).toBe(13);expect(full.filter(i=>i.topicId==='CO_T06_ASSEMBLY_X86_64')).toHaveLength(1);expect(full.some(i=>i.mechanism==='dma')).toBe(true);});
 it('R&L full has twelve open components, accepting multiple valid proof/formalization surfaces without numeric grading',()=>{const b=banks[1],s=startSession(b.blueprints[1],b,'x','s',now);expect(s.items.filter(i=>i.evaluation==='RUBRIC')).toHaveLength(12);for(const value of ['∀x ¬P(x)','¬∃x P(x)','incorrect proof induction QED']){s.responses.find(r=>r.itemId==='ds.exam.rl.formalization')!.answer={kind:'text',value};const e=evaluateSubmission(s,b,s.startedAt).evaluations.find(e=>e.itemId==='ds.exam.rl.formalization');expect(e).toMatchObject({status:'RUBRIC_REVIEW_REQUIRED'});expect(e).not.toHaveProperty('earned');}});
 it('IP full links eight components into one unexecuted program with explicit requirement skill ownership',()=>{const open=banks[2].items.filter(i=>i.evaluation==='RUBRIC');expect(open).toHaveLength(8);expect(new Set(open.map(i=>i.context)).size).toBe(1);expect(open.every(i=>i.rubric!.length>=3&&i.skillIds.length>0&&i.responseType==='code')).toBe(true);});
 it('eligible wrong components feed existing evidence without whole-exam weakness',()=>{const b=banks[0],s=startSession(b.blueprints[0],b,'x','s',now);s.responses[0].answer={kind:'text',value:'00000'};s.responses[2].answer={kind:'text',value:'proof wrong'};const r=evaluateSubmission(s,b,s.startedAt);const ev=deriveEvidence(r.attempts,[],now);expect(ev.mistakes).toHaveLength(1);expect(r.evidence).toHaveLength(1);expect(ev.mistakes[0].attempt.targetedSkillIds).toHaveLength(1);});
 it('partial points are only sums of independently verified atomic components',()=>{const b=banks[0],s=startSession(b.blueprints[0],b,'x','s',now);s.responses[0].answer=practiceFor(b.items[0])!.reference;s.responses[1].answer={kind:'text',value:'0'};const r=evaluateSubmission(s,b,s.startedAt);expect(r.evaluations[0]).toMatchObject({earned:2,max:2});expect(r.evaluations[1]).toMatchObject({earned:0,max:2});});
 it.each(['','   ','\n\t'])('blank %j is unanswered, not incorrect',value=>expect(answered({kind:'text',value})).toBe(false));
 it('detects duplicate mechanisms and missing constraints instead of silently constructing a poor exam',()=>{const b=structuredClone(banks[0]),p=b.blueprints[0];p.slots[1]=structuredClone(p.slots[0]);expect(()=>selectItems(p,b,'s')).toThrow();});
 it('selection stays linear over a large bank with repeated deterministic reconstruction',()=>{const b=structuredClone(banks[0]);b.items.push(...Array.from({length:10000},(_,n)=>({...b.items[0],id:'unused-'+n})));const start=performance.now();for(let n=0;n<100;n++)expect(selectItems(b.blueprints[0],b,'x')).toHaveLength(4);expect(performance.now()-start).toBeLessThan(5000);});
 it.each(['sessionId','blueprint','deadlineAt','responses','items','timingPolicy','scoringPolicy'])('rejects missing %s',key=>{const s=startSession(banks[0].blueprints[0],banks[0],'x','s',now);delete (s as unknown as Record<string,unknown>)[key];expect(()=>validateExamSession(s)).toThrow();});
});
