import {afterEach,describe,it,expect,vi} from 'vitest';
import {IDBFactory,IDBObjectStore} from 'fake-indexeddb';
import {IndexedStudentRepository} from '../src/learning/repository';
import {emptyBackup,parseBackup,migrateBackup} from '../src/learning/contracts';
import type {ExamBank} from '../src/exams/types';
import co from '../src/exams/banks/co.json';
import {attempt,time} from './helpers/learning';
const bank=co as ExamBank;
function setup(factory=new IDBFactory()){let now=Date.parse(time),id=0;const repo=new IndexedStudentRepository({factory,name:'exam',now:()=>new Date(now).toISOString(),id:()=>`gen-${++id}`});return {repo,factory,setTime:(n:number)=>{now=n;}};}
async function started(){const context=setup(),loaded=await context.repo.load(),state=await context.repo.startExam(bank,bank.blueprints[0].id,'fixed','one',loaded.data);return {...context,state,session:state.data.exams[0]};}
afterEach(()=>vi.restoreAllMocks());
describe('transactional exam storage',()=>{
 it('autosaves answers/flags, resumes exact deadline and refuses stale tab overwrite',async()=>{const {repo,factory,state,session}=await started();const tab=setup(factory).repo,old=await tab.load();session.responses[0].answer={kind:'text',value:'00000'};const saved=await repo.saveExam('one',1,session.responses,[session.items[0].id],state.data);expect((await tab.load()).data.exams[0]).toEqual(saved.data.exams[0]);expect(saved.data.exams[0].deadlineAt).toBe(session.deadlineAt);await expect(tab.saveExam('one',1,old.data.exams[0].responses,[],old.data)).rejects.toMatchObject({code:'CONFLICT'});expect((await repo.load()).data).toEqual(saved.data);repo.close();tab.close();});
 it('commits submission/evidence atomically, is idempotent and locks edits/abandon',async()=>{const {repo,state,session}=await started();session.responses[0].answer={kind:'text',value:'00000'};const saved=await repo.saveExam('one',1,session.responses,[],state.data),original=saved.data.exams[0];const done=await repo.submitExam(original,'operation',bank,saved.data);expect(done.data.exams[0].status).toBe('SUBMITTED');expect(done.data.attempts).toHaveLength(1);expect(await repo.submitExam(original,'operation',bank,saved.data)).toEqual(done);await expect(repo.saveExam('one',2,session.responses,[],state.data)).rejects.toMatchObject({code:'CONFLICT'});await expect(repo.abandonExam('one',3,done.data)).rejects.toMatchObject({code:'CONFLICT'});const conflicting=structuredClone(original);conflicting.responses[0].answer={kind:'text',value:'11111'};await expect(repo.submitExam(conflicting,'operation',bank,done.data)).rejects.toMatchObject({code:'CONFLICT'});expect((await repo.load()).data).toEqual(done.data);repo.close();});
 it('an aborted submission after successful put reports failure and preserves answers and attempts',async()=>{const {repo,state,session}=await started();const put=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value,key){const r=put.call(this,value,key);if(key==='active')r.addEventListener('success',()=>this.transaction.abort());return r;});await expect(repo.submitExam(session,'op',bank,state.data)).rejects.toBeDefined();vi.restoreAllMocks();expect(await repo.load()).toEqual(state);repo.close();});
 it('expired drafts freeze at the exact boundary but explicitly submit previously saved work',async()=>{const {repo,state,session,setTime}=await started();setTime(Date.parse(session.deadlineAt)-1);const saved=await repo.saveExam('one',1,session.responses,[session.items[0].id],state.data);setTime(Date.parse(session.deadlineAt));await expect(repo.saveExam('one',2,session.responses,[],saved.data)).rejects.toMatchObject({code:'CONFLICT'});const done=await repo.submitExam(saved.data.exams[0],'op',bank,saved.data);expect(done.data.exams[0].submission?.submittedAt).toBe(session.deadlineAt);expect(done.data.exams[0].flagged).toHaveLength(1);repo.close();});
 it('retake creates a new deadline/session and leaves submitted bytes unchanged',async()=>{const {repo,state,session,setTime}=await started();const done=await repo.submitExam(session,'op',bank,state.data);setTime(Date.parse(time)+60000);const again=await repo.startExam(bank,bank.blueprints[0].id,session.seed,'two',done.data);expect(again.data.exams[0]).toEqual(done.data.exams[0]);expect(again.data.exams[1].deadlineAt).not.toBe(session.deadlineAt);await expect(repo.startExam(bank,bank.blueprints[0].id,'x','one',again.data)).rejects.toMatchObject({code:'CONFLICT'});repo.close();});
 it('abandon preserves responses and rejects subsequent editing',async()=>{const {repo,state}=await started();const end=await repo.abandonExam('one',1,state.data);expect(end.data.exams[0].status).toBe('ABANDONED');await expect(repo.saveExam('one',2,end.data.exams[0].responses,[],end.data)).rejects.toMatchObject({code:'CONFLICT'});repo.close();});
 it('self-review is separate revisioned workflow and cannot assign points to open work',async()=>{const {repo,state,session}=await started();session.responses[2].answer={kind:'text',value:'my construction'};const saved=await repo.saveExam('one',1,session.responses,[],state.data),done=await repo.submitExam(saved.data.exams[0],'op',bank,saved.data);const review=await repo.reviewExam('one',session.items[2].id,0,true,done.data);expect(review.data.exams).toEqual(done.data.exams);await expect(repo.reviewExam('one',session.items[2].id,0,false,done.data)).rejects.toMatchObject({code:'CONFLICT'});await expect(repo.reviewExam('one',session.items[0].id,0,true,done.data)).rejects.toBeDefined();repo.close();});
 it('new backup round-trip and atomic restore preserve submitted/in-progress history with recovery and stale epochs',async()=>{const {repo,state,session}=await started();const done=await repo.submitExam(session,'op',bank,state.data),before=await repo.exportBackup();expect(parseBackup(JSON.stringify(before))).toEqual(before);const replaced=await repo.restore(before,done.data);expect(await repo.exportRecovery()).toEqual(before);expect(replaced.data.exams).toEqual(done.data.exams);await expect(repo.startExam(bank,bank.blueprints[0].id,'x','stale',done.data)).rejects.toMatchObject({code:'CONFLICT'});repo.close();});
 it('aborted restore retains active exams and pre-existing recovery together',async()=>{const {repo,state}=await started();const first=await repo.restore(await repo.exportBackup(),state.data),recovery=await repo.exportRecovery();const put=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value,key){const r=put.call(this,value,key);if(key==='active')r.addEventListener('success',()=>this.transaction.abort());return r;});await expect(repo.restore(emptyBackup(),first.data)).rejects.toBeDefined();vi.restoreAllMocks();expect(await repo.load()).toEqual(first);expect(await repo.exportRecovery()).toEqual(recovery);repo.close();});
 it('rejects future schemas and corrupted exam records before replacing active data',async()=>{const {repo,state}=await started();for(const bad of [{...emptyBackup(),schemaVersion:4},{...emptyBackup(),exams:[{...state.data.exams[0],status:'SUBMITTED'}]},{...emptyBackup(),exams:[{...state.data.exams[0],deadlineAt:time}]},{...emptyBackup(),exams:[state.data.exams[0],state.data.exams[0]]}]){await expect(repo.restore(bad,state.data)).rejects.toBeDefined();expect(await repo.load()).toEqual(state);}repo.close();});
 it('rejects fabricated open automatic points and mismatched evidence on backup import',async()=>{const {repo,state,session}=await started(),done=await repo.submitExam(session,'op',bank,state.data);const backup=await repo.exportBackup();backup.exams[0].submission!.evaluations[2]={itemId:session.items[2].id,status:'AUTO_SCORED',earned:4,max:4};await expect(repo.restore(backup,done.data)).rejects.toBeDefined();expect(await repo.load()).toEqual(done);repo.close();});
 it('Schema 2 backups preserve attempts and reviews exactly while adding empty exam state',()=>{const {exams:_exams,examReviews:_examReviews,...old}=emptyBackup();const a=attempt({status:'SUBMITTED',submission:{operationId:'old',submittedAt:time}});const legacy={...old,schemaVersion:2,attempts:[a],reviews:[{attemptId:a.attemptId,reviewedAt:time,revision:5}]};const before=JSON.stringify(legacy),up=migrateBackup(legacy);expect(up.schemaVersion).toBe(3);expect(up.exams).toEqual([]);expect(JSON.stringify(up.attempts)).toBe(JSON.stringify(legacy.attempts));expect(up.reviews).toEqual(legacy.reviews);expect(JSON.stringify(legacy)).toBe(before);});
 it.each(['active','recovery','abort'])('Schema 2 upgrade rolls back both records and DB version on %s failure',async failure=>{const f=new IDBFactory(),{exams:_e,examReviews:_r,...old}=emptyBackup();const active={...old,schemaVersion:2,generation:'old',revision:13},recovery={...old,schemaVersion:2};const bad={...old,schemaVersion:2,invalid:true};const a=failure==='active'?{...bad,generation:'old',revision:13}:active,r=failure==='recovery'?bad:recovery;const db=await new Promise<IDBDatabase>(resolve=>{const q=f.open('exam',2);q.onupgradeneeded=()=>q.result.createObjectStore('student');q.onsuccess=()=>resolve(q.result);});await new Promise<void>(resolve=>{const tx=db.transaction('student','readwrite');tx.objectStore('student').put(a,'active');tx.objectStore('student').put(r,'recovery');tx.oncomplete=()=>resolve();});db.close();if(failure==='abort'){const put=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value,key){const q=put.call(this,value,key);if(key==='recovery')q.addEventListener('success',()=>this.transaction.abort());return q;});}await expect(setup(f).repo.load()).rejects.toBeDefined();vi.restoreAllMocks();const read=await new Promise<IDBDatabase>(resolve=>{const q=f.open('exam');q.onsuccess=()=>resolve(q.result);});expect(read.version).toBe(2);const values=await Promise.all(['active','recovery'].map(k=>new Promise<unknown>(resolve=>{const q=read.transaction('student').objectStore('student').get(k);q.onsuccess=()=>resolve(q.result);})));expect(values).toEqual([a,r]);read.close();});
 it('large history validates and round-trips within the declared session bound',async()=>{const {repo,state}=await started();const backup=emptyBackup();backup.exams=Array.from({length:250},(_,i)=>({...structuredClone(state.data.exams[0]),sessionId:'session-'+i}));const start=performance.now();expect(parseBackup(JSON.stringify(backup)).exams).toHaveLength(250);expect(performance.now()-start).toBeLessThan(3000);await repo.restore(backup,state.data);expect((await repo.load()).data.exams).toHaveLength(250);repo.close();});
});
