import {describe,it,expect} from 'vitest';
import {canonical} from '../scripts/practice-catalog';
import {loadIP,validateIP,validateIPFiles,ipRecords,ipCapabilities,checkIPLocks,readIP,readIPPack,validateIPSourcePolicy,ipBuildGuard} from '../scripts/ip-content';
import projection from '../src/generated/topic-study.json';
import {gradeIPResponse} from '../src/ip/grading';
import type {IPExercise} from '../src/ip/types';
const data=loadIP();
describe('IP complete-course authoring and safety gate',()=>{
 it('validates 20 topics,44 subtopics,56 deliberately covered skills and the published control-flow pilot',()=>{expect(validateIP(data)).toMatchObject({topics:20,subtopics:44,skills:56,lessons:20,newExercises:33,assignments:11});expect(data.topics).toHaveLength(19);expect(data.topics.some(t=>t.lesson.topicId==='IP_T02_CONTROL_FLOW')).toBe(false);expect(data.coverage).toHaveLength(56);expect(ipCapabilities(data).find(c=>c.topicId==='IP_T02_CONTROL_FLOW')?.cardCount).toBe(8);});
 it('validates all generated indexes, immutable locks, fingerprints and protected baseline bytes',()=>{expect(()=>validateIPFiles()).not.toThrow();});
 it('preserves canonical topic order and factual capabilities without learner percentages',()=>{const c=ipCapabilities(data);expect(c.map(t=>t.topicId)).toEqual(projection.topics.filter(t=>t.subjectId==='CSE1100_IP').map(t=>t.id));expect(c.every(t=>t.lessonId&&t.cardCount&&t.guidedCount)).toBe(true);expect(c.reduce((n,t)=>n+t.exerciseCount,0)).toBe(35);expect(canonical(c)).not.toMatch(/mastery|percentage|readiness|completed/);});
 it.each(['missing-topic','pilot-replacement','duplicate-topic','foreign-skill','wrong-subtopic','missing-source','promoted-source','duplicate-card','missing-card-skill','extra-score','unscored-guide-grade','empty-rubric','empty-guide-reference','duplicate-guide-field','code-in-concept','missing-substantive-teaching'] as const)('rejects lesson/card defect: %s',kind=>{
  const d=structuredClone(data),p=structuredClone(projection),topic=d.topics[0],block=topic.lesson.blocks[1];
  if(kind==='missing-topic')d.topics.pop();if(kind==='pilot-replacement')topic.lesson.topicId='IP_T02_CONTROL_FLOW';if(kind==='duplicate-topic')d.topics[1]=structuredClone(topic);if(kind==='foreign-skill')block.skillIds=['CO_SK04_04_OVERFLOW'];if(kind==='wrong-subtopic')block.subtopicIds=['IP_ST20_01_SPEC_TO_PROGRAM'];if(kind==='missing-source')block.sourceIds=['missing'];if(kind==='promoted-source')p.sources.find(s=>s.id===block.sourceIds[0])!.precision='EXACT_PAGE';if(kind==='duplicate-card')topic.cards[1].id=topic.cards[0].id;if(kind==='missing-card-skill'){const skill=topic.cards[0].skillIds[0];topic.cards=topic.cards.filter(c=>!c.skillIds.includes(skill));}if(kind==='extra-score')Object.assign(topic.cards[0],{mastery:100});if(kind==='unscored-guide-grade')Object.assign(topic.guided[0],{earned:1});if(kind==='empty-rubric')topic.guided[0].rubric=[];if(kind==='empty-guide-reference')topic.guided[0].reference=[];if(kind==='duplicate-guide-field')topic.guided[0].fields.push(topic.guided[0].fields[0]);if(kind==='code-in-concept'){block.kind='concept';block.code='class Bad {}';}if(kind==='missing-substantive-teaching'){const skill=block.skillIds[0];topic.lesson.blocks.filter(b=>!['introduction','recap'].includes(b.kind)).forEach(b=>b.skillIds=b.skillIds.filter(id=>id!==skill));}
  expect(()=>validateIP(d,p)).toThrow();
 });
 it.each(['untrusted-notes','promoted-mock','missing-evidence','unverified-evidence','invalid-page','foreign-evidence-skill','unknown-cue-skill','cue-source-mismatch'] as const)('rejects source/evidence defect: %s',kind=>{const d=structuredClone(data);if(kind==='untrusted-notes')d.evidence[0].filename='IP Notes.pdf';if(kind==='promoted-mock')d.evidence.find(e=>e.id==='ip-integrated-mock')!.authority='OFFICIAL_ASSESSMENT';if(kind==='missing-evidence')d.evidence.pop();if(kind==='unverified-evidence')d.feedback[0].evidenceIds=['unverified'];if(kind==='invalid-page')d.evidence[0].pages=[9999];if(kind==='foreign-evidence-skill')d.evidence[0].skillIds=['RL_SK01_01_CONNECTIVE'];if(kind==='unknown-cue-skill')d.cues[0].skillIds=['IP_UNKNOWN'];if(kind==='cue-source-mismatch')d.cues[0].sourceIds=['ref-4796de4e30624f07'];expect(()=>validateIP(d)).toThrow();});
 it.each(['open-code-task','fake-grader','invalid-reference','duplicate-option','ambiguous-display','assessment-source','wrong-practice-skill','stale-profile-binding','correct-answer-pattern','ambiguous-pattern','unknown-pattern','wrong-pattern-skill','missing-profile','extra-diagnosis-field'] as const)('rejects fixed practice/feedback defect: %s',kind=>{const d=structuredClone(data),e=d.exercises[0],p=d.feedback[0];if(kind==='open-code-task')Object.assign(e.task,{kind:'java-free-form'});if(kind==='fake-grader')Object.assign(e.grader,{id:'keyword-java'});if(kind==='invalid-reference')e.reference={kind:'choice',value:['unknown']};if(kind==='duplicate-option')e.task.options[1].id=e.task.options[0].id;if(kind==='ambiguous-display')e.task.options[1].output=e.task.options[0].output;if(kind==='assessment-source')Object.assign(e.source,{kind:'ASSESSMENT'});if(kind==='wrong-practice-skill')e.skillId='IP_SK20_01_EXAM_SYNTHESIS';if(kind==='stale-profile-binding')p.binding='old';if(kind==='correct-answer-pattern')p.paths[0].answer=(e.reference.value as string[])[0];if(kind==='ambiguous-pattern')p.paths.push({...p.paths[0]});if(kind==='unknown-pattern')p.paths[0].answer='does-not-exist';if(kind==='wrong-pattern-skill')p.paths[0].misconceptionId=d.misconceptions.find(m=>!m.skillIds.includes(e.skillId))!.id;if(kind==='missing-profile')d.feedback.pop();if(kind==='extra-diagnosis-field')Object.assign(p,{learnerErrorHistory:[]});expect(()=>validateIP(d)).toThrow();});
 it.each(['missing-reference','reference-version','extra-reference','missing-primary-topic','foreign-related-topic','extra-skill','missing-requirement','dangling-rubric-test','rubric-foreign-skill','missing-requirement-test','missing-rubric','wrong-reference-owner','unsafe-filename','duplicate-filename','language-mismatch','fake-open-grade','missing-time-class','missing-integrated-flow'] as const)('rejects assignment/reference defect: %s',kind=>{const d=structuredClone(data),a=d.assignments[0],r=d.references.find(r=>r.id===a.referenceId)!;if(kind==='missing-reference')d.references=d.references.filter(x=>x.id!==r.id);if(kind==='reference-version')r.version='99';if(kind==='extra-reference')d.references.push(structuredClone(r));if(kind==='missing-primary-topic')a.relatedTopicIds=a.relatedTopicIds.filter(id=>id!==a.topicId);if(kind==='foreign-related-topic')a.relatedTopicIds.push('RL_T01_PROP_LOGIC');if(kind==='extra-skill')a.skillIds.push('IP_UNKNOWN');if(kind==='missing-requirement')a.requirements.pop();if(kind==='dangling-rubric-test')a.rubric[0].testIds=['missing'];if(kind==='rubric-foreign-skill')a.rubric[0].skillIds=['RL_SK01_01_CONNECTIVE'];if(kind==='missing-requirement-test')r.tests=[];if(kind==='missing-rubric')a.rubric=[];if(kind==='wrong-reference-owner')r.assignmentId='other';if(kind==='unsafe-filename')a.starterFiles[0].name='../Program.java';if(kind==='duplicate-filename')a.starterFiles.push({...a.starterFiles[0]});if(kind==='language-mismatch')a.starterFiles[0].language='text';if(kind==='fake-open-grade')Object.assign(a,{grader:'keyword-score'});if(kind==='missing-time-class')d.assignments.filter(a=>a.minutes===15).forEach(a=>a.minutes=30);if(kind==='missing-integrated-flow')d.assignments.find(a=>a.minutes===60)!.minutes=30;expect(()=>validateIP(d)).toThrow();});
 it.each(['missing-class','duplicate-class','foreign-class','A-without-exercise','C-without-rubric','D-without-workspace','foreign-exercise-link','foreign-guide-link','foreign-assignment-link'] as const)('rejects classification defect: %s',kind=>{const d=structuredClone(data),c=d.coverage[0];if(kind==='missing-class')d.coverage.pop();if(kind==='duplicate-class')d.coverage[1].skillId=c.skillId;if(kind==='foreign-class')c.skillId='RL_SK01_01_CONNECTIVE';if(kind==='A-without-exercise'){c.category='A';c.exerciseIds=[];}if(kind==='C-without-rubric'){c.category='C';c.guidedIds=[];c.assignmentIds=[];}if(kind==='D-without-workspace'){c.category='D';c.assignmentIds=[];}if(kind==='foreign-exercise-link')c.exerciseIds=['ds.practice.nonexistent'];if(kind==='foreign-guide-link')c.guidedIds=['ds.guided.nonexistent'];if(kind==='foreign-assignment-link')c.assignmentIds=['ds.assignment.nonexistent'];expect(()=>validateIP(d)).toThrow();});
 it.each(['lesson','block','card','guide','intro-guide','exercise','feedback','misconception','cue','evidence','assignment','reference','coverage'] as const)('rejects silent mutation of a published %s record',kind=>{const d=structuredClone(data);if(kind==='lesson')d.topics[0].lesson.version='2';if(kind==='block')d.topics[0].lesson.blocks[0].paragraphs[0]+=' changed';if(kind==='card')d.topics[0].cards[0].answer+=' changed';if(kind==='guide')d.topics[0].guided[0].reference[0]+=' changed';if(kind==='intro-guide')d.introGuided[0].prompt+=' changed';if(kind==='exercise')d.exercises[0].prompt+=' changed';if(kind==='feedback')d.feedback[0].reasoning+=' changed';if(kind==='misconception')d.misconceptions[0].rule+=' changed';if(kind==='cue')d.cues[0].text+=' changed';if(kind==='evidence')d.evidence[0].section+=' changed';if(kind==='assignment')d.assignments[0].instructions[0]+=' changed';if(kind==='reference')d.references[0].reasoning[0]+=' changed';if(kind==='coverage')d.coverage[0].reason+=' changed';expect(()=>checkIPLocks(d,readIP('content-lock.json'))).toThrow('published version changed');});
 it('does not register or automatically grade any open code assignment or guided answer',()=>{for(const a of [...data.assignments,...data.topics.flatMap(t=>t.guided),...data.introGuided]){expect(data.exercises.some(e=>e.id===a.id)).toBe(false);expect(a).not.toHaveProperty('grader');expect(a).not.toHaveProperty('score');}const open={...data.exercises[0],task:{kind:'open-java'}} as unknown as IPExercise;expect(gradeIPResponse(open,{kind:'text',value:'public class Code { }'})).toMatchObject({status:'NOT_AUTOGRADABLE'});});
 it('locks every distinct authored entity and keeps direct Vite builds behind validation',()=>{expect(new Set(ipRecords(data).map(r=>r.id)).size).toBe(ipRecords(data).length);const guard=ipBuildGuard(()=>{throw new Error('invalid IP content');});expect(guard.buildStart as ()=>void).toThrow('invalid IP content');});
});
describe('IP canonical source policy retains integrated assessments and unknown components',()=>{
 it('preserves seven integrated whole programs and 38 unknown analytical component locators',()=>{expect(validateIPSourcePolicy()).toEqual({assessments:7,integratedMappings:7,unknownComponentMappings:38});});
 it.each(['promote-mock','promote-era','change-weight','split-whole','automatic-whole-credit','frequency-whole-credit','precise-component','known-component-page'] as const)('rejects policy mutation: %s',kind=>{const p=readIPPack();const as=p.assessment_model.assessments.filter(a=>a.subject_id==='CSE1100_IP');const q=as.flatMap(a=>a.question_map);const whole=q.find(q=>q.mapping_granularity==='INTEGRATED_MULTI_SKILL')!,component=q.find(q=>q.mapping_granularity==='SKILL_LEVEL')!;if(kind==='promote-mock')as.find(a=>a.document_id==='IP_MOCK_2024')!.official_status='OFFICIAL_ASSESSMENT';if(kind==='promote-era')as.find(a=>a.document_id==='IP_END_2020')!.evidence_era='CURRENT';if(kind==='change-weight')as.find(a=>a.document_id==='IP_END_2021')!.current_style_weight='VERY_HIGH';if(kind==='split-whole')whole.mapping_granularity='SKILL_LEVEL';if(kind==='automatic-whole-credit')whole.skill_mastery_update_policy='UPDATE_ALL_SKILLS';if(kind==='frequency-whole-credit')whole.historical_skill_frequency_eligible=true;if(kind==='precise-component')component.source_locator={kind:'PDF_PAGE_RANGE',start_page:2,end_page:2,confidence:'HIGH',method:'DIRECT_REVIEW'};if(kind==='known-component-page')component.source_page_or_slide='PDF_PAGE_2';expect(()=>validateIPSourcePolicy(p)).toThrow();});
});
describe('IP source-policy review regressions',()=>{
 it.each(['question-authority','question-era','duplicate-assessment','guessed-unknown-page'] as const)('rejects contradictory or invented source metadata: %s',kind=>{const p=readIPPack();const assessments=p.assessment_model.assessments.filter(a=>a.subject_id==='CSE1100_IP');const mock=assessments.find(a=>a.document_id==='IP_MOCK_2024')!;if(kind==='question-authority')mock.question_map[0].official_status='OFFICIAL_ASSESSMENT';if(kind==='question-era')mock.question_map[0].evidence_era='HISTORICAL';if(kind==='duplicate-assessment'){const target=p.assessment_model.assessments.findIndex(a=>a.document_id==='IP_END_2023');p.assessment_model.assessments[target]=structuredClone(assessments.find(a=>a.document_id==='IP_END_2024')!);}if(kind==='guessed-unknown-page'){const component=mock.question_map.find(q=>q.mapping_granularity==='SKILL_LEVEL')!;Object.assign(component.source_locator as object,{start_page:2});}expect(()=>validateIPSourcePolicy(p)).toThrow();});
});
