import {afterEach, describe, expect, it, vi} from 'vitest';
import {IDBFactory, IDBObjectStore} from 'fake-indexeddb';
import {emptyBackup, migrateBackup, parseBackup, validateBackup, type Backup} from '../src/learning/contracts';
import {IndexedStudentRepository} from '../src/learning/repository';
import {attempt, time} from './helpers/learning';
const submitted=attempt({status:'SUBMITTED', submission:{operationId:'legacy-operation',submittedAt:time}});
function legacy(){const {reviews:_reviews,...backup}=emptyBackup();return {...backup,schemaVersion:1,attempts:[structuredClone(submitted)]};}
function open(factory:IDBFactory,name:string,version?:number){return new Promise<IDBDatabase>((resolve,reject)=>{const r=factory.open(name,version);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function seed(factory:IDBFactory,active:unknown,recovery:unknown=legacy()){
 const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=factory.open('migration',1);r.onupgradeneeded=()=>r.result.createObjectStore('student');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 await new Promise<void>((resolve,reject)=>{const tx=db.transaction('student','readwrite');tx.objectStore('student').put(active,'active');tx.objectStore('student').put(recovery,'recovery');tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error);});db.close();
}
async function read(factory:IDBFactory){const db=await open(factory,'migration');const tx=db.transaction('student');const values=await Promise.all(['active','recovery'].map(key=>new Promise<unknown>(resolve=>{const r=tx.objectStore('student').get(key);r.onsuccess=()=>resolve(r.result);})));const version=db.version;db.close();return {version,values};}
function repo(factory:IDBFactory){let i=0;return new IndexedStudentRepository({factory,name:'migration',now:()=>time,id:()=>`new-generation-${++i}`});}
afterEach(()=>vi.restoreAllMocks());
describe('Schema 1 to 2 migration and separate workflow',()=>{
 it('migrates valid legacy backups without rewriting submitted bytes',()=>{const old=legacy(),before=JSON.stringify(old);const result=parseBackup(before);expect(result.schemaVersion).toBe(2);expect(result.reviews).toEqual([]);expect(JSON.stringify(result.attempts)).toBe(JSON.stringify(old.attempts));expect(JSON.stringify(old)).toBe(before);});
 it('atomically upgrades active and recovery, preserves revisions and changes generation',async()=>{const f=new IDBFactory(),old={...legacy(),generation:'old',revision:7};await seed(f,old);const r=repo(f),loaded=await r.load();expect(loaded.data.revision).toBe(7);expect(loaded.data.generation).not.toBe('old');expect(JSON.stringify(loaded.data.attempts)).toBe(JSON.stringify(old.attempts));expect((await r.exportRecovery()).attempts).toEqual(old.attempts);expect((await read(f)).version).toBe(2);await expect(r.editDraft('x',1,{kind:'text',value:'x'},{generation:'old'})).rejects.toMatchObject({code:'CONFLICT'});r.close();await expect(open(f,'migration',1)).rejects.toMatchObject({name:'VersionError'});});
 it.each(['active','recovery'])('rolls back the database version and both records if %s is malformed',async key=>{const f=new IDBFactory(),old={...legacy(),generation:'old',revision:0};const corrupt={...legacy(),attempts:[{...submitted,correct:true}]};const active=key==='active'?{...corrupt,generation:'old',revision:0}:old;const recovery=key==='recovery'?corrupt:legacy();await seed(f,active,recovery);await expect(repo(f).load()).rejects.toMatchObject({code:'INVALID'});expect(await read(f)).toEqual({version:1,values:[active,recovery]});});
 it('abort after a migration put request succeeds rolls back version and all data',async()=>{const f=new IDBFactory(),old={...legacy(),generation:'old',revision:0};await seed(f,old);const put=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value,key){const r=put.call(this,value,key);if(key==='recovery')r.addEventListener('success',()=>this.transaction.abort());return r;});await expect(repo(f).load()).rejects.toMatchObject({code:'STORAGE'});vi.restoreAllMocks();expect(await read(f)).toEqual({version:1,values:[old,legacy()]});});
 it('versionchange closes a cooperative v1 tab before migration; stale generation cannot write',async()=>{const f=new IDBFactory();await seed(f,{...legacy(),generation:'old',revision:0});const old=await open(f,'migration',1);let changed=false;old.onversionchange=()=>{changed=true;old.close();};const r=repo(f);await r.load();expect(changed).toBe(true);await expect(r.setReviewed(submitted.attemptId,0,true,{generation:'old'})).rejects.toMatchObject({code:'CONFLICT'});r.close();});
 it('review, undo and conflicts preserve the original answer and submission',async()=>{const f=new IDBFactory();await seed(f,{...legacy(),generation:'old',revision:0});const r=repo(f),initial=await r.load();const marked=await r.setReviewed(submitted.attemptId,0,true,initial.data);expect(marked.data.reviews[0]).toEqual({attemptId:submitted.attemptId,reviewedAt:time,revision:1});expect(marked.data.attempts).toEqual(initial.data.attempts);await expect(r.setReviewed(submitted.attemptId,0,false,initial.data)).rejects.toMatchObject({code:'CONFLICT'});const undone=await r.setReviewed(submitted.attemptId,1,false,marked.data);expect(undone.data.reviews[0].reviewedAt).toBeNull();expect(undone.data.attempts).toEqual(initial.data.attempts);r.close();});
 it('new-schema export and legacy restore keep a pre-restore recovery, reject stale writes',async()=>{const f=new IDBFactory();await seed(f,{...legacy(),generation:'old',revision:0});const r=repo(f),initial=await r.load(),reviewed=await r.setReviewed(submitted.attemptId,0,true,initial.data);const before=await r.exportBackup();const replacement=await r.restore(legacy(),reviewed.data);expect(replacement.data.reviews).toEqual([]);expect(await r.exportRecovery()).toEqual(before);expect(parseBackup(JSON.stringify(before))).toEqual(before);await expect(r.setReviewed(submitted.attemptId,1,false,reviewed.data)).rejects.toMatchObject({code:'CONFLICT'});r.close();});
 it('aborted restore preserves attempts and workflow together',async()=>{const f=new IDBFactory();await seed(f,{...legacy(),generation:'old',revision:0});const r=repo(f),initial=await r.load(),before=await r.setReviewed(submitted.attemptId,0,true,initial.data);const original=await r.exportRecovery();const put=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value,key){const req=put.call(this,value,key);if(key==='active')req.addEventListener('success',()=>this.transaction.abort());return req;});await expect(r.restore(legacy(),before.data)).rejects.toBeDefined();vi.restoreAllMocks();expect(await r.load()).toEqual(before);expect(await r.exportRecovery()).toEqual(original);r.close();});
 it.each([
 ['missing reviews',(b:Backup)=>{delete (b as Partial<Backup>).reviews;}],
 ['unknown attempt',(b:Backup)=>{b.reviews=[{attemptId:'unknown',reviewedAt:time,revision:1}];}],
 ['draft reference',(b:Backup)=>{b.attempts=[attempt()];b.reviews=[{attemptId:submitted.attemptId,reviewedAt:time,revision:1}];}],
 ['duplicate review',(b:Backup)=>{b.attempts.push({...submitted,attemptId:'other',submission:{operationId:'other-op',submittedAt:time}});b.reviews=Array.from({length:2},()=>({attemptId:submitted.attemptId,reviewedAt:time,revision:1}));}],
 ['bad review time',(b:Backup)=>{b.reviews=[{attemptId:submitted.attemptId,reviewedAt:'yesterday',revision:1}];}],
 ['fake correctness',(b:Backup)=>{b.reviews=[{attemptId:submitted.attemptId,reviewedAt:time,revision:1,correct:true} as Backup['reviews'][number]];}],
 ['duplicate attempt',(b:Backup)=>{b.attempts.push(b.attempts[0]);}],
 ['future version',(b:Backup)=>{Object.assign(b,{schemaVersion:3});}],
 ])('rejects %s before replacement',async(_name,damage)=>{const f=new IDBFactory(),r=repo(f),state=await r.load();const bad=migrateBackup(legacy());damage(bad);await expect(r.restore(bad,state.data)).rejects.toBeDefined();expect(await r.load()).toEqual(state);r.close();});
 it('rejects legacy extra fields rather than discarding fake evidence',()=>{expect(()=>migrateBackup({...legacy(),reviews:[]})).toThrow();expect(()=>migrateBackup({...legacy(),mastery:80})).toThrow();expect(()=>validateBackup({...emptyBackup(),schemaVersion:1})).toThrow();});
});
