import {describe,it,expect} from 'vitest';
import {deriveProgress} from '../src/progress/derive';
import {difficultyWeight} from '../src/progress/mastery';
import {validateBackup} from '../src/learning/contracts';
import {allExercises} from '../src/practice/catalog';
import {emptyBackup,CLOCK,banks,mock,success} from './helpers/progress';
describe('course-specific readiness and evidence boundaries',()=>{
 for(const course of [0,1,2]){
  it(`${course} one quick is low confidence, not a mock score`,()=>{const d=emptyBackup();mock(d,course,0,'quick');const r=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId===banks[course].course)!;expect(r.index).toBeLessThanOrEqual(35);expect(r.confidence).toBe('Low');expect(r.gaps.join(' ')).toContain('two recent');});
  it(`${course} full/open experience adds breadth but no open points or skill correctness`,()=>{const d=emptyBackup();mock(d,course,1,'full',false);const a=deriveProgress(d,CLOCK,banks);const open=emptyBackup();mock(open,course,1,'full',true);const b=deriveProgress(open,CLOCK,banks);const x=a.readiness.find(r=>r.courseId===banks[course].course)!,y=b.readiness.find(r=>r.courseId===banks[course].course)!;expect(y.index).toBe(x.index);expect(y.practisedTopics).toBeGreaterThan(x.practisedTopics);expect(b.evidence.observations.length).toBe(a.evidence.observations.length);expect(b.skills.every(s=>s.index===null)).toBe(true);});
  it(`${course} old exams retain records while recent breadth expires`,()=>{const d=emptyBackup();mock(d,course,1,'old',true,180);const r=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId===banks[course].course)!;expect(r.sessions).toBe(0);expect(r.index).toBeNull();expect(r.confidence).toBe('Insufficient');expect(r.objectiveTopics).toBe(0);expect(d.exams).toHaveLength(1);});
  it(`${course} missing historical banks cannot become practice or readiness evidence`,()=>{const d=emptyBackup();mock(d,course,1,'old',true);const r=deriveProgress(d,CLOCK,[]);expect(r.evidence.observations).toEqual([]);expect(r.evidence.open).toEqual([]);expect(r.readiness.every(r=>r.index===null)).toBe(true);});
  it(`${course} repeated full mock keeps per-item diversity capped`,()=>{const d=emptyBackup();mock(d,course,1,'one',true);const a=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId===banks[course].course)!;for(let n=0;n<10;n++)mock(d,course,1,'repeat'+n,true);const b=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId===banks[course].course)!;expect(b.distinctItems).toBe(a.distinctItems);expect(b.objectiveTopics).toBe(a.objectiveTopics);expect(b.confidence).not.toBe('High');expect(b.index).toBeLessThanOrEqual(60);});
 }
 it('Assembly-heavy learning cannot create CO readiness',()=>{const d=emptyBackup();d.attempts=allExercises.filter(e=>e.topicId==='CO_T06_ASSEMBLY_X86_64').map(e=>success(e.id,e.id));const r=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId==='CSE1400_CO')!;expect(r.index).toBeNull();expect(r.totalTopics).toBe(13);});
 it('truth-table drills alone cannot create R&L readiness',()=>{const d=emptyBackup();d.attempts=allExercises.filter(e=>e.topicId==='RL_T01_PROP_LOGIC').map(e=>success(e.id,e.id));const r=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId==='CSE1300_RL')!;expect(r.index).toBeNull();expect(r.openState).toBe('Limited');});
 it('Java predictions alone cannot create IP readiness or integrated practice',()=>{const d=emptyBackup();d.attempts=allExercises.filter(e=>e.subjectId==='CSE1100_IP').map(e=>success(e.id,e.id));const r=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId==='CSE1100_IP')!;expect(r.index).toBeNull();expect(r.integrated).toBe(false);});
 it('IP integration needs model, parser, application and tests from one exact full session',()=>{const d=emptyBackup();mock(d,2,1,'full',true);const r=deriveProgress(d,CLOCK,banks);expect(r.readiness.find(r=>r.courseId==='CSE1100_IP')!.integrated).toBe(true);expect(r.evidence.open).toHaveLength(8);expect(r.evidence.observations).toHaveLength(2);expect(r.skills.every(s=>s.index===null)).toBe(true);});
 it('open self-review, flags and completion do not raise correctness',()=>{const d=emptyBackup();const s=mock(d,1,1,'full',true);const a=deriveProgress(d,CLOCK,banks);s.flagged=[s.items[0].id];d.examReviews=[{sessionId:s.sessionId,itemId:'ds.exam.rl.proof-method',reviewedAt:s.startedAt,revision:1}];expect(deriveProgress(d,CLOCK,banks)).toEqual(a);});
 it('forged persisted objective result is excluded instead of granting readiness',()=>{const d=emptyBackup();const s=mock(d,0,0,'quick');const e=s.submission!.evaluations[0];if(e.status==='AUTO_SCORED')e.earned=0;expect(deriveProgress(d,CLOCK,banks).evidence.observations).toHaveLength(1);});
 it('orphan exam attempts cannot be laundered into learning mastery',()=>{const d=emptyBackup();mock(d,0,0,'quick');d.exams=[];const r=deriveProgress(d,CLOCK,banks);expect(r.evidence.observations).toEqual([]);expect(r.evidence.limited).toHaveLength(2);});
 it.each(['Easy','Medium','Hard','Unknown'] as const)('difficulty %s uses only declared modest coefficients',d=>expect(difficultyWeight(d)).toBe({Easy:.9,Medium:1,Hard:1.1,Unknown:1}[d]));
 it('two full CO exams still disclose missing early/late clusters and unverified explanation',()=>{const d=emptyBackup();mock(d,0,1,'one',true,1);mock(d,0,1,'two',true);const r=deriveProgress(d,CLOCK,banks).readiness.find(r=>r.courseId==='CSE1400_CO')!;expect(r.objectiveTopics).toBe(8);expect(r.practisedTopics).toBe(13);expect(r.confidence).toBe('Moderate');expect(r.index).toBeLessThanOrEqual(60);expect(r.gaps.join(' ')).toContain('correctness remains unverified');});
 it('new grader binding cannot reinterpret a submitted mock',()=>{const d=emptyBackup();mock(d,0,0,'quick',true);const changed=structuredClone(banks);changed[0].items[0].evaluator.version='future';expect(deriveProgress(d,CLOCK,changed).evidence.observations).toHaveLength(0);});
 it('broader normal learning coverage does not silently create exam readiness',()=>{const d=emptyBackup();d.attempts=allExercises.map(e=>success(e.id,e.id));const r=deriveProgress(d,CLOCK,banks);expect(r.courses.every(c=>c.covered>10)).toBe(true);expect(r.readiness.every(r=>r.index===null)).toBe(true);});
 it.each([100,1000,5000])('derives %i immutable attempts within a bounded runtime',count=>{const d=emptyBackup();d.attempts=Array.from({length:count},(_,n)=>success('p'+n,allExercises[n%100].id,n%20));validateBackup(d);const start=performance.now();const r=deriveProgress(d,CLOCK,banks);expect(r.evidence.observations).toHaveLength(count);expect(performance.now()-start).toBeLessThan(6000);});
 it('250 valid full sessions and 2000 components derive without duplicate evidence inflation',()=>{const d=emptyBackup();for(let n=0;n<250;n++)mock(d,0,1,'p'+n,true,n%20);validateBackup(d);const start=performance.now();const r=deriveProgress(d,CLOCK,banks);expect(r.readiness.find(r=>r.courseId==='CSE1400_CO')!.distinctItems).toBe(8);expect(performance.now()-start).toBeLessThan(6000);});
});
it('self-review regression: adding ungraded open answers cannot raise an objective readiness index',()=>{const closed=emptyBackup(),open=emptyBackup();for(const id of ['one','two']){mock(closed,0,1,id,false);mock(open,0,1,id,true);}const a=deriveProgress(closed,CLOCK,banks).readiness.find(r=>r.courseId==='CSE1400_CO')!,b=deriveProgress(open,CLOCK,banks).readiness.find(r=>r.courseId==='CSE1400_CO')!;expect(b.index).toBe(a.index);expect(b.openState).not.toBe(a.openState);});
it('final-review regression: selector answer identity is field-based even when record keys are reordered',()=>{const d=emptyBackup();mock(d,0,0,'ordered');const before=deriveProgress(d,CLOCK,banks);for(const a of d.attempts)a.answer={value:a.answer.value,kind:a.answer.kind} as typeof a.answer;expect(()=>validateBackup(d)).toThrow();expect(deriveProgress(d,CLOCK,banks)).toEqual(before);});
