import {describe,it,expect} from 'vitest';
import {loadRL,validateRL,validateRLFiles,checkRLLocks,readRL,rlCapabilities,rlBuildGuard} from '../scripts/rl-content';
import {checkRLSourcePolicy,readRLCanonicalPack,puzzleSolutions} from '../scripts/rl-source-policy';
import {topicStudy} from '../src/topic-study/content';
import {gradeRLResponse} from '../src/rl/grading';
import type {RLExercise} from '../src/rl/practice-types';
import {canonical} from '../scripts/practice-catalog';
const data=loadRL();
describe('complete R&L content and immutable publication gates',()=>{
 it('9 lessons,29 subtopics,45 taught/card-covered skills,67 cards,27 new exact items,23 guided activities,7 tools validate',()=>{
  expect(()=>validateRLFiles()).not.toThrow();const c=rlCapabilities(data,topicStudy);expect(c).toHaveLength(9);expect(c.every(t=>t.lessonId&&t.cardCount&&t.guidedCount)).toBe(true);expect(c.reduce((n,t)=>n+t.cardCount,0)).toBe(67);expect(c.reduce((n,t)=>n+t.exerciseCount,0)).toBe(29);expect(c.reduce((n,t)=>n+t.guidedCount,0)).toBe(23);expect(data.coverage).toHaveLength(45);expect(data.exercises).toHaveLength(27);expect(data.topics).toHaveLength(8);
 });
 it.each(['missing-topic','foreign-skill','subtopic','source','precision','old-lecture','duplicate-card','card-coverage','extra-score','proof-grade','reference-missing','duplicate-field','assessment-source','extra-mapping','invalid-reference','missing-class','unlinked-class','tool-scope'] as const)('rejects %s',kind=>{
  const d=structuredClone(data),projection=structuredClone(topicStudy),block=d.topics[0].lesson.blocks[1];
  if(kind==='missing-topic')d.topics.pop();if(kind==='foreign-skill')block.skillIds=['CO_SK14_01_VM_TRANSLATE'];if(kind==='subtopic')block.subtopicIds=['RL_ST_UNKNOWN'];if(kind==='source')block.sourceIds=['missing'];if(kind==='precision')projection.sources.find(s=>s.id===block.sourceIds[0])!.precision='EXACT_PAGE';if(kind==='old-lecture')projection.sources.find(s=>s.id===block.sourceIds[0])!.documentId='RL_LEC_08';if(kind==='duplicate-card')d.topics[0].cards[1].id=d.topics[0].cards[0].id;if(kind==='card-coverage')d.topics[0].cards=[];if(kind==='extra-score')Object.assign(d.topics[0].cards[0],{mastery:1});if(kind==='proof-grade')Object.assign(d.topics[0].guided[0],{earned:1});if(kind==='reference-missing')d.topics[0].guided[0].reference=[];if(kind==='duplicate-field')d.topics[0].guided[0].fields.push(d.topics[0].guided[0].fields[0]);if(kind==='assessment-source')Object.assign(d.exercises[0].source,{kind:'ASSESSMENT'});if(kind==='extra-mapping')Object.assign(d.exercises[0],{questionRef:'RL_MID_2023_Q1'});if(kind==='invalid-reference')d.exercises[0].reference={kind:'text',value:'a proof'};if(kind==='missing-class')d.coverage.pop();if(kind==='unlinked-class')d.coverage.find(c=>c.category==='A')!.exerciseIds=[];if(kind==='tool-scope')d.tools[0].skillIds=['RL_SK02_01_NL_TO_FOL'];
  expect(()=>validateRL(d,projection)).toThrow();
 });
 it.each(['lesson','block','card','guide','intro-guide','exercise','tool','classification','policy'] as const)('rejects silent changes to published %s',kind=>{const d=structuredClone(data);if(kind==='lesson')d.topics[0].lesson.version='2';if(kind==='block')d.topics[0].lesson.blocks[0].paragraphs[0]+=' changed';if(kind==='card')d.topics[0].cards[0].answer+=' changed';if(kind==='guide')d.topics[0].guided[0].reference[0]+=' changed';if(kind==='intro-guide')d.introGuided[0].prompt+=' changed';if(kind==='exercise')d.exercises[0].prompt+=' changed';if(kind==='tool')d.tools[0].assumptions+=' changed';if(kind==='classification')d.coverage[0].reason+=' changed';if(kind==='policy')d.policy.purpose+=' changed';expect(()=>checkRLLocks(d,readRL('content-lock.json'))).toThrow('published version changed');});
 it('all open constructions/proofs have an unscored guide; guides are never registered graders',()=>{for(const c of data.coverage.filter(c=>['B','C'].includes(c.category)))expect(c.guidedIds.length).toBeGreaterThan(0);for(const g of [...data.introGuided,...data.topics.flatMap(t=>t.guided)]){expect(data.exercises.some(e=>e.id===g.id)).toBe(false);expect(g).not.toHaveProperty('grader');expect(g).not.toHaveProperty('score');}const open={...data.exercises[0],task:{kind:'open-proof'}} as unknown as RLExercise;expect(gradeRLResponse(open,{kind:'text',value:'assume arbitrary induction therefore proven'})).toMatchObject({status:'NOT_AUTOGRADABLE'});expect(gradeRLResponse(open,{kind:'text',value:'proof'})).not.toHaveProperty('earned');});
 it('capabilities preserve canonical order and have no learner state',()=>{const c=rlCapabilities(data,topicStudy);expect(c.map(t=>t.topicId)).toEqual(topicStudy.topics.filter(t=>t.subjectId==='CSE1300_RL').map(t=>t.id));expect(canonical(c)).not.toMatch(/mastery|percentage|readiness|completed/);});
 it('direct Vite builds use the same mandatory R&L validator',()=>{const guard=rlBuildGuard(()=>{throw new Error('invalid RL content');});expect(guard.buildStart as ()=>void).toThrow('invalid RL content');});
 it('self-review: tool IDs cannot be reassigned to a different topic while moving their coverage links',()=>{const d=structuredClone(data);const a=d.tools[0].id,b=d.tools[1].id;d.tools[0].id=b;d.tools[1].id=a;d.coverage.forEach(c=>{if(c.toolId===a)c.toolId=b;else if(c.toolId===b)c.toolId=a;});expect(()=>validateRL(d,topicStudy)).toThrow();});
});
describe('R&L source authorization and puzzle safety',()=>{
 const guides=[...data.introGuided,...data.topics.flatMap(t=>t.guided)];
 it('all99 uncertain mappings remain blocked and135 broad mappings cannot credit child skills',()=>{expect(checkRLSourcePolicy(data.policy,data.exercises,guides)).toEqual({uncertainMappings:99,broadMappings:135,puzzles:1});});
 it.each(['can_generate_variants','historical_topic_frequency_eligible','historical_skill_frequency_eligible','exam_readiness_eligible','skill_mastery_update_policy'] as const)('rejects unverified promotion via %s',field=>{const pack=readRLCanonicalPack(),q=pack.assessment_model.assessments.filter(a=>a.subject_id==='CSE1300_RL').flatMap(a=>a.question_map).find(q=>q.mapping_granularity==='UNVERIFIED_OR_DRILL_ONLY')!;if(field==='skill_mastery_update_policy')q[field]='UPDATE_ONLY_LISTED_SKILLS_AFTER_VALIDATED_ATTEMPT';else q[field]=true;expect(()=>checkRLSourcePolicy(data.policy,data.exercises,guides,pack)).toThrow();});
 it('rejects broad evidence promoted to child-skill evidence',()=>{const pack=readRLCanonicalPack(),q=pack.assessment_model.assessments.filter(a=>a.subject_id==='CSE1300_RL').flatMap(a=>a.question_map).find(q=>q.mapping_granularity==='TOPIC_LEVEL_BROAD')!;q.historical_skill_frequency_eligible=true;expect(()=>checkRLSourcePolicy(data.policy,data.exercises,guides,pack)).toThrow();});
 it('rejects unverified or historical puzzle authorization and missing unscored justification',()=>{for(const key of ['question_ref','evidence_era','mapping_granularity'] as const){const policy=structuredClone(data.policy);policy.puzzles[0].mapping[key]='UNVERIFIED_OR_DRILL_ONLY';expect(()=>checkRLSourcePolicy(policy,data.exercises,guides)).toThrow();}expect(()=>checkRLSourcePolicy(data.policy,data.exercises,[])).toThrow();});
 it('the new puzzle has one complete solution; deleting a constraint yields multiple and cannot pass',()=>{expect(puzzleSolutions(data.policy.puzzles[0].instance)).toEqual([{A:3,B:2,C:4,D:1}]);const policy=structuredClone(data.policy);policy.puzzles[0].instance.constraints.pop();expect(puzzleSolutions(policy.puzzles[0].instance).length).toBeGreaterThan(1);expect(()=>checkRLSourcePolicy(policy,data.exercises,guides)).toThrow('exactly one');});
});
