import {describe,expect,it} from 'vitest';
import type {ActionKind,Recommendation} from '../src/adaptive/engine';
import {claimRecommendationImpression,recommendationImpressionKey,recommendStudyMethod,studyMethodSelectionSource} from '../src/adaptive/study-method-recommendation';
import {parseStudyMethod} from '../src/adaptive/study-methods';
import {languages,loadMessages} from '../src/i18n/messages';
const action=(kind:ActionKind,minutes=10,topicId='T1'):Recommendation=>({id:kind+topicId,title:kind,topicId,subjectId:'C',skillIds:[],kind,minutes,durationSource:'Notedra estimate',to:`/${topicId}/${kind}`,reason:'fixed',priority:0,basisSkillId:'s'});
const input=(overrides={})=>({minutes:30,subjectId:'C',eligibleTopicCount:3,usableTopicCount:1,hasCourseActivity:false,hasContextActivity:false,hasRecentMistakes:false,candidates:[action('practice'),action('flashcards'),action('retry')],...overrides});
describe('study method recommendation',()=>{
 it.each([30,45,60])('recommends Pomodoro to a new learner at %i minutes',minutes=>expect(recommendStudyMethod(input({minutes})).methodId).toBe('pomodoro'));
 it('falls back to Flexible when Pomodoro is unavailable',()=>expect(recommendStudyMethod(input({minutes:15}))).toMatchObject({methodId:'flexible',reasonCode:'flexible-fallback'}));
 it('recommends Active Recall from existing activity or mistake evidence',()=>{expect(recommendStudyMethod(input({hasCourseActivity:true,hasContextActivity:true}))).toMatchObject({methodId:'active-recall',reasonCode:'retrieval'});expect(recommendStudyMethod(input({hasCourseActivity:true,hasRecentMistakes:true})).methodId).toBe('active-recall')});
 it('prioritizes complex work over 52/17',()=>{expect(recommendStudyMethod(input({minutes:90,candidates:[action('coding',45),action('learn',25)]}))).toMatchObject({methodId:'time-blocking',reasonCode:'complex-work'});expect(recommendStudyMethod(input({minutes:90,candidates:[action('learn',30),action('learn',30),action('review',30)]}))).toMatchObject({methodId:'52-17',reasonCode:'deep-focus'})});
 it('recommends Interleaving only for an active whole course',()=>{expect(recommendStudyMethod(input({hasCourseActivity:true,usableTopicCount:3}))).toMatchObject({methodId:'interleaving',reasonCode:'multi-topic'});expect(recommendStudyMethod(input({hasCourseActivity:false,usableTopicCount:3})).methodId).not.toBe('interleaving');expect(recommendStudyMethod(input({topicId:'T1',hasCourseActivity:true,usableTopicCount:3})).methodId).not.toBe('interleaving')});
 it('never overrides a valid explicit URL method',()=>expect(parseStudyMethod('active-recall')).toBe('active-recall'));
 it('fires one impression per meaningful recommendation state',()=>{const r=recommendStudyMethod(input()),seen=new Set<string>(),first=recommendationImpressionKey(input(),r),changed=recommendationImpressionKey(input({minutes:45}),r);expect(claimRecommendationImpression(seen,first)).toBe(true);expect(claimRecommendationImpression(seen,first)).toBe(false);expect(claimRecommendationImpression(seen,changed)).toBe(true)});
 it('classifies recommended selections and manual overrides',()=>{expect(studyMethodSelectionSource('pomodoro','pomodoro')).toBe('recommended');expect(studyMethodSelectionSource('active-recall','pomodoro')).toBe('manual')});
 it('keeps every localized recommendation reason to one concise sentence',async()=>{const keys=['studyMethod.reason.newLearner','studyMethod.reason.practiceShort','studyMethod.reason.deepFocus','studyMethod.reason.complexWork','studyMethod.reason.retrieval','studyMethod.reason.multiTopic','studyMethod.reason.flexibleFallback'] as const;for(const language of languages){const messages=await loadMessages(language);for(const key of keys){const copy=messages[key]!;expect(copy).not.toMatch(/[\r\n]/);expect(copy.length).toBeLessThanOrEqual(100)}}});
});
