import type {Aggregate,Readiness} from './types';
import {useI18n} from '../i18n/i18n';
export function MasteryCard({value}:{value:Aggregate}){
 const {t}=useI18n();
 return <article className="progress-card progress-mastery"><div className="progress-mastery-heading"><h3>{t('learning.mastery')}</h3><p className="progress-number">{value.index===null?t('learning.notEnoughPractice'):`${value.index} / 100`}</p></div>
  <div className="progress-mastery-bar" role="progressbar" aria-label={t('learning.mastery')} aria-valuemin={0} aria-valuemax={100} aria-valuenow={value.index??undefined} aria-valuetext={value.index===null?t('learning.notEnoughPractice'):`${value.index} / 100`}><span style={{width:`${value.index??0}%`}}/></div>
  <div className="progress-mastery-meta"><p><strong>{t('learning.confidence',{confidence:value.confidence})}</strong></p><p>{t('learning.recentSkills',{covered:value.covered,total:value.total,recent:value.recent})}</p></div>
  <details><summary>{t('learning.calculated')}</summary><div className="progress-method"><p>{t('learning.method')}</p><p>Strongest recorded skills: {value.strongest.join('; ')||t('learning.notEnoughPractice')}.</p><p>Recent mistakes to review: {value.review.join('; ')||t('learning.noneRecorded')}.</p>{value.why.map(p=><p key={p}>{p}</p>)}<p>{t('learning.separateReadiness')}</p></div></details></article>;
}
export function ReadinessCard({value}:{value:Readiness}){
 const openLabel=value.openState==='Limited'?'Not assessed yet':value.openState;
 return <article className="progress-card"><h3>Exam Readiness</h3><p className="progress-number">{value.index===null?'Not enough exam practice yet':`${value.index} / 100`}</p><p><strong>Confidence: {value.confidence}</strong> <span>— how much reliable exam practice supports this estimate.</span></p><p>Topics assessed: {value.objectiveTopics} / {value.totalTopics}. Topics practiced: {value.practisedTopics} / {value.totalTopics} (including work that is not automatically graded).</p><p>Open reasoning: {openLabel} · {value.openMechanisms} different mechanisms practiced; correctness is not automatically verified.</p>{value.courseId==='CSE1100_IP'&&<p>Integrated programming practice: {value.integrated?'Completed, not automatically graded':'Not practiced yet'}</p>}<details><summary>How is this calculated?</summary><p>Exam Readiness reflects the strength and breadth of recent exam-relevant practice. It does not estimate your exam result or chance of passing.</p>{value.why.map(p=><p key={p}>{p}</p>)}<h4>What to practice next</h4><ul>{value.gaps.map(p=><li key={p}>{p}</li>)}</ul></details></article>;
}
