import {useState} from 'react';
import {displayFol,evaluateFol,type FolFormula,type FolTerm,type FiniteStructure} from './logic';
const domain=['a','b','c'];
const x:FolTerm={kind:'variable',name:'x'},y:FolTerm={kind:'variable',name:'y'};
const px:FolFormula={kind:'predicate',name:'P',args:[x]},rxy:FolFormula={kind:'predicate',name:'R',args:[x,y]};
const formulas:Record<string,FolFormula>={all:{kind:'forall',variable:'x',body:px},some:{kind:'exists',variable:'x',body:px},notAll:{kind:'not',operand:{kind:'forall',variable:'x',body:px}},eachSome:{kind:'forall',variable:'x',body:{kind:'exists',variable:'y',body:rxy}},someAll:{kind:'exists',variable:'y',body:{kind:'forall',variable:'x',body:rxy}},named:{kind:'predicate',name:'P',args:[{kind:'constant',name:'k'}]},function:{kind:'forall',variable:'x',body:{kind:'predicate',name:'R',args:[x,{kind:'function',name:'f',args:[x]}]}}};
const plain:Record<string,string>={all:'Every object has property P.',some:'At least one object has property P.',notAll:'It is not the case that every object has property P.',eachSome:'For every object x, there is an object y such that R(x, y) holds. The witness y may depend on x.',someAll:'There is one object y such that R(x, y) holds for every object x. The same witness must work for all x.',named:'The object named by k has property P.',function:'For every object x, the pair (x, f(x)) is in R.'};
const initialPairs=['a:b','b:c','c:a'];
export default function FolWorkspace(){
 const [members,setMembers]=useState(['a']),[pairs,setPairs]=useState(initialPairs),[selected,setSelected]=useState('eachSome');
 const toggle=(values:string[],value:string)=>values.includes(value)?values.filter(v=>v!==value):[...values,value];
 const structure:FiniteStructure={domain,constants:{k:'a'},predicates:{P:{arity:1,tuples:members.map(v=>[v])},R:{arity:2,tuples:pairs.map(v=>v.split(':'))}},functions:{f:{arity:1,entries:domain.map((v,i)=>({args:[v],value:domain[(i+1)%3]}))}}};
 const formula=formulas[selected],result=evaluateFol(formula,structure);
 return <><p>Domain D = {'{a, b, c}'}. The named constant k denotes a. The total function f maps a ↦ b, b ↦ c, c ↦ a. Objects are abstract labels; no spatial geometry is assumed.</p><fieldset><legend>Unary predicate P: select its members</legend><div className="ds-rl-set-controls">{domain.map(v=><label key={v}><input type="checkbox" checked={members.includes(v)} onChange={()=>setMembers(toggle(members,v))}/>P({v})</label>)}</div></fieldset><fieldset><legend>Binary relation R: select its ordered pairs</legend><div className="ds-rl-set-controls">{domain.flatMap(a=>domain.map(b=><label key={`${a}:${b}`}><input type="checkbox" checked={pairs.includes(`${a}:${b}`)} onChange={()=>setPairs(toggle(pairs,`${a}:${b}`))}/>R({a}, {b})</label>))}</div></fieldset><div className="ds-rl-fields"><label>Formula in this structure<select value={selected} onChange={e=>setSelected(e.target.value)}>{Object.entries(formulas).map(([id,f])=><option key={id} value={id}>{displayFol(f)}</option>)}</select></label></div><div className="ds-rl-result"><pre>{displayFol(formula)}{'\n'}{result.value?'TRUE':'FALSE'} in this structure</pre><p>{plain[selected]}</p><p>P = {'{'+members.join(', ')+'}'}. R = {'{'+pairs.map(p=>'('+p.replace(':',', ')+')').join(', ')+'}'}. Empty predicate extensions are allowed; the domain remains nonempty.</p><h3>Quantifier evidence</h3>{result.quantifiers.length===0?<p>This formula contains no quantifier. Evaluate P at the object denoted by k.</p>:result.quantifiers.map((e,i)=><article className="ds-lesson-block" key={i}><h4>{e.kind==='forall'?'For every':'There exists'} {e.variable}{Object.keys(e.outerAssignment).length>0?' with '+Object.entries(e.outerAssignment).map(([v,o])=>`${v} = ${o}`).join(', '):''}</h4><p>{e.results.map(r=>`${e.variable} = ${r.object}: ${r.value?'true':'false'}`).join(' · ')}</p><p>{e.kind==='exists'?`Witnesses: ${e.witnesses.join(', ')||'none'}.`:`Refuting assignments: ${e.counterexamples.join(', ')||'none'}.`}</p></article>)}<p>These results decide only the displayed formula in this finite interpretation. A true result here does not prove universal validity.</p></div><button className="ds-button" onClick={()=>{setMembers(['a']);setPairs(initialPairs);setSelected('eachSome');}}>Reset finite structure</button></>;
}
