import {useState} from 'react';
import {AuthoredSources} from '../topic-study/AuthoredViews';
import type {GuidedActivity} from './types';
export function GuidedPractice({activities,headingId="rl-guided-heading"}:{activities:GuidedActivity[];headingId?:string}){
 return <section className="ds-section ds-study-reading" aria-labelledby={headingId}><h2 id={headingId}>Guided reasoning · unscored self-check</h2><p>Write an attempt before revealing the criteria. These prompts may have many valid responses. No automatic correctness, numeric score or academic evidence is assigned.</p>{activities.map(activity=><GuidedAttempt key={activity.id} activity={activity}/>)}</section>;
}
function GuidedAttempt({activity}:{activity:GuidedActivity}){
 const [answers,setAnswers]=useState<Record<string,string>>({});const [revealed,setRevealed]=useState(false);
 return <article className="ds-lesson-block ds-rl-guided"><h3>{activity.title}</h3><p>{activity.prompt}</p><div className="ds-rl-proof-fields">{activity.fields.map(field=><label key={field.id} htmlFor={`${activity.id}-${field.id}`}>{field.label}<textarea id={`${activity.id}-${field.id}`} rows={3} maxLength={8000} placeholder={field.placeholder} value={answers[field.id]??''} onChange={e=>setAnswers({...answers,[field.id]:e.target.value})}/></label>)}</div><p className="ds-study-muted">Working notes stay on this page only. Copy them before navigating or reloading; they are not saved as a submitted Practice attempt.</p><div className="ds-storage-actions"><button className="ds-button ds-practice-primary" aria-expanded={revealed} aria-controls={`${activity.id}-criteria`} onClick={()=>setRevealed(v=>!v)}>{revealed?'Hide criteria and reference':'Reveal criteria and reference'}</button><button className="ds-button" onClick={()=>{setAnswers({});setRevealed(false);}}>Reset working notes<span className="sr-only">: {activity.title}</span></button></div><div id={`${activity.id}-criteria`} hidden={!revealed}><h4>Self-check criteria</h4><ul>{activity.rubric.map((criterion,i)=><li key={i}>{criterion}</li>)}</ul><h4>Reference reasoning</h4>{activity.reference.map((p,i)=><p key={i}>{p}</p>)}<p>Use this to review your reasoning. Revealing or satisfying a checklist does not verify a proof.</p></div><AuthoredSources item={activity}/></article>;
}
