import {useState} from 'react';
import {analyzeArgument,analyzeFormula,compareEquivalent,displayProp,evaluateProp,propVariables,type PropFormula,type BinaryConnective} from './logic';
const p:PropFormula={kind:'variable',name:'p'},q:PropFormula={kind:'variable',name:'q'};
const atoms:Record<string,PropFormula>={p,q,'not-p':{kind:'not',operand:p},'not-q':{kind:'not',operand:q}};
const atomLabels:Record<string,string>={p:'p',q:'q','not-p':'¬p','not-q':'¬q'};
const alternatives:Record<string,PropFormula>={implication:{kind:'or',left:{kind:'not',operand:p},right:q},converse:{kind:'implies',left:q,right:p},conjunction:{kind:'and',left:p,right:q},biconditional:{kind:'iff',left:p,right:q}};
const tf=(value:boolean)=>value?'T':'F';
const assignment=(values:Record<string,boolean>)=>Object.entries(values).map(([key,value])=>`${key} = ${tf(value)}`).join(', ');
export default function PropositionWorkspace(){
 const [left,setLeft]=useState('p'),[right,setRight]=useState('q'),[operator,setOperator]=useState<BinaryConnective>('implies'),[negated,setNegated]=useState(false),[comparison,setComparison]=useState('implication'),[pValue,setPValue]=useState(false),[qValue,setQValue]=useState(false),[argumentMode,setArgumentMode]=useState('modus-ponens');
 const inner:PropFormula={kind:operator,left:atoms[left],right:atoms[right]};const formula:PropFormula=negated?{kind:'not',operand:inner}:inner;
 const order=propVariables(formula).sort(),analysis=analyzeFormula(formula,order),other=alternatives[comparison];
 const equivalence=compareEquivalent(formula,other,[...new Set([...order,...propVariables(other)])].sort());
 const implication:PropFormula={kind:'implies',left:p,right:q};
 const premises=argumentMode==='modus-ponens'?[implication,p]:argumentMode==='affirm-consequent'?[implication,q]:[p,{kind:'not',operand:p} as PropFormula];
 const conclusion=argumentMode==='affirm-consequent'?p:q;const validity=analyzeArgument(premises,conclusion,['p','q']);
 return <>
 <div className="ds-rl-fields"><label>Left operand<select value={left} onChange={e=>setLeft(e.target.value)}>{Object.keys(atoms).map(key=><option key={key} value={key}>{atomLabels[key]}</option>)}</select></label><label>Connective<select value={operator} onChange={e=>setOperator(e.target.value as BinaryConnective)}><option value="and">AND ∧</option><option value="or">OR ∨</option><option value="implies">IMPLIES →</option><option value="iff">IFF ↔</option></select></label><label>Right operand<select value={right} onChange={e=>setRight(e.target.value)}>{Object.keys(atoms).map(key=><option key={key} value={key}>{atomLabels[key]}</option>)}</select></label></div>
 <div className="ds-rl-set-controls"><label><input type="checkbox" checked={negated} onChange={e=>setNegated(e.target.checked)}/>Negate the whole formula</label><label><input type="checkbox" checked={pValue} onChange={e=>setPValue(e.target.checked)}/>p is true</label><label><input type="checkbox" checked={qValue} onChange={e=>setQValue(e.target.checked)}/>q is true</label></div>
 <div className="ds-rl-result"><h3>Formula and valuation</h3><pre>{displayProp(formula)}{'\n'}{assignment({p:pValue,q:qValue})} → {tf(evaluateProp(formula,{p:pValue,q:qValue}))}</pre><p>Every binary connective is parenthesized. T means true; F means false. Truth-table variables: {order.join(', ')}. False precedes true; the last variable changes fastest.</p><div className="ds-study-table-wrap"><table><caption>Full truth table</caption><thead><tr>{order.map(v=><th key={v} scope="col">{v}</th>)}<th scope="col">{displayProp(formula)}</th></tr></thead><tbody>{analysis.rows.map((row,i)=><tr key={i}>{order.map(v=><td key={v}>{tf(row.valuation[v])}</td>)}<td>{tf(row.value)}</td></tr>)}</tbody></table></div><dl><div><dt>Satisfiable</dt><dd>{analysis.satisfiable?'Yes':'No'}</dd></div><div><dt>Tautology</dt><dd>{analysis.tautology?'Yes':'No'}</dd></div><div><dt>Contradiction</dt><dd>{analysis.contradiction?'Yes':'No'}</dd></div></dl>
 <h3>Semantic equivalence</h3><div className="ds-rl-fields"><label>Compare with<select value={comparison} onChange={e=>setComparison(e.target.value)}>{Object.entries(alternatives).map(([id,f])=><option key={id} value={id}>{displayProp(f)}</option>)}</select></label></div><p>{equivalence.equivalent?'Equivalent: both formulas agree on every valuation.':`Not equivalent: ${assignment(equivalence.counterexample!.valuation)} makes the constructed formula ${tf(equivalence.counterexample!.left)} and the comparison ${tf(equivalence.counterexample!.right)}.`}</p>
 <h3>Argument validity</h3><p>Validity asks whether all premises can be true while the conclusion is false. It is different from equivalence of two formulas.</p><div className="ds-rl-fields"><label>Argument to investigate<select value={argumentMode} onChange={e=>setArgumentMode(e.target.value)}><option value="modus-ponens">p → q; p; therefore q</option><option value="affirm-consequent">p → q; q; therefore p</option><option value="explosion">p; ¬p; therefore q</option></select></label></div><pre>Premises: {premises.map(displayProp).join('; ')}{'\n'}Conclusion: {displayProp(conclusion)}</pre><p>{validity.valid?'Valid: there is no valuation with all premises true and the conclusion false.':`Invalid: ${assignment(validity.counterexample!.valuation)} makes all premises true and the conclusion false.`}{!validity.satisfiablePremises&&' The premises cannot all be true; validity is vacuous (explosion), not evidence that q is a tautology.'}</p></div>
 <button className="ds-button" onClick={()=>{setLeft('p');setRight('q');setOperator('implies');setNegated(false);setComparison('implication');setPValue(false);setQValue(false);setArgumentMode('modus-ponens');}}>Reset logic workspace</button>
 </>;
}
