import {useState} from 'react';
import {analyzeTree,analyzeGraph,checkTopologicalOrder,type BinaryTree} from './models';
const leaf=(label:string):BinaryTree=>({label,left:null,right:null});
const trees:Record<string,BinaryTree|null>={branch:{label:'A',left:{label:'B',left:leaf('D'),right:leaf('E')},right:leaf('C')},chain:{label:'A',left:null,right:{label:'B',left:leaf('C'),right:null}},empty:null};
const vertices=['A','B','C','D'];const initialEdges=['A:B','A:C','B:D','C:D'];
export default function TreeGraphWorkspace(){
 const [treeId,setTreeId]=useState('branch'),[edges,setEdges]=useState(initialEdges),[order,setOrder]=useState(vertices);
 const tree=trees[treeId],analysis=analyzeTree(tree),structure:{label:string;left:string;right:string}[]=[];
 function visit(node:BinaryTree|null){if(!node)return;structure.push({label:node.label,left:node.left?.label??'empty',right:node.right?.label??'empty'});visit(node.left);visit(node.right);}visit(tree);
 const graph={vertices,edges:edges.map(edge=>edge.split(':') as [string,string])};const graphResult=analyzeGraph(graph),validOrder=checkTopologicalOrder(graph,order);
 return <><h3>Ordered binary trees</h3><div className="ds-rl-fields"><label>Tree structure<select value={treeId} onChange={e=>setTreeId(e.target.value)}><option value="branch">A with left B(D, E), right C</option><option value="chain">A with right B; B with left C</option><option value="empty">Empty tree</option></select></label></div><p>Child order is semantic: left before right. Node labels are distinct. Height counts edges; a leaf has height 0 and the empty tree has height −1.</p><div className="ds-study-table-wrap"><table><caption>Textual tree structure · root {tree?.label??'empty'}</caption><thead><tr><th scope="col">Node</th><th scope="col">Left child</th><th scope="col">Right child</th></tr></thead><tbody>{structure.map(row=><tr key={row.label}><th scope="row">{row.label}</th><td>{row.left}</td><td>{row.right}</td></tr>)}</tbody></table></div><div className="ds-rl-result"><pre>Preorder (root, left, right): {analysis.preorder.join(' ')||'empty'}{'\n'}Inorder (left, root, right): {analysis.inorder.join(' ')||'empty'}{'\n'}Postorder (left, right, root): {analysis.postorder.join(' ')||'empty'}{'\n'}Nodes: {analysis.nodeCount} · Leaves: {analysis.leafCount} · Height: {analysis.height}</pre><p>Recursive node count: N(empty) = 0; N(node(L, R)) = 1 + N(L) + N(R). Leaf count is 1 at a leaf, 0 at empty, and otherwise the sum of the two child counts.</p></div><h3>Directed graph and topological ordering</h3><p>Vertices are A, B, C, D. A selected pair X → Y means X must precede Y in a topological order. All edges are listed textually; drawing positions do not affect the result.</p><fieldset><legend>Graph edges</legend><div className="ds-rl-set-controls">{vertices.flatMap(a=>vertices.filter(b=>a!==b).map(b=><label key={`${a}:${b}`}><input type="checkbox" checked={edges.includes(`${a}:${b}`)} onChange={()=>setEdges(edges.includes(`${a}:${b}`)?edges.filter(v=>v!==`${a}:${b}`):[...edges,`${a}:${b}`])}/>{a} → {b}</label>))}</div></fieldset><div className="ds-rl-result"><p>{graphResult.acyclic?`DAG. One valid order: ${graphResult.topologicalOrder!.join(' → ')}. ${graphResult.unique?'The order is unique.':'Multiple valid orders exist.'}`:`Cycle: ${graphResult.cycle!.join(' → ')}. No topological order exists.`}</p></div><div className="ds-rl-fields">{order.map((value,index)=><label key={index}>Position {index+1}<select value={value} onChange={e=>setOrder(order.map((old,i)=>i===index?e.target.value:old))}>{vertices.map(v=><option key={v}>{v}</option>)}</select></label>)}</div><p>{validOrder?'This order satisfies every edge constraint.':'This order does not satisfy the constraints. Use each vertex exactly once, and place the source of every edge before its target.'} Every satisfying order is accepted; this check does not require matching the displayed example.</p><button className="ds-button" onClick={()=>{setTreeId('branch');setEdges(initialEdges);setOrder(vertices);}}>Reset tree and graph</button></>;
}
