import {useEffect} from 'react';
import {Link} from 'react-router';
import {ShellIcon, type ShellIconName} from '../shell/ShellIcon';
import './landing.css';

const description='Turn course material into active, measurable study with authored practice, clear feedback, Study Paths and evidence of progress.';
const workflow=[['01','Learn','Start from structured course material.'],['02','Practise','Work through authored questions and interactive tools.'],['03','Understand mistakes','Return to the exact skill that needs work.'],['04','Build evidence','Keep mastery and exam readiness clear and separate.'],['05','Prepare for exams','Combine topics in focused, exam-style practice.']];
const strengths:[ShellIconName,string,string][]=[['practice','Authored practice','Questions are designed around course concepts, not generated to fill a feed.'],['mistakes','Deterministic feedback','Where supported, answers produce explainable, repeatable feedback.'],['calendar','Study Path','Turn current evidence into a focused sequence for the time you have.'],['progress','Mastery and readiness','Understand topic learning separately from exam preparation.'],['logic','Prerequisite maps','See how foundational skills connect before moving forward.'],['cpu','Interactive tools','Step through x86-64 execution and inspect registers, stack frames and calls.']];

export function LandingPage(){
  const entry='/dashboard';
  useEffect(()=>{document.title='Notedra — Active, measurable study';document.querySelector<HTMLMetaElement>('meta[name="description"]')?.setAttribute('content',description);window.scrollTo(0,0);},[]);
  return <div className="landing">
    <a className="landing-skip" href="#landing-content">Skip to content</a>
    <header className="landing-header"><Link className="landing-brand" to="/" aria-label="Notedra home"><span><ShellIcon name="book" size={21}/></span>Notedra</Link><nav aria-label="Public navigation"><a href="#how-it-works">How it works</a><a href="#what-makes-it-different">Why Notedra</a><a href="#focused-study">Focused study</a></nav><Link className="landing-header-cta" to={entry}>Explore Notedra <ShellIcon name="arrow" size={16}/></Link></header>
    <main id="landing-content">
      <section className="landing-hero" aria-labelledby="landing-title"><div><p className="landing-eyebrow">A study system, not another chat window</p><h1 id="landing-title">Study what matters.<br/><em>Know what you actually understand.</em></h1><p className="landing-lede">Notedra connects course content, practice, feedback and progress into one study system.</p><div className="landing-actions"><Link className="landing-primary" to={entry}>Explore Notedra <ShellIcon name="arrow" size={18}/></Link><a href="#how-it-works">See how it works</a></div><p className="landing-beta-note">Free to explore during beta. No payment details required.</p></div><div className="landing-hero-visual" aria-label="Preview of the Notedra Dashboard"><div className="preview-window"><div className="preview-top"><span className="preview-mark"><ShellIcon name="book" size={17}/></span><b>Dashboard</b><span className="preview-avatar">S</span></div><div className="preview-body"><p>NEXT BEST ACTION</p><div className="preview-action"><div><span>Recommended next</span><strong>Review Propositional Logic</strong><small>You have recent mistakes on this skill.</small></div><i><ShellIcon name="arrow" size={18}/></i></div><div className="preview-grid"><div><ShellIcon name="progress"/><small>Learning evidence</small><b>Mastery</b></div><div><ShellIcon name="exam"/><small>Exam preparation</small><b>Readiness</b></div></div></div></div><span className="orbit o1">practice</span><span className="orbit o2">feedback</span><span className="orbit o3">progress</span></div></section>
      <section className="landing-flow" id="how-it-works" aria-labelledby="flow-title"><Heading eyebrow="One connected loop" title="Material becomes action, not another open tab." id="flow-title">Move from learning to exam preparation without losing the evidence you build along the way.</Heading><ol>{workflow.map(([number,title,copy])=><li key={number}><span>{number}</span><strong>{title}</strong><p>{copy}</p></li>)}</ol></section>
      <section className="landing-difference" id="what-makes-it-different" aria-labelledby="difference-title"><Heading eyebrow="Built for deliberate study" title="More than answers. A system for understanding." id="difference-title">Notedra does not pretend that uploading material is the same as learning it. Every surface supports a visible study decision.</Heading><div className="landing-strengths">{strengths.map(([icon,title,copy])=><article key={title}><span><ShellIcon name={icon}/></span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
      <section className="landing-surfaces" aria-labelledby="surfaces-title"><Heading eyebrow="Inside Notedra" title="From a single next step to the wider course map." id="surfaces-title"/><div className="surface-grid"><Surface icon="practice" label="Practice" badge="Authored" title="Work the concept, then inspect the feedback."><div className="answer-lines"><i/><i/><i/></div><p className="surface-feedback">Clear reasoning, not just a score.</p></Surface><Surface icon="calendar" label="Study Path" badge="15 min" title="A focused sequence grounded in your activity."><ol className="path-list"><li><b>1</b> Review a prerequisite</li><li><b>2</b> Practise the current skill</li><li><b>3</b> Check understanding</li></ol></Surface><Surface icon="cpu" label="Assembly Visualizer" badge="Interactive" title="See machine state change instruction by instruction." dark><pre><code><span>movq</span> $7, %rax{`\n`}<span>pushq</span> %rax{`\n`}<span>callq</span> example</code></pre></Surface></div></section>
      <section className="landing-focus" id="focused-study" aria-labelledby="focused-study-title"><div><p className="landing-eyebrow">Built around real learning</p><h2 id="focused-study-title">Built for focused university study.</h2></div><div><p>Learn concepts, practise with real exercises, understand mistakes and turn your work into a clear study path.</p><small>Notedra is an independent educational platform and is not an official service of any university.</small></div></section>
      <section className="landing-final"><p className="landing-eyebrow">Currently in beta</p><h2>Turn the next study session into evidence.</h2><p>Explore the courses, try authored practice and see how the pieces connect.</p><Link className="landing-primary" to={entry}>Explore Notedra <ShellIcon name="arrow" size={18}/></Link></section>
    </main>
    <footer className="landing-footer"><Link className="landing-brand" to="/"><span><ShellIcon name="book" size={18}/></span>Notedra</Link><p>Independent study support for computer science students.</p><nav aria-label="Legal"><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></nav></footer>
  </div>;
}
function Heading({eyebrow,title,id,children}:{eyebrow:string;title:string;id:string;children?:string}){return <div className="landing-heading"><p className="landing-eyebrow">{eyebrow}</p><h2 id={id}>{title}</h2>{children&&<p>{children}</p>}</div>}
function Surface({icon,label,badge,title,dark=false,children}:{icon:ShellIconName;label:string;badge:string;title:string;dark?:boolean;children:React.ReactNode}){return <article className={dark?'surface dark':''}><div className="surface-head"><span><ShellIcon name={icon}/> {label}</span><small>{badge}</small></div><h3>{title}</h3>{children}</article>}
