import {useState} from 'react';
import {Sources,CanonicalLink} from '../topic-study/AcademicViews';
import {addressAliases,amdahl,cacheFields,cacheTrace,customFloat,fixedPoint,interleave,isaBudget,memoryOrganization,pipelineSchedule,translateVM,truthTable,vmLayout,type BooleanOperation,type CacheStep} from './models';
interface Tool {id:string;name:string;topicId:string;skillIds:string[];sourceIds:string[];summary:string;assumptions:string;}
interface Field {key:string;label:string;initial:string;options?:[string,string][];}
interface Result {facts:[string,string][];table?:{caption:string;headers:string[];rows:string[][]};trace?:CacheStep[];}
const field=(key:string,label:string,initial:string,options?:[string,string][]):Field=>({key,label,initial,options});
const toggle:[string,string][]=[['yes','Yes'],['no','No']];
const specs:Record<string,Field[]>={
 boolean:[field('op','Boolean operation','and',[['and','AND'],['or','OR'],['xor','XOR'],['nand','NAND']])],
 representation:[field('bits','Fixed-point binary code','11010'),field('f','Fixed-point fractional bits','2'),field('signed','Signed fixed point','yes',toggle),field('sign','Float sign bit','0'),field('eb','Float exponent width','3'),field('fb','Float fraction width','3'),field('bias','Float exponent bias','2'),field('e','Float stored exponent (decimal)','4'),field('m','Float stored fraction (decimal)','3')],
 isa:[field('length','Instruction length (bits)','20'),field('regs','Register count','10'),field('fields','Register fields','2'),field('address','Address / immediate field (bits)','6')],
 address:[field('address','Eight-bit address (decimal or 0x hex)','0x24'),field('ignored','Ignored bits, comma-separated (0 is LSB)','0,3')],
 memory:[field('words','Target words','2048'),field('width','Bits per target word','16'),field('chipWords','Words per chip','512'),field('chipBits','Data bits per chip','4'),field('banks','Interleaved banks','4'),field('word','Word address for bank mapping','13')],
 cache:[field('bits','Address width (bits)','8'),field('block','Block size (bytes)','4'),field('sets','Number of sets','2'),field('ways','Ways per set','2'),field('addresses','Read addresses, comma-separated (decimal or 0x hex)','0,8,0,16,8')],
 pipeline:[field('forward','Forwarding enabled','yes',toggle)],
 amdahl:[field('s','Serial fraction of original time (0–1)','0.25'),field('p','Processors','3')],
 vm:[field('v','Virtual address bits','16'),field('p','Physical address bits','12'),field('o','Page offset bits','8'),field('entry','Page-table entry bytes','4'),field('address','Virtual byte address (decimal or 0x hex)','0x1234'),field('frame','Mapped physical frame (decimal)','7'),field('present','Entry present','yes',toggle),field('writable','Entry permits writes','yes',toggle),field('write','Requested access is a write','no',toggle)],
};
function number(value:string){if(!/^(?:-?\d+(?:\.\d+)?|0x[0-9a-f]+)$/i.test(value.trim()))throw new Error('Enter a number in the field’s stated format. Empty values are not zero.');const n=Number(value);if(!Number.isFinite(n))throw new Error('Enter a finite number.');return n;}
const display=(value:unknown)=>typeof value==='number'&&!Number.isFinite(value)?'Unbounded in this ideal model':String(value);
function facts(values:Record<string,unknown>):[string,string][]{return Object.entries(values).map(([k,v])=>[k,display(v)]);}
function calculate(id:string,v:Record<string,string>):Result{
 const n=(key:string)=>number(v[key]);const yes=(key:string)=>v[key]==='yes';
 if(id==='boolean')return {facts:[],table:{caption:'Complete two-input truth table',headers:['A','B','Output'],rows:truthTable(v.op as BooleanOperation).map(r=>[r.a,r.b,r.value].map(x=>x?'1':'0'))}};
 if(id==='representation'){const fixed=fixedPoint(v.bits.trim(),n('f'),yes('signed'));const fp=customFloat({exponentBits:n('eb'),fractionBits:n('fb'),bias:n('bias')},n('sign'),n('e'),n('m'));return {facts:facts({'Fixed value':fixed.value,'Fixed step':fixed.step,'Fixed minimum':fixed.minimum,'Fixed maximum':fixed.maximum,'Float value':fp.value,'Float significand':fp.significand,'Actual exponent':fp.actualExponent,'Float spacing at this exponent':fp.spacing,'Smallest positive float':fp.minimumPositive,'Largest finite float':fp.maximumFinite})};}
 if(id==='isa'){const r=isaBudget(n('length'),n('regs'),n('fields'),n('address'));return {facts:facts({'Bits per register field':r.registerBits,'Opcode bits':r.opcodeBits,'Opcode capacity':r.opcodeCapacity,'Unused codes per register field':r.unusedRegisterCodes})};}
 if(id==='address'){const ignored=v.ignored.trim()?v.ignored.split(',').map(number):[];const aliases=addressAliases(8,n('address'),ignored);return {facts:[['Alias count',String(aliases.length)],['Addresses',aliases.map(a=>'0x'+a.toString(16).padStart(2,'0').toUpperCase()).join(', ')]]};}
 if(id==='memory'){const r=memoryOrganization(n('words'),n('width'),n('chipWords'),n('chipBits')),bank=interleave(n('word'),n('banks'));return {facts:facts({'Chips required':r.chips,'Depth groups':r.depthGroups,'Parallel chips per group':r.parallelChips,'Chip address pins':r.chipAddressPins,'Chip data pins':r.chipDataPins,'Board word-address bits':r.boardAddressPins,'Total capacity (bits)':r.capacityBits,'Bank':bank.bank,'Row':bank.row})};}
 if(id==='cache'){const config={addressBits:n('bits'),blockBytes:n('block'),sets:n('sets'),ways:n('ways')};const addresses=v.addresses.split(',').map(number);const f=cacheFields(config,addresses[0]);return {facts:facts({'Offset bits':f.offsetBits,'Index bits':f.indexBits,'Tag bits':f.tagBits,'Data capacity (bytes)':f.dataBytes}),trace:cacheTrace(config,addresses)};}
 if(id==='pipeline'){const r=pipelineSchedule([{label:'ALU A',kind:'alu',dependencies:[]},{label:'ALU B ← A',kind:'alu',dependencies:[0]},{label:'Load C',kind:'load',dependencies:[]},{label:'ALU D ← C',kind:'alu',dependencies:[2]}],yes('forward'));return {facts:facts({'Total cycles':r.cycles,'Inserted wait cycles':r.stalls}),table:{caption:'Abstract dependency sequence — cycle number for each stage',headers:['Instruction','F','D','X','M','W'],rows:r.rows.map(r=>[r.label,...r.stages.map(String)])}};}
 if(id==='amdahl'){const r=amdahl(n('s'),n('p'));return {facts:facts({'Relative execution time':r.relativeTime,'Speedup':r.speedup,'Unlimited-processor speedup limit':r.upperLimit})};}
 if(id==='vm'){const config={virtualBits:n('v'),physicalBits:n('p'),pageBits:n('o'),entryBytes:n('entry')};const l=vmLayout(config),r=translateVM(config,n('address'),n('frame'),yes('present'),yes('writable'),yes('write'));return {facts:facts({'Page size (bytes)':l.pageBytes,'Virtual pages':l.pages,'Physical frames':l.frames,'Flat page table (bytes)':l.tableBytes,'Virtual page number':r.page,'Offset':r.offset,'Access result':r.status,...(r.status==='TRANSLATED'?{'Physical address':'0x'+r.physicalAddress.toString(16).toUpperCase()}: {})})};}
 throw new Error('Workspace unavailable.');
}
export default function Workspace({tool}:{tool:Tool}){
 const fields=specs[tool.id];const defaults=()=>Object.fromEntries(fields.map(f=>[f.key,f.initial]));
 const [values,setValues]=useState(defaults),[result,setResult]=useState(()=>calculate(tool.id,defaults())),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[cursor,setCursor]=useState(0);
 function run(){try{setResult(calculate(tool.id,values));setError('');setDirty(false);setCursor(0);}catch(e){setError(e instanceof Error?e.message:'Check the supplied values.');}}
 const trace=result.trace,step=trace?.[cursor-1];
 return <section id="co-workspace" className="ds-co-workspace" aria-labelledby="workspace-title"><p className="ds-study-eyebrow">Interactive teaching model</p><h2 id="workspace-title">{tool.name}</h2><p>{tool.summary}</p><p className="ds-co-assumptions">{tool.assumptions}</p>
 <form onSubmit={e=>{e.preventDefault();run();}}><div className="ds-co-fields">{fields.map(f=><label key={f.key}>{f.label}{f.options?<select value={values[f.key]} onChange={e=>{setValues({...values,[f.key]:e.target.value});setDirty(true);}}>{f.options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input autoComplete="off" spellCheck={false} value={values[f.key]} maxLength={600} onChange={e=>{setValues({...values,[f.key]:e.target.value});setDirty(true);}}/>}</label>)}</div><div className="ds-storage-actions"><button className="ds-button ds-practice-primary" type="submit">Calculate</button><button className="ds-button" type="button" onClick={()=>{setValues(defaults());setResult(calculate(tool.id,defaults()));setError('');setDirty(false);setCursor(0);}}>Reset workspace</button></div></form>
 {error&&<p role="alert" className="ds-storage-error">{error}</p>}{dirty&&<p role="status">Inputs changed. Calculate to update the result below.</p>}
 <div className="ds-co-result" aria-label="Workspace result" aria-live="polite"><dl>{result.facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{result.table&&<div className="ds-study-table-wrap"><table><caption>{result.table.caption}</caption><thead><tr>{result.table.headers.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{result.table.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
 {trace&&<><p>Read {cursor} of {trace.length} · {cursor===0?'Cache empty':`Address ${step!.address} → set ${step!.set}, tag ${step!.tag}: ${step!.hit?'HIT':'MISS'}. ${step!.evicted===null?'No eviction.':`Evicted tag ${step!.evicted}.`}`}</p><div className="ds-storage-actions"><button className="ds-button" disabled={dirty||cursor===0} onClick={()=>setCursor(c=>c-1)}>Previous read</button><button className="ds-button" disabled={dirty||cursor===trace.length} onClick={()=>setCursor(c=>c+1)}>Next read</button></div><p>Set contents, least → most recently used:</p><ul>{(step?.sets??trace[0].sets.map(()=>[])).map((tags,i)=><li key={i}>Set {i}: {tags.length?tags.join(' → '):'empty'}</li>)}</ul></>}
 </div><details><summary>Workspace source and skill scope</summary><Sources ids={tool.sourceIds}/><ul>{tool.skillIds.map(id=><li key={id}><CanonicalLink id={id}/></li>)}</ul><p>This workspace stores no student data and assigns no grade.</p></details></section>;
}
