import {build} from 'vite';
import {finalBundleInventory} from './final-bundle-inventory';
import {writeFileSync,readFileSync,readdirSync} from 'node:fs';
import {gzipSync} from 'node:zlib';
import {relative} from 'node:path';
const {chunks,assets,plugin}=finalBundleInventory('rl-acceptance-module-inventory');
await build({logLevel:'warn',plugins:[plugin]});
const entry=chunks.find(c=>c.entry)!;const initial=new Set<string>();function visit(file:string){if(initial.has(file))return;initial.add(file);chunks.find(c=>c.file===file)?.imports.forEach(visit);}visit(entry.file);
const mainModules=chunks.filter(c=>initial.has(c.file)).flatMap(c=>c.modules);
const allModules=chunks.flatMap(c=>c.modules);
const forbidden=allModules.filter(m=>/content-pack\/|scripts\/|co\/(?:content-lock|coverage)\.json|topic-study\/content-lock\.json/.test(m));
if(forbidden.length)throw new Error('Development-only modules bundled: '+forbidden.join(', '));
if(mainModules.some(m=>/src\/co\/(?:topics\/|Workspace|models|practice\.json)|src\/engine\/|src\/AssemblyWorkbench/.test(m)))throw new Error('CO content/tools or Assembly unexpectedly entered the initial dependency graph.');
if(chunks.filter(c=>c.modules.some(m=>/src\/co\/topics\/.*\.json$/.test(m))).length!==13)throw new Error('Thirteen independently lazy CO bundles required.');
// Inspect every final emitted byte after generation; HTML is measured separately from the established non-HTML asset totals.
for(const item of [...chunks,...assets]){const emitted=readFileSync('dist/'+item.file);item.bytes=emitted.length;item.gzipBytes=gzipSync(emitted).length;}
if(mainModules.some(m=>/src\/rl\/(?:topics\/|.*Workspace|logic|models|practice\.json|TopicContent|intro-guided)/.test(m)))throw new Error('R&L content or workspaces entered the initial dependency graph.');
if(allModules.some(m=>/src\/rl\/(?:content-lock|coverage|source-policy)\.json/.test(m)))throw new Error('R&L build-only data bundled.');
if(chunks.filter(c=>c.modules.some(m=>/src\/rl\/topics\/.*\.json$/.test(m))).length!==8)throw new Error('Eight independently lazy new R&L topics required.');
if(chunks.filter(c=>c.modules.some(m=>/src\/rl\/(?:Proposition|Fol|Recurrence|TreeGraph|Sets|Relations)Workspace\.tsx$/.test(m))).length!==6)throw new Error('Six independently lazy calculation workspaces required.');
const emittedFiles=readdirSync('dist',{recursive:true,withFileTypes:true}).filter(f=>f.isFile()).map(f=>{const file=relative('dist',f.parentPath+'/'+f.name);const bytes=readFileSync('dist/'+file);return {file,bytes:bytes.length,gzipBytes:gzipSync(bytes).length};});
const report={emittedFiles,totalProductionBytes:emittedFiles.reduce((sum,f)=>sum+f.bytes,0),totalProductionGzipBytes:emittedFiles.reduce((sum,f)=>sum+f.gzipBytes,0),authoredRLLazyBytes:chunks.filter(c=>c.modules.some(m=>/src\/rl\/topics\//.test(m))).reduce((sum,c)=>sum+c.bytes,0),rlTopicChunks:chunks.filter(c=>c.modules.some(m=>/src\/rl\/topics\//.test(m))).map(c=>({file:c.file,bytes:c.bytes,gzipBytes:c.gzipBytes})),rlToolChunks:chunks.filter(c=>c.modules.some(m=>/src\/rl\/(?:.*Workspace|logic|models)\./.test(m))).map(c=>({file:c.file,bytes:c.bytes,gzipBytes:c.gzipBytes})),initialChunks:[...initial],initialJSBytes:chunks.filter(c=>initial.has(c.file)).reduce((s,c)=>s+c.bytes,0),initialJSGzipBytes:chunks.filter(c=>initial.has(c.file)).reduce((s,c)=>s+c.gzipBytes,0),authoredCOLazyBytes:chunks.filter(c=>c.modules.some(m=>/src\/co\/topics\//.test(m))).reduce((s,c)=>s+c.bytes,0),totalAssetBytes:[...chunks,...assets.filter(asset=>!asset.file.endsWith('.html'))].reduce((s,c)=>s+c.bytes,0),totalAssetGzipBytes:[...chunks,...assets.filter(asset=>!asset.file.endsWith('.html'))].reduce((s,c)=>s+c.gzipBytes,0),chunks,assets,checks:['eight R&L topic chunks; published pilot content preserved','six R&L calculation workspace chunks plus shared bounded model modules','R&L topic content/tools/Practice definitions absent from initial graph','R&L full build-only locks/coverage/source-policy absent from all runtime chunks','all production gates executed directly by Vite','13 CO topic chunks','CO models/workspace/Practice definitions and Assembly absent from initial graph','full pack, validators, CO content locks/coverage and pilot locks absent from browser','sizes measured from final emitted assets after Vite preload rewriting']};
writeFileSync('docs/rl-bundle-report.json',JSON.stringify(report,null,2)+'\n');console.log(`RL bundle PASS: initial JS ${report.initialJSBytes} bytes; ${report.authoredRLLazyBytes} bytes R&L topic content; total ${report.totalAssetBytes} bytes. See docs/rl-bundle-report.json.`);
