import {storageMigrationHash} from './storage-migration-preservation';
import {readFileSync,readdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import type {Plugin} from 'vite';
import projectionData from '../src/generated/topic-study.json';
import pilotLessons from '../src/topic-study/lessons.json';
import pilotCards from '../src/topic-study/flashcards.json';
import oldPractice from '../src/practice/catalog.json';
import type {AuthoredScope,StudyProjection} from '../src/topic-study/types';
import type {GuidedActivity} from '../src/rl/types';
import type {Evidence,FeedbackProfile,Misconception,StudyCue} from '../src/enrichment/types';
import type {IPTopicContent,IPExercise,IPAssignment,IPReference,SkillCoverage,IPCapability,CodeFile} from '../src/ip/types';
import {gradeIPResponse} from '../src/ip/grading';
import {canonical,validateGraderSource} from './practice-catalog';
import {checkTopicStudy,trustedTopicStudySource} from './topic-projection';
import type {ContentPack} from './content/types';
export interface IPData {topics:IPTopicContent[];exercises:IPExercise[];coverage:SkillCoverage[];assignments:IPAssignment[];references:IPReference[];introGuided:GuidedActivity[];evidence:Evidence[];feedback:FeedbackProfile[];misconceptions:Misconception[];cues:StudyCue[];}
const root=new URL('../src/ip/',import.meta.url);
export const readIP=<T>(name:string):T=>JSON.parse(readFileSync(new URL(name,root),'utf8')) as T;
const files=<T>(directory:string):T[]=>readdirSync(new URL(directory+'/',root)).filter(f=>f.endsWith('.json')).sort().map(f=>readIP<T>(directory+'/'+f));
export function loadIP():IPData{return {topics:files('topics'),exercises:readIP('practice.json'),coverage:readIP('coverage.json'),assignments:files('assignments'),references:files('references'),introGuided:readIP('intro-guided.json'),evidence:readIP('evidence.json'),feedback:readIP('feedback.json'),misconceptions:readIP('misconceptions.json'),cues:readIP('cues.json')};}
export const digest=(value:unknown)=>createHash('sha256').update(canonical(value)).digest('hex');
const byteHash=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
function need(value:unknown,message:string):asserts value {if(!value)throw new Error('IP content: '+message);}
function shape(value:unknown,required:string[],optional:string[]=[]){need(value&&typeof value==='object'&&!Array.isArray(value),'expected object');const keys=Object.keys(value);need(required.every(k=>keys.includes(k))&&keys.every(k=>required.includes(k)||optional.includes(k)),'unsupported or missing fields');}
function text(value:unknown,max=5000):asserts value is string {need(typeof value==='string'&&value.trim().length>0&&value.length<=max,'text bounds');}
function list(value:unknown,min=1,max=100):asserts value is string[]{need(Array.isArray(value)&&value.length>=min&&value.length<=max,'list bounds');value.forEach(v=>text(v));need(new Set(value).size===value.length,'duplicate list member');}
const same=(a:readonly string[],b:readonly string[])=>canonical([...a].sort())===canonical([...b].sort());
const unique=(items:{id:string}[],what:string)=>need(new Set(items.map(x=>x.id)).size===items.length,'duplicate '+what+' identity');
function identity(item:{id:string;version:string},prefix:string){text(item.id,140);need(item.id.startsWith(prefix)&&/^[1-9]\d{0,7}$/.test(item.version),'authored identity/version');}
const scopeKeys=['id','version','topicId','skillIds','subtopicIds','sourceIds'];
const pilot='IP_T02_CONTROL_FLOW';
export function ipRecords(data:IPData){return [...data.topics.flatMap(t=>[t.lesson,...t.lesson.blocks,...t.cards,...t.guided]),...data.introGuided,...data.exercises,...data.assignments,...data.references,...data.evidence.map(e=>({...e,version:'1'})),...data.feedback,...data.misconceptions,...data.cues,...data.coverage.map(c=>({...c,id:'ds.coverage.'+c.skillId,version:'1'}))];}
export function ipCapabilities(data:IPData):IPCapability[]{return projectionData.topics.filter(t=>t.subjectId==='CSE1100_IP').map(t=>{const bundle=data.topics.find(b=>b.lesson.topicId===t.id);return {topicId:t.id,lessonId:(bundle?.lesson??pilotLessons.find(l=>l.topicId===t.id))!.id,cardCount:bundle?.cards.length??pilotCards.filter(c=>c.topicId===t.id).length,exerciseCount:[...data.exercises,...oldPractice].filter(e=>e.topicId===t.id).length,guidedCount:bundle?.guided.length??data.introGuided.length,assignmentCount:data.assignments.filter(a=>a.relatedTopicIds.includes(t.id)).length};});}
export function readIPPack():ContentPack{return JSON.parse(readFileSync(new URL('../content-pack/v1.0.1/DelftStudy_Codex_Handoff_Pack.json',import.meta.url),'utf8')) as ContentPack;}
/** Analytical components remain imprecise even when the original source is now available. */
export function validateIPSourcePolicy(pack=readIPPack()){
 const expected:Record<string,[string,string,string,string]>={IP_RESIT_2024:['RESIT','OFFICIAL_ASSESSMENT','RECENT','HIGH'],IP_MOCK_2024:['MOCK','OFFICIAL_PRACTICE_MATERIAL','CURRENT','VERY_HIGH'],IP_MOCK_2023:['MOCK','OFFICIAL_PRACTICE_MATERIAL','RECENT','HIGH'],IP_END_2024:['ENDTERM','OFFICIAL_ASSESSMENT','CURRENT','VERY_HIGH'],IP_END_2023:['ENDTERM','OFFICIAL_ASSESSMENT','RECENT','HIGH'],IP_END_2021:['ENDTERM','OFFICIAL_ASSESSMENT','HISTORICAL','MEDIUM_HIGH'],IP_END_2020:['ENDTERM','OFFICIAL_ASSESSMENT','HISTORICAL','MEDIUM']};
 const assessments=pack.assessment_model.assessments.filter(a=>a.subject_id==='CSE1100_IP');need(assessments.length===7&&same(assessments.map(a=>a.document_id),Object.keys(expected))&&new Set(assessments.map(a=>a.document_id)).size===7,'seven distinct canonical IP assessments');
 for(const a of assessments){const policy=expected[a.document_id];need(policy&&canonical([a.assessment_type,a.official_status,a.evidence_era,a.current_style_weight])===canonical(policy),'assessment era/authority/style policy');const doc=pack.corpus.documents.find(d=>d.document_id===a.document_id);need(doc&&doc.official_status===a.official_status&&doc.evidence_era===a.evidence_era&&doc.current_style_weight===a.current_style_weight,'document assessment policy consistency');need(a.question_map.filter(q=>q.mapping_granularity==='INTEGRATED_MULTI_SKILL').length===1,'one integrated whole program per assessment');for(const q of a.question_map)need(q.assessment_id===a.assessment_id&&q.document_id===a.document_id&&q.official_status===a.official_status&&q.evidence_era===a.evidence_era&&q.current_style_weight===a.current_style_weight&&q.assessment_type===a.assessment_type,'question source authority/era consistency');}
 const questions=assessments.flatMap(a=>a.question_map);need(questions.length===45,'45 canonical IP mappings');
 const whole=questions.filter(q=>q.mapping_granularity==='INTEGRATED_MULTI_SKILL');const components=questions.filter(q=>q.mapping_granularity==='SKILL_LEVEL');need(whole.length===7&&components.length===38,'integrated/component mapping boundary');
 for(const q of whole){const locator=q.source_locator as Record<string,unknown>;need(q.skill_mastery_update_policy==='REQUIRES_COMPONENT_RUBRIC_OR_TEST_EVIDENCE'&&!q.historical_skill_frequency_eligible,'whole assignment cannot award broad child-skill evidence');need(locator.kind==='PDF_PAGE_RANGE'&&locator.method==='WHOLE_DOCUMENT_RANGE','integrated whole-document locator');}
 for(const q of components){const locator=q.source_locator as Record<string,unknown>;shape(locator,['kind','method','confidence']);need(q.source_page_or_slide==='UNKNOWN'&&locator.kind==='UNKNOWN'&&locator.confidence==='UNVERIFIED'&&locator.method==='ANALYTICAL_COMPONENT_NOT_EXACTLY_LOCATABLE','unknown component locator promoted');}
 return {assessments:7,integratedMappings:7,unknownComponentMappings:38};
}
export function validateIP(data:IPData,projection:StudyProjection=projectionData){
 shape(data,['topics','exercises','coverage','assignments','references','introGuided','evidence','feedback','misconceptions','cues']);
 const topics=projection.topics.filter(t=>t.subjectId==='CSE1100_IP');const skills=topics.flatMap(t=>t.subtopics.flatMap(s=>s.skills.map(k=>({...k,topicId:t.id,subtopicId:s.id}))));
 need(topics.length===20&&topics.flatMap(t=>t.subtopics).length===44&&skills.length===56,'20 topics / 44 subtopics / 56 skills');
 const sourceById=new Map(projection.sources.map(s=>[s.id,s]));const pack=readIPPack();
 function scope(item:AuthoredScope,prefix:string,allowedTopics=[item.topicId]){
  identity(item,prefix);list(item.skillIds);list(item.subtopicIds);list(item.sourceIds);need(topics.some(t=>t.id===item.topicId),'primary topic ownership');
  const selected=item.skillIds.map(id=>skills.find(s=>s.id===id));need(selected.every(s=>s&&allowedTopics.includes(s.topicId)),'canonical skill ownership');
  need(same([...new Set(selected.map(s=>s!.subtopicId))],item.subtopicIds),'canonical subtopic ownership');
  need(selected.every(s=>s!.sources.some(id=>item.sourceIds.includes(id)))&&item.sourceIds.every(id=>selected.some(s=>s!.sources.includes(id))),'canonical source association');
  need(item.sourceIds.every(id=>{const s=sourceById.get(id);return s&&s.documentId.startsWith('IP_LEC_')&&s.confidence==='HIGH'&&s.precision==='DOCUMENT_RANGE'&&s.kind==='PDF_PAGE_RANGE';}),'source precision and lecture authority');
 }
 need(Array.isArray(data.evidence)&&data.evidence.length===24,'24 verified source records');unique(data.evidence,'evidence');
 const evidenceById=new Map(data.evidence.map(e=>[e.id,e]));
 for(const e of data.evidence){shape(e,['id','filename','pages','section','authority','skillIds']);list(e.skillIds);text(e.section);need(e.skillIds.every(id=>skills.some(s=>s.id===id)),'evidence outside canonical IP scope');
  let documentId:string|undefined;const matched=/^ip-t(\d\d)$/.exec(e.id);
  if(matched){const topic=topics.find(t=>t.id.startsWith('IP_T'+matched[1]+'_'));need(topic,'verified topic evidence identity');const owned=skills.filter(s=>s.topicId===topic.id);need(same(owned.map(s=>s.id),e.skillIds),'verified evidence skill scope');documentId=sourceById.get(owned[0].sources[0])?.documentId;need(e.authority==='OFFICIAL_LECTURE','lecture evidence authority');}
  else {const docs:Record<string,string>={'ip-exam-workflow':'IP_LEC_16','ip-integrated-current':'IP_END_2024','ip-integrated-mock':'IP_MOCK_2024','ip-integrated-recent':'IP_RESIT_2024'};documentId=docs[e.id];need(documentId,'unreviewed source cannot establish authority');need(e.authority===(e.id==='ip-exam-workflow'?'OFFICIAL_LECTURE':e.id==='ip-integrated-mock'?'OFFICIAL_PRACTICE_MATERIAL':'OFFICIAL_ASSESSMENT'),'practice source cannot be promoted to assessment');}
  const doc=pack.corpus.documents.find(d=>d.document_id===documentId);need(doc&&doc.filename===e.filename,'verified source filename');
  const lecture=projection.sources.find(s=>s.documentId===documentId&&s.precision==='DOCUMENT_RANGE');const whole=pack.assessment_model.assessments.find(a=>a.document_id===documentId)?.question_map.find(q=>q.mapping_granularity==='INTEGRATED_MULTI_SKILL');
  const maxPage=lecture?Number(lecture.locator.match(/-(\d+)$/)?.[1]):Number((whole?.source_locator as Record<string,unknown>|undefined)?.end_page);
  need(Array.isArray(e.pages)&&e.pages.length>0&&new Set(e.pages).size===e.pages.length&&e.pages.every(n=>Number.isInteger(n)&&n>0&&n<=maxPage),'physical page bounds');
 }
 function evidence(item:{evidenceIds:string[];skillIds:string[]}){list(item.evidenceIds);need(item.evidenceIds.every(id=>evidenceById.has(id)),'unknown verified evidence');need(item.skillIds.every(skill=>item.evidenceIds.some(id=>evidenceById.get(id)!.skillIds.includes(skill))),'unverified skill evidence');}
 function guides(items:GuidedActivity[],topicId:string){need(Array.isArray(items)&&items.length>0,'guided self-check required');unique(items,'guided');for(const g of items){shape(g,[...scopeKeys,'title','prompt','fields','rubric','reference']);scope(g,'ds.guided.ip.');need(g.topicId===topicId,'guide topic ownership');text(g.title,200);text(g.prompt);need(Array.isArray(g.fields)&&g.fields.length>0&&g.fields.length<=8,'guided fields');unique(g.fields,'field');for(const f of g.fields){shape(f,['id','label'],['placeholder']);text(f.id,80);text(f.label,300);if(f.placeholder!==undefined)text(f.placeholder);}list(g.rubric);list(g.reference);}}
 need(Array.isArray(data.topics)&&data.topics.length===19,'19 new lessons; published T02 preserved');
 for(const bundle of data.topics){shape(bundle,['lesson','cards','guided']);const l=bundle.lesson;shape(l,['id','version','topicId','blocks']);identity(l,'ds.lesson.ip.');need(l.topicId!==pilot&&topics.some(t=>t.id===l.topicId),'published pilot and topic ownership');need(Array.isArray(l.blocks)&&l.blocks.length>=4&&l.blocks.length<=20,'lesson block bounds');
  for(const b of l.blocks){shape(b,[...scopeKeys,'kind','title','paragraphs'],['code','table']);scope(b,'ds.block.ip.');need(b.topicId===l.topicId,'lesson block topic ownership');need(['introduction','concept','procedure','worked_example','important_rule','common_pitfall','code_example','recap'].includes(b.kind),'safe block kind');text(b.title,200);list(b.paragraphs,1,8);if(b.code!==undefined){text(b.code,16000);need(['worked_example','code_example'].includes(b.kind),'code example role');}if(b.table){shape(b.table,['headers','rows']);list(b.table.headers,1,12);need(Array.isArray(b.table.rows)&&b.table.rows.length>0&&b.table.rows.length<=30,'table row bounds');for(const r of b.table.rows){need(Array.isArray(r)&&r.length===b.table.headers.length,'table shape');r.forEach(v=>text(v,1000));}}}
  need(l.blocks[0].kind==='introduction'&&l.blocks.at(-1)!.kind==='recap'&&l.blocks.some(b=>['worked_example','code_example'].includes(b.kind)),'coherent lesson structure');
  const owned=skills.filter(s=>s.topicId===l.topicId);need(owned.every(s=>l.blocks.some(b=>b.skillIds.includes(s.id)&&!['introduction','recap'].includes(b.kind))),'substantive teaching coverage');
  need(Array.isArray(bundle.cards)&&bundle.cards.length>0,'cards required');for(const c of bundle.cards){shape(c,[...scopeKeys,'prompt','answer']);scope(c,'ds.card.ip.');need(c.topicId===l.topicId,'card topic ownership');text(c.prompt,900);text(c.answer,2000);}need(owned.every(s=>bundle.cards.some(c=>c.skillIds.includes(s.id))),'flashcard skill coverage');guides(bundle.guided,l.topicId);
 }
 need(new Set(data.topics.map(t=>t.lesson.topicId)).size===19,'duplicate topic lesson');guides(data.introGuided,pilot);
 need(pilotLessons.filter(l=>l.topicId===pilot).length===1&&pilotCards.filter(c=>c.topicId===pilot).length===8,'preserved pilot inventory');
 need(Array.isArray(data.exercises)&&data.exercises.length>0,'fixed predictions required');
 const grader=readIP<{id:string;version:string;sha256:string}>('grader-lock.json');
 for(const e of data.exercises){shape(e,['id','version','title','prompt','rules','subjectId','topicId','subtopicId','skillId','authorship','source','grader','task','reference','explanation']);identity(e,'ds.practice.ip-');need(e.subjectId==='CSE1100_IP'&&e.authorship==='AUTHORED_PRACTICE','practice authorship');const skill=skills.find(s=>s.id===e.skillId&&s.topicId===e.topicId&&s.subtopicId===e.subtopicId);need(skill,'practice canonical ownership');[e.title,e.prompt,e.rules,e.explanation].forEach(v=>text(v,12000));shape(e.source,['kind','documentId','filename','locator','precision']);need(e.source.kind==='LECTURE'&&e.source.precision==='DOCUMENT_RANGE','practice lecture precision');need(skill.sources.some(id=>{const s=sourceById.get(id)!;return s.confidence==='HIGH'&&s.documentId===e.source.documentId&&s.filename===e.source.filename&&s.locator===e.source.locator&&s.precision===e.source.precision;}),'practice provenance');shape(e.task,['kind','code','options']);need(e.task.kind==='ip-fixed','learner Java cannot be an automatic grading task');text(e.task.code,12000);need(Array.isArray(e.task.options)&&e.task.options.length>=2&&e.task.options.length<=6,'fixed option bounds');unique(e.task.options,'option');for(const o of e.task.options){shape(o,['id','output']);text(o.id,100);text(o.output,1000);}need(new Set(e.task.options.map(o=>o.output.trim())).size===e.task.options.length,'ambiguous displayed options');shape(e.grader,['id','version']);shape(e.reference,['kind','value']);need(e.grader.id==='ip-fixed-choice'&&e.grader.version==='1','fixed grader identity');const grade=gradeIPResponse(e,e.reference);need(grade.status==='GRADED'&&grade.correct,'independently checked reference format');}
 for(const item of data.misconceptions){shape(item,[...scopeKeys,'evidenceIds','label','rule']);scope(item,'ds.misconception.ip.');evidence(item);text(item.label,300);text(item.rule);}
 for(const p of data.feedback){shape(p,[...scopeKeys,'evidenceIds','exerciseId','binding','reasoning','remember','fallback','paths']);scope(p,'ds.feedback.ip.');evidence(p);const e=data.exercises.find(e=>e.id===p.exerciseId);need(e&&p.skillIds.length===1&&p.skillIds[0]===e.skillId,'feedback exercise ownership');need(p.binding===`${e.version}:sha256:${digest(e)}:grader:${grader.sha256}`,'exact feedback version binding');[p.reasoning,p.remember,p.fallback].forEach(v=>text(v));need(Array.isArray(p.paths)&&p.paths.length>0&&p.paths.length<=5,'bounded feedback patterns');need(new Set(p.paths.map(x=>x.answer)).size===p.paths.length,'ambiguous feedback pattern');for(const path of p.paths){shape(path,['answer','misconceptionId','why']);text(path.why);const grade=gradeIPResponse(e,{kind:'choice',value:[path.answer]});need(grade.status==='GRADED'&&!grade.correct,'feedback pattern must be a valid wrong option');need(data.misconceptions.some(m=>m.id===path.misconceptionId&&m.skillIds.includes(e.skillId)),'misconception skill ownership');}}
 need(data.feedback.length===data.exercises.length&&new Set(data.feedback.map(p=>p.exerciseId)).size===data.exercises.length,'every fixed prediction has one bound feedback profile');
 for(const cue of data.cues){shape(cue,[...scopeKeys,'evidenceIds','text']);scope(cue,'ds.cue.ip.');evidence(cue);text(cue.text);}
 function codeFiles(entries:CodeFile[]){need(Array.isArray(entries)&&entries.length>0&&entries.length<=30,'code file count');need(new Set(entries.map(f=>f.name.toLowerCase())).size===entries.length,'duplicate code filename');for(const file of entries){shape(file,['name','language','content']);need(/^[A-Za-z][A-Za-z0-9_.-]*\.(?:java|txt|csv|data)$/.test(file.name)&&!file.name.includes('..'),'safe flat authored filename');need(file.language===(file.name.endsWith('.java')?'java':'text'),'code file language');text(file.content,60000);}}
 need(data.assignments.length>=3&&[15,30,60].every(n=>data.assignments.some(a=>a.minutes===n)),'authored 15/30/60 practice coverage');need(data.assignments.filter(a=>a.minutes===60&&a.topicId==='IP_T20_EXAM_PROGRAM_SYNTHESIS').length>=3,'several integrated T20 workflows');need(data.references.length===data.assignments.length,'one reference per assignment');
 for(const a of data.assignments){shape(a,['id','version','title','minutes','topicId','relatedTopicIds','skillIds','subtopicIds','sourceIds','evidenceIds','instructions','starterFiles','requirements','rubric','referenceId']);list(a.relatedTopicIds);need(a.relatedTopicIds.includes(a.topicId),'primary topic included in assignment links');scope(a,'ds.assignment.ip.',a.relatedTopicIds);need(same(a.relatedTopicIds,[...new Set(a.skillIds.map(id=>skills.find(s=>s.id===id)!.topicId))]),'exact assignment topic scope');evidence(a);text(a.title,220);need([15,30,60].includes(a.minutes),'authored time class');list(a.instructions);codeFiles(a.starterFiles);need(a.requirements.length>0&&a.rubric.length>0,'component requirements and rubric');unique(a.requirements,'requirement');unique(a.rubric,'rubric');
  for(const r of a.requirements){shape(r,['id','text','skillIds']);text(r.id,100);text(r.text);list(r.skillIds);need(r.skillIds.every(id=>a.skillIds.includes(id)),'requirement skill scope');}need(same([...new Set(a.requirements.flatMap(r=>r.skillIds))],a.skillIds),'all assignment skills have component requirements');
  const ref=data.references.find(r=>r.id===a.referenceId&&r.assignmentId===a.id);need(ref,'reference assignment binding');shape(ref,['id','version','assignmentId','files','tests','reasoning']);identity(ref,'ds.reference.ip.');need(ref.version===a.version,'reference version binding');codeFiles(ref.files);list(ref.reasoning);need(ref.tests.length>0,'reference test specifications');unique(ref.tests,'test');
  for(const t of ref.tests){shape(t,['id','name','requirementIds','skillIds','description','expected']);text(t.id,120);[t.name,t.description,t.expected].forEach(v=>text(v,7000));list(t.requirementIds);list(t.skillIds);need(t.requirementIds.every(id=>a.requirements.some(r=>r.id===id)),'test requirement link');const owned=[...new Set(a.requirements.filter(r=>t.requirementIds.includes(r.id)).flatMap(r=>r.skillIds))];need(t.skillIds.every(id=>owned.includes(id)),'test skill requirement link');}
  for(const r of a.rubric){shape(r,['id','text','requirementIds','skillIds','testIds']);text(r.id,120);text(r.text);list(r.requirementIds);list(r.skillIds);list(r.testIds);need(r.requirementIds.every(id=>a.requirements.some(x=>x.id===id)),'rubric requirement link');const owned=a.requirements.filter(x=>r.requirementIds.includes(x.id)).flatMap(x=>x.skillIds);need(r.skillIds.every(id=>owned.includes(id)),'rubric skill link');need(r.testIds.every(id=>ref.tests.some(t=>t.id===id&&r.requirementIds.some(req=>t.requirementIds.includes(req)))),'rubric test link');need(r.skillIds.every(id=>r.testIds.some(test=>ref.tests.find(t=>t.id===test)!.skillIds.includes(id))),'rubric component test evidence');}
  need(a.requirements.every(r=>ref.tests.some(t=>t.requirementIds.includes(r.id))&&a.rubric.some(c=>c.requirementIds.includes(r.id))),'every requirement has rubric and test evidence');
 }
 const guidesAll=[...data.introGuided,...data.topics.flatMap(t=>t.guided)];const exercisesAll=[...oldPractice,...data.exercises];
 need(data.coverage.length===56&&new Set(data.coverage.map(c=>c.skillId)).size===56,'56 deliberate practice classifications');
 for(const c of data.coverage){shape(c,['skillId','category','reason','exerciseIds','guidedIds','assignmentIds']);need(skills.some(s=>s.id===c.skillId)&&['A','B','C','D','E'].includes(c.category),'practice classification identity');text(c.reason);list(c.exerciseIds,0);list(c.guidedIds,0);list(c.assignmentIds,0);need(c.exerciseIds.every(id=>exercisesAll.some(e=>e.id===id&&e.skillId===c.skillId)),'classification exercise link');need(c.guidedIds.every(id=>guidesAll.some(g=>g.id===id&&g.skillIds.includes(c.skillId))),'classification guided link');need(c.assignmentIds.every(id=>data.assignments.some(a=>a.id===id&&a.skillIds.includes(c.skillId))),'classification assignment link');need(c.category!=='A'||c.exerciseIds.length>0,'A requires deterministic exercise');need(!['B','C'].includes(c.category)||c.guidedIds.length+c.assignmentIds.length>0,'open classification requires rubric');need(c.category!=='D'||c.assignmentIds.length>0,'workspace classification requires assignment');}
 unique(ipRecords(data),'authored record');validateIPSourcePolicy();
 return {topics:20,subtopics:44,skills:56,lessons:20,cards:ipCapabilities(data).reduce((n,c)=>n+c.cardCount,0),newExercises:data.exercises.length,guides:guidesAll.length,assignments:data.assignments.length};
}
export function checkIPLocks(data:IPData,locks:Record<string,string>){const records=ipRecords(data);need(Object.keys(locks).length===records.length,'content lock inventory');for(const r of records)need(locks[r.id+'@'+r.version]===digest(r),'published version changed: '+r.id);}
export function validateIPFiles(){const source=trustedTopicStudySource();checkTopicStudy(source);const data=loadIP();const report=validateIP(data,JSON.parse(source) as StudyProjection);checkIPLocks(data,readIP('content-lock.json'));need(canonical(Object.fromEntries(data.exercises.map(e=>[e.id+'@'+e.version,digest(e)])))===canonical(readIP('practice-lock.json')),'practice lock inventory or fingerprint');validateGraderSource(readFileSync(new URL('grading.ts',root),'utf8'),readIP('grader-lock.json'));need(canonical(ipCapabilities(data))===canonical(readIP('capabilities.json')),'stale capability counts');
 const summaries=files<IPAssignment>('assignments').map(a=>({id:a.id,version:a.version,file:readdirSync(new URL('assignments/',root)).find(f=>f.endsWith('.json')&&readIP<IPAssignment>('assignments/'+f).id===a.id)!,title:a.title,minutes:a.minutes,topicId:a.topicId,relatedTopicIds:a.relatedTopicIds}));need(canonical(summaries)===canonical(readIP('assignment-index.json')),'stale assignment index');
 const baseline=JSON.parse(readFileSync(new URL('./ip-baseline.json',import.meta.url),'utf8')) as Record<string,string>;need(Object.keys(baseline).length>=83,'protected baseline inventory');for(const [file,hash] of Object.entries(baseline))need(byteHash(readFileSync(new URL('../'+file,import.meta.url)))===storageMigrationHash(file,hash),'protected baseline changed: '+file);return report;
}
export const ipBuildGuard=(validate=validateIPFiles):Plugin=>({name:'delftstudy-ip-course',apply:'build',buildStart(){validate();}});
