import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useAccount} from './context';
import {StudentDataPanel} from '../learning/StudentDataPanel';
import './accounts.css';
export function AccountPage() {
  const account=useAccount(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[displayName,setDisplayName]=useState(''),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[consent,setConsent]=useState(false),[restoreConsent,setRestoreConsent]=useState(false);
  const feedback=useRef<HTMLParagraphElement>(null);
  useEffect(()=>{if(error)feedback.current?.focus();},[error]);
  async function action(work:()=>Promise<unknown>) {if(busy)return;setBusy(true);setError('');setNotice('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Account action failed. Your local work is preserved.');}finally{setBusy(false);setPassword('');setDisplayName('');}}
  function submit(event:FormEvent){event.preventDefault();if(!account.auth)return;void displayName;void action(async()=>{
    if(creating){if(!displayName.trim())throw Error('Enter a display name.');const result=await account.auth!.signUp(email,password,displayName);setNotice(result.verificationRequired?'Check your email to verify the account, then return here and sign in. An account may already exist for this address.':'Account session opened. Your anonymous history stays separate until you choose to copy it.');}
    else await account.auth!.signIn(email,password);
  });}
  return <div className="ds-account"><header className="ds-page-heading"><p className="ds-eyebrow">Your study space</p><h1>Account & cloud sync</h1><p>Accounts are optional. Learning, saved answers and backups work locally.</p></header>
    <section className="ds-section"><h2>{account.state.user?'Account profile':'Anonymous local profile'}</h2>{account.state.user?.displayName?.trim()&&<p><strong>{account.state.user.displayName.trim()}</strong></p>}<p>{account.state.user?.email??'Your existing study history stays in this browser.'}</p><p role="status"><strong>{account.syncStatus}</strong>{account.syncMessage&&` — ${account.syncMessage}`}</p>{account.state.message&&<p>{account.state.message}</p>}
      {account.config.status!=='configured'?(account.syncMessage===account.config.message?null:<p>{account.config.message}</p>):account.state.user?<>
        <div className="ds-account-actions"><button disabled={busy||account.syncStatus==='Syncing'} onClick={()=>void action(()=>account.sync!())}>Sync now</button><button disabled={busy} onClick={()=>void action(()=>account.auth!.signOut())}>Sign out</button></div>
        {account.syncStatus==='Conflict requires attention'&&account.reconcile&&<details><summary>Recover after a backup restore during sync</summary><p>First export your current and recovery backups in Progress. This retries the saved upload with its original operation ID, then compares your restored data with that acknowledged history. Missing historical records can return. Conflicting submitted answers or concurrent drafts are still rejected.</p><label><input type="checkbox" checked={restoreConsent} onChange={e=>setRestoreConsent(e.target.checked)}/> Compare my restored profile with the saved cloud operation.</label><button disabled={!restoreConsent||busy} onClick={()=>void action(async()=>{await account.reconcile!();setRestoreConsent(false);})}>Compare restored history</button></details>}
        <p>Sync runs after sign-in and when you choose Sync now. New local work is marked pending. Signing out preserves this account’s local profile and returns to the separate anonymous profile.</p>
        <details><summary>Copy anonymous history into this account</summary><p>This copies saved attempts, exams and review records. It keeps the anonymous original and compares matching IDs. Conflicting histories stop the copy.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> I want to associate this browser’s anonymous study history with {account.state.user.email}.</label><button disabled={!consent||busy||account.syncStatus==='Syncing'} onClick={()=>void action(async()=>{await account.adopt!();setConsent(false);})}>Copy anonymous history</button></details>
      </>:<form onSubmit={submit}><h2>{creating?'Create an account':'Sign in'}</h2>{creating&&<label>Display name<input required maxLength={80} autoComplete="name" value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>}<label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={creating?'new-password':'current-password'} required minLength={creating?8:1} value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="ds-account-actions"><button type="submit" disabled={busy||!account.auth}>{busy?'Please wait…':creating?'Create account':'Sign in'}</button><button type="button" disabled={busy} onClick={()=>{setCreating(!creating);setPassword('');setError('');}}>{creating?'Use an existing account':'Create an account instead'}</button>{account.state.phase==='error'&&<button type="button" disabled={busy} onClick={()=>void action(()=>account.auth!.signOut())}>Retry sign-out</button>}</div><p>Passwords are sent to Supabase Auth and are not stored by DelftStudy. If email verification is enabled, verify first and then sign in here.</p></form>}
      {error&&<p ref={feedback} tabIndex={-1} role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    </section><StudentDataPanel/>
  </div>;
}
