import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link} from 'react-router';
import {useAccount} from './context';
import './accounts.css';
export function AccountPage(){
 const account=useAccount(); const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[displayName,setDisplayName]=useState('');
 const [creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''); const feedback=useRef<HTMLParagraphElement>(null);
 useEffect(()=>{if(error)feedback.current?.focus()},[error]);
 async function action(work:()=>Promise<unknown>){if(busy)return;setBusy(true);setError('');setNotice('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Account action failed. Your local work is preserved.')}finally{setBusy(false);setPassword('')}}
 function submit(event:FormEvent){event.preventDefault();if(!account.auth)return;void action(async()=>{if(creating){const name=displayName.trim();if(!name)throw Error('Enter a display name.');if(name.length>80)throw Error('Display name must be 80 characters or fewer.');const result=await account.auth!.signUp(email,password,name);setNotice(result.verificationRequired?'Check your email to verify the account, then return here and sign in.':'Account session opened.')}else await account.auth!.signIn(email,password)})}
 const user=account.state.user;
 return <div className="ds-account"><header className="ds-page-heading"><p className="ds-eyebrow">Your study space</p><h1>Account & cloud sync</h1><p>Accounts are optional. Learning, saved answers and backups work locally.</p></header><section className="ds-section"><h2>{user?'Account profile':'Anonymous local profile'}</h2>{user?<><p><strong>{user.displayName||'Your profile'}</strong></p><p>{user.email}</p><p role="status"><strong>{account.syncStatus}</strong>{account.syncMessage&&` — ${account.syncMessage}`}</p><button disabled={busy} onClick={()=>void action(()=>account.auth!.signOut())}>Sign out</button></>:<><p>Your existing study history stays in this browser.</p><p role="status"><strong>{account.syncStatus}</strong>{account.syncMessage&&` — ${account.syncMessage}`}</p>{account.config.status==='configured'&&<form onSubmit={submit}><h2>{creating?'Create an account':'Sign in'}</h2>{creating&&<label>Display name<input required maxLength={80} autoComplete="name" value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label>}<label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={creating?'new-password':'current-password'} required minLength={creating?8:1} value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="ds-account-actions"><button type="submit" disabled={busy}>{busy?'Please wait…':creating?'Create account':'Sign in'}</button><button type="button" disabled={busy} onClick={()=>{setCreating(!creating);setPassword('');setError('')}}>{creating?'Use an existing account':'Create an account instead'}</button></div><p>Passwords are sent to Supabase Auth and are not stored by DelftStudy.</p></form>}</>}{error&&<p ref={feedback} tabIndex={-1} role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</section><section className="ds-section"><h2>Local data & recovery</h2><p>Anonymous and account profiles are separate. Switching accounts never copies another account’s history.</p><Link className="ds-text-link" to="/progress">Export, restore or recover a local backup →</Link></section></div>;
}
