import {lazy,Suspense,useEffect,useState} from 'react';
import {Link,Route,Routes,useNavigate,useParams} from 'react-router';
import {courses} from '../academic/navigation';
import {useLearning} from '../learning/LearningProvider';
import {errorMessage} from '../learning/contracts';
import {PageHeading} from '../shell/PageParts';
import {examCourse,loadExamBank} from './catalog';
import {summary} from './engine';
import type {ExamBank,ExamCourse} from './types';
import './exams.css';
const SessionPage=lazy(()=>import('./ExamSessionPage').then(m=>({default:m.ExamSessionPage})));
const ReviewPage=lazy(()=>import('./ExamReviewPage').then(m=>({default:m.ExamReviewPage})));
function useBank(course:ExamCourse|null){const [bank,setBank]=useState<ExamBank|null>(null),[error,setError]=useState('');useEffect(()=>{setBank(null);setError('');let active=true;if(course)void loadExamBank(course).then(bank=>{if(active)setBank(bank);},()=>{if(active)setError('Exam content could not load. Reload to retry; saved data is preserved.');});return()=>{active=false;};},[course]);return {bank,error};}
function History(){const learning=useLearning()!,sessions=[...learning.snapshot!.data.exams].sort((a,b)=>b.startedAt.localeCompare(a.startedAt)||a.sessionId.localeCompare(b.sessionId));return <section className="exam-history"><h2>Local exam history</h2>{!sessions.length?<p>No exams yet. Start a quick set or a full authored mock above.</p>:sessions.map(session=>{const c=summary(session,learning.snapshot!.data.examReviews);return <article className="exam-card" key={session.sessionId}><h3>{courses.find(c=>c.subject_id===session.course)?.name} · {session.mode==='quick'?'Quick exam':'Full authored mock'}</h3><p>{session.status.replaceAll('_',' ')} · {new Date(session.startedAt).toLocaleString()} · {session.durationMinutes} minute limit{session.submission?` · ${Math.round((Date.parse(session.submission.submittedAt)-Date.parse(session.startedAt))/60000)} minutes until submission`:''}</p><p>{c.answered} answered · {c.unanswered} unanswered{session.status==='SUBMITTED'?` · Automatically verified ${c.autoEarned} / ${c.autoMax} points · ${c.openRemaining} open components await review`:''}</p><Link className="ds-button" to={`/exams/${session.status==='IN_PROGRESS'?'sessions':'review'}/${session.sessionId}`}>{session.status==='IN_PROGRESS'?'Resume exam':'Review saved responses'}</Link> <Link className="ds-button" to={`/exams/${session.course}/setup`}>New exam / retake</Link></article>;})}</section>;}
function Landing(){return <><PageHeading eyebrow="STUDY" title="Mock Exams"><p>Authored exam-style practice. Work under a fixed deadline, then review exact answers and open reasoning separately.</p></PageHeading><div className="exam-course-grid">{courses.map(c=><article className="exam-card" key={c.subject_id}><p>{c.code}</p><h2>{c.name}</h2><p>Quick practice and a full authored mock.</p><Link className="ds-button" to={`/exams/${c.subject_id}/setup`}>Choose an exam</Link></article>)}</div><p>Open proofs and Java code require self/rubric review. No official grade is provided. See Progress for separate evidence indices with coverage, confidence and limitations.</p><History/></>;}
function Setup(){const {courseId}=useParams(),course=examCourse(courseId),{bank,error}=useBank(course),learning=useLearning()!,navigate=useNavigate(),[seed,setSeed]=useState('foundation-v1'),[busy,setBusy]=useState(false),[failure,setFailure]=useState('');if(!course)return <p>Unknown exam course. <Link to="/exams">Return to Mock Exams</Link></p>;if(!bank)return <p role="status">{error||'Loading course exam bank…'}</p>;const readyBank=bank;
 async function start(id:string){setBusy(true);setFailure('');const sessionId=crypto.randomUUID();try{await learning.changeStudentData(repo=>repo.startExam(readyBank,id,seed,sessionId,learning.snapshot!.data));navigate(`/exams/sessions/${sessionId}`);}catch(e){setFailure(errorMessage(e));}finally{setBusy(false);}}
 return <div className="exam-page"><Link to="/exams">← Mock Exams</Link><h1>{courses.find(c=>c.subject_id===course)?.name}</h1><p>Authored exam-style practice · Fixed original questions · Exact version binding</p><label className="exam-seed">Reconstruction seed<input value={seed} maxLength={80} onChange={e=>setSeed(e.target.value)} disabled={busy}/></label><p>The first bank uses a fixed order and one candidate per slot. A different seed does not invent new questions.</p><div className="exam-course-grid">{bank.blueprints.map(b=><article className="exam-card" key={b.id}><h2>{b.title}</h2><p>{b.durationMinutes} minutes · {b.slots.length} components · {b.constraints.minOpen} open/rubric</p><p>{b.rationale}</p><details><summary>Coverage and difficulty</summary><ul>{b.constraints.topics.map(t=><li key={t}>{t}</li>)}</ul><p>{Object.entries(b.difficultyMix).map(([k,v])=>`${v} ${k}`).join(' · ')} — authored workload labels.</p></details><p>The timer starts when the session is saved. Reloading retains its deadline. At expiry, editing freezes and you confirm submission of saved responses.</p><button className="ds-button ds-button-primary" disabled={busy||!seed.trim()} onClick={()=>void start(b.id)}>{busy?'Starting…':b.mode==='quick'?'Start quick exam':'Start full mock'}</button></article>)}</div>{failure&&<p role="alert">{failure}</p>}</div>;
}
function SessionRoute({review=false}:{review?:boolean}){const learning=useLearning()!,{sessionId}=useParams(),session=learning.snapshot!.data.exams.find(s=>s.sessionId===sessionId),{bank,error}=useBank(session?.course??null);if(!session)return <><h1>Exam not found in this browser</h1><p>This link refers to local student data. Import a compatible backup or return to the exam list.</p><Link to="/exams">Mock Exams</Link></>;if(!bank)return <p role="status">{error||'Loading exact exam content…'}</p>;return <Suspense fallback={<p>Loading exam…</p>}>{review?<ReviewPage session={session} bank={bank}/>:<SessionPage key={session.sessionId} session={session} bank={bank}/>}</Suspense>;}
export function ExamsPage(){const learning=useLearning();if(!learning)return <><h1>Mock Exams</h1><p role="status">Student storage is not connected.</p></>;if(!learning.snapshot)return <p role="status">{learning.message}</p>;return <Routes><Route index element={<Landing/>}/><Route path="history" element={<><h1>Exam history</h1><Link to="/exams">Choose a new exam</Link><History/></>}/><Route path=":courseId/setup" element={<Setup/>}/><Route path="sessions/:sessionId" element={<SessionRoute/>}/><Route path="review/:sessionId" element={<SessionRoute review/>}/><Route path="*" element={<p>Exam page not found. <Link to="/exams">Mock Exams</Link></p>}/></Routes>;}
